Repository unlock-protocol/unlock, pull requests merged in 2018-12, with the labels that each got.

#720 Migrate from openzeppelin-solidity to openzeppelin-eth.
  smart-contracts/README.md
  smart-contracts/build/contracts/ERC721.json
  smart-contracts/build/contracts/ILockCore.json
  smart-contracts/build/contracts/ILockPublic.json
  smart-contracts/build/contracts/IUnlock.json
  smart-contracts/build/contracts/Initializable.json
  smart-contracts/build/contracts/Migrations.json
  smart-contracts/build/contracts/Ownable.json
  smart-contracts/build/contracts/PublicLock.json
  smart-contracts/build/contracts/Unlock.json
  smart-contracts/build/contracts/UnlockTestV2.json
  smart-contracts/build/contracts/UnlockTestV3.json
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/UnlockTestV3.sol
  smart-contracts/contracts/interfaces/ILockPublic.sol
  smart-contracts/npm-shrinkwrap.json
  smart-contracts/package.json
  smart-contracts/test/Lock/erc721/getApproved.js
  smart-contracts/test/Unlock/Unlock.js
  smart-contracts/test/Unlock/UnlockProxy.js
  smart-contracts/test/Unlock/behaviors/createLock.js
  smart-contracts/test/Unlock/behaviors/createLockWithInfiniteKeys.js
  smart-contracts/test/Unlock/behaviors/shared.js
  smart-contracts/test/helpers/deployLocks.js
  unlock-app/package-lock.json
Labels: blockchain, please test!

#717 New Profile Pics
  unlock-app/src/static/images/illustrations/akeem.jpg
  unlock-app/src/static/images/illustrations/julien.jpg
  unlock-app/src/static/images/illustrations/sascha.jpg
Labels: design

#845 Replaced old with new chevron svg
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/__tests__/utils/withConfig/__snapshots__/missingProvidersWithConfig.test.js.snap
  unlock-app/src/__tests__/utils/withConfig/__snapshots__/wrongNetwork.test.js.snap
  unlock-app/src/components/interface/svg/ChevronUp.js
  unlock-app/src/static/images/svg/chevron-up.svg
  unlock-app/src/static/images/svg/chevron.svg
Labels: design, p-3
