Repository unlock-protocol/unlock, pull requests merged in 2019-03, with the labels that each got.

#1780 Copy relevant stories over from unlock-app
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/stories/Paywall.stories.js
  paywall/stories/developer/DeveloperOverlay.stories.js
  paywall/stories/lock/Lock.stories.js
  paywall/stories/lock/UnlockFlag.stories.js
Labels: in progress

#1793 update config to be split-ready but work with existing app
  unlock-app/next.config.js
  unlock-app/src/components/creator/lock/EmbedCodeSnippet.js
  unlock-app/src/config.js
  unlock-app/src/pages/demo.js
  unlock-app/src/stories/lock/CodeSnippet.stories.js
Labels: in progress

#1785 fixing a couple redux action namespaces
  unlock-app/src/__tests__/components/creator/lock/KeyList.test.js
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/actions/key.js
  unlock-app/src/actions/keysPages.js
Labels: in progress

#1794 Refactored the signData method on walletService
  unlock-app/src/__tests__/services/walletService.test.js
  unlock-app/src/services/walletService.js
Labels: in progress

#1787 Add partialWithdrawFromLock method
  unlock-app/src/__tests__/services/walletService.test.js
  unlock-app/src/services/walletService.js
Labels: Partial Withdrawal, in progress

#1803 Pass proper type for keyPrice
  unlock-app/src/stories/creator/CreatorLockForm-errors.stories.js
Labels: in progress

#1812 Refactor walletService tests
  unlock-app/src/__tests__/services/walletService.test.js
Labels: in progress

#1810 fixing deployments to netlify on master
  scripts/deploy.sh
Labels: in progress

#1813 error on console.warn or console.error in storyshots tests
  paywall/src/__tests__/storybook/storyshots.test.js
  unlock-app/src/__tests__/storybook/storyshots.test.js
Labels: in progress

#1792 Renamed variable name to avoid confusion
  unlock-app/src/services/storageService.js
Labels: in progress

#1797 Adding disableLock test cases and added a couple isAlive requirements
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/disableLock.js
Labels: in progress

#1795 Adding approve test cases and fixed a couple bugs
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/approveForAll.js
Labels: in progress

#1799 Reviewing MixinLockCore
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/test/Lock/withdraw.js
Labels: in progress

#1798 Add ExpireKey event
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/expireKeyFor.js
Labels: in progress

#1808 Refactored how lock names are signed
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/middlewares/walletMiddleware.js
Labels: in progress

#1817 use constants for postmessage data
  paywall/paywall-builder/build.js
  paywall/paywall-builder/constants.js
  paywall/src/__tests__/middlewares/interWindowCommunicationMiddleware.test.js
  paywall/src/middlewares/interWindowCommunicationMiddleware.js
Labels: in progress

#1790 Remove old example Upgrade test files
  smart-contracts/contracts/UnlockTestV2.sol
  smart-contracts/contracts/UnlockTestV3.sol
  smart-contracts/test/Unlock/UnlockProxy.js
  smart-contracts/test/Unlock/upgrades.js
Labels: in progress

#1820 Stop overwriting key data on transfers
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/transferFrom.js
Labels: in progress

#1789 Refactor Mixin for Purchase functions
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: in progress

#1826 Fix inheritance compile issue
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: in progress

#1823 clean up old signature mechanism
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/utils/signature.test.js
  unlock-app/src/__tests__/utils/typedDataSignature.test.js
  unlock-app/src/utils/signature.js
  unlock-app/src/utils/typedDataSignature.js
Labels: in progress

#1824 Using camelCase on LockSmith
  locksmith/src/controllers/lockController.js
  locksmith/src/routes/lock.js
Labels: in progress

#1830 Adding an action to change the lock's name
  unlock-app/src/__tests__/actions/lock.test.js
  unlock-app/src/actions/lock.js
Labels: in progress

#1814 add deploy command
  paywall/.gitignore
  paywall/package.json
Labels: in progress

#1822 Revert "fixing deployments to netlify on master (#1810)"
  scripts/deploy.sh
Labels: in progress

#1844 added more files to nuke
  scripts/nuke.sh
Labels: in progress

#1837 moving the locksmith deploy script inside locksmith
  .circleci/config.yml
  .travis.yml
  locksmith/scripts/deploy-elasticbeanstalk.sh
Labels: in progress

#1836 removed the azure pipeline config
  azure-pipelines.yml
Labels: in progress

#1829 using a single method to set and update lock names
  locksmith/__tests__/app.test.js
  locksmith/jest.config.js
  locksmith/src/controllers/lockController.js
  locksmith/src/locksmithLogger.js
  locksmith/src/routes/lock.js
Labels: in progress

#1833 wrapping bash variables in quotes
  .circleci/config.yml
  .travis.yml
Labels: in progress

#1832 Solidity 0.5 update
  paywall/src/__tests__/services/walletService.test.js
  paywall/src/services/walletService.js
  smart-contracts/contracts/Migrations.sol
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/UnlockErrors.sol
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/interfaces/ILockCore.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/contracts/mixins/MixinDisableAndDestroy.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinLockMetadata.sol
  smart-contracts/contracts/mixins/MixinNoFallback.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/package-lock.json
  smart-contracts/package.json
  smart-contracts/reports/gas.js
  smart-contracts/test/Lock/destroyLock.js
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/noFallback.js
  smart-contracts/test/Unlock/TestUnlock.sol
  smart-contracts/test/Unlock/noFallback.js
  smart-contracts/test/Unlock/upgrades.js
  smart-contracts/test/helpers/deployLocks.js
  smart-contracts/test/helpers/shouldFail.js
  smart-contracts/test/helpers/walletServiceMock.js
  smart-contracts/truffle-config.js
  unlock-app/src/services/walletService.js
Labels: in progress

#1800 the deploy.sh script can now be used for any service
  .circleci/config.yml
  .travis.yml
  paywall/package.json
  paywall/scripts/deploy-netlify.sh
  scripts/deploy.sh
  unlock-app/package.json
  unlock-app/scripts/deploy-netlify.sh
Labels: in progress

#1835 Now using 307 when redirecting on errors.
  unlock-app/src/pages/_error.js
Labels: in progress

#1839 Updated the npm module for published ABI
  smart-contracts/published-npm-modules/V0/PublicLock.json
  smart-contracts/published-npm-modules/V0/README.md
  smart-contracts/published-npm-modules/V0/Unlock.json
  smart-contracts/published-npm-modules/V0/abi_V0.json
  smart-contracts/published-npm-modules/V0/index.js
  smart-contracts/published-npm-modules/V0/package.json
  smart-contracts/test/Unlock/upgrades.js
Labels: in progress

#1821 Refactor useListenForPostMessage
  paywall/paywall-builder/build.js
  paywall/src/__tests__/hooks/browser/useListenForPostMessage.test.js
  paywall/src/__tests__/paywall-builder/build.test.js
  paywall/src/hooks/browser/useListenForPostMessage.js
Labels: in progress

#1845 Lock names can be updated
  unlock-app/src/__tests__/components/creator/CreatorLock.test.js
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/creator/CreatorLock.js
  unlock-app/src/components/creator/CreatorLockForm.js
  unlock-app/src/middlewares/storageMiddleware.js
Labels: in progress

#1854 Moves Currency Lookup URI to configuration
  unlock-app/src/config.js
  unlock-app/src/middlewares/currencyConversionMiddleware.js
Labels: in progress

#1851 Refactor hooks to use window passed down through context.
  paywall/pages/_app.js
  paywall/src/__tests__/hooks/browser/useListenForPostMessage.test.js
  paywall/src/__tests__/hooks/browser/useLocalStorage-no-localStorage.test.js
  paywall/src/__tests__/hooks/browser/useLocalStorage.test.js
  paywall/src/__tests__/hooks/browser/usePostMessage.test.js
  paywall/src/hooks/browser/useListenForPostMessage.js
  paywall/src/hooks/browser/useLocalStorage.js
  paywall/src/hooks/browser/usePostMessage.js
  paywall/src/hooks/browser/useWindow.js
Labels: in progress

#1850 using a hardcoded address for the Unlock smart contract
  paywall/src/__tests__/services/walletService.test.js
  paywall/src/config.js
  paywall/src/services/walletService.js
  paywall/src/services/web3Service.js
  unlock-app/src/__tests__/services/walletService.test.js
  unlock-app/src/config.js
  unlock-app/src/services/walletService.js
  unlock-app/src/services/web3Service.js
Labels: in progress

#1860 merge validators from unlock-app to paywall
  paywall/src/__tests__/utils/validators.test.js
  paywall/src/utils/validators.js
Labels: in progress

#1861 Reset on deploy
  smart-contracts/package.json
Labels: in progress

#1863 Refusing to build the application when some env variables are missing
  unlock-app/next.config.js
Labels: in progress

#1864 passing env variables to the running docker container for tests
  scripts/tests.sh
Labels: in progress

#1866 the service name cannot use dash and needs an underscore
  scripts/tests.sh
Labels: in progress

#1849 Update NPM bignumber.js
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1848 Update NPM web3-eth-abi and web3-utils
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1858 fix incorrect context usage
  paywall/pages/_app.js
Labels: in progress

#1847 Update NPM truffle-hdwallet-provider
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1872 Adding a -o to next's package command
  unlock-app/.eslintignore
  unlock-app/.gitignore
  unlock-app/next.config.js
  unlock-app/package.json
  unlock-app/scripts/deploy-netlify.sh
Labels: in progress

#1867 Passing environment variables to the deploy scripts
  paywall/scripts/deploy-netlify.sh
  scripts/deploy.sh
  unlock-app/scripts/deploy-netlify.sh
Labels: in progress

#1869 Refactor paywall to use hooks
  paywall/src/__tests__/components/Paywall.test.js
  paywall/src/components/Paywall.js
  paywall/src/components/lock/Overlay.js
  paywall/src/services/iframeService.js
Labels: in progress

#1868 Add dependency for connected-next-router
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1865 Router is now connected to Redux
  unlock-app/src/__tests__/middlewares/web3Middleware.test.js
  unlock-app/src/createUnlockStore.js
  unlock-app/src/pages/_app.js
Labels: Transaction Log Page, p-1

#1891 explicitly passing the AUTH_TOKEN to netlify command
  paywall/scripts/deploy-netlify.sh
  unlock-app/scripts/deploy-netlify.sh
Labels: in progress

#1892 Remove connected-react-router dep
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1875 configuration setup for chromatic
  unlock-app/.storybook/config.js
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1881 Fix unlocked paywall flag story to display it as it actually looks
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/stories/Paywall.stories.js
Labels: in progress

#1871 Extracts Currency Lookup Service from Middleware
  unlock-app/src/__tests__/middlewares/currencyConversionMiddleware.test.js
  unlock-app/src/__tests__/services/currencyLookupService.test.js
  unlock-app/src/constants.js
  unlock-app/src/middlewares/currencyConversionMiddleware.js
  unlock-app/src/services/currencyLookupService.js
Labels: in progress

#1893 fixing unlimited key count
  paywall/src/__tests__/services/web3Service.test.js
  paywall/src/services/web3Service.js
  unlock-app/src/__tests__/middlewares/web3Middleware.test.js
  unlock-app/src/__tests__/services/web3Service.test.js
  unlock-app/src/middlewares/web3Middleware.js
  unlock-app/src/propTypes.js
  unlock-app/src/services/web3Service.js
Labels: in progress

#1896 Updating zos version in config files
  smart-contracts/zos.json
Labels: in progress

#1897 Applies engine version enforcement to dashboard & paywall
  .npmrc
  paywall/.npmrc
  unlock-app/.npmrc
Labels: in progress

#1894 adding a tasks to ci to deploy the paywall app
  .circleci/config.yml
  .travis.yml
  paywall/.gitignore
  paywall/next.config.js
  paywall/package.json
  paywall/src/pages/_app.js
  paywall/src/pages/_document.js
  paywall/src/pages/_error.js
  paywall/src/pages/index.js
  paywall/src/pages/paywall.js
Labels: in progress

#1857 add chromatic to config
  .circleci/config.yml
  scripts/storybook.sh
Labels: in progress

#1870 KEY_PURCHASE transactions now have the lock address
  unlock-app/src/__tests__/services/web3Service.test.js
  unlock-app/src/services/web3Service.js
Labels: in progress

#1921 Take space on the log page
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/pages/log.js
Labels: Transaction Log Page, design, frontend

#2001 Add home icon and svg
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/svg/Home.js
  unlock-app/src/components/interface/svg/index.js
  unlock-app/src/static/images/svg/home.svg
Labels: Transaction Log Page, frontend

#2013 Add buttons for log/dashboard navigation
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/buttons/PageNavButton.js
  unlock-app/src/components/interface/buttons/navigation/Dashboard.js
  unlock-app/src/components/interface/buttons/navigation/Log.js
  unlock-app/src/components/interface/buttons/navigation/index.js
  unlock-app/src/stories/interface/NavButtons.stories.js
Labels: Transaction Log Page, frontend

#2047 Connect header with router
  unlock-app/src/__tests__/components/interface/GlobalErrorConsumer.test.js
  unlock-app/src/__tests__/components/interface/Header.test.js
  unlock-app/src/__tests__/pages/pages.test.js
  unlock-app/src/components/interface/Header.js
  unlock-app/src/stories/creator/Dashboard.stories.js
  unlock-app/src/stories/creator/Log.stories.js
  unlock-app/src/stories/interface/Header.stories.js
  unlock-app/src/stories/interface/Layout.stories.js
Labels: Transaction Log Page

#2055 Header now affords navigation between dashboard and log
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/Header.js
  unlock-app/src/stories/creator/Log.stories.js
  unlock-app/src/stories/interface/Layout.stories.js
Labels: Transaction Log Page, frontend

#1989 Lock Form Button Design Fixes
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/creator/lock/EmbedCodeSnippet.js
  unlock-app/src/components/interface/buttons/Button.js
  unlock-app/src/components/interface/buttons/lock/Preview.js
Labels: design

#2098 Update tsconfig so Jest can read tsx files
  unlock-app/tsconfig.json
Labels: dev tools

#2109 Recategorize eslint deps so they can run in the CI env
  package-lock.json
  package.json
Labels: dev tools, testing

#2076 Locksmith now builds with TypeScript
  locksmith/.eslintignore
  locksmith/.gitignore
  locksmith/__tests__/app.test.js
  locksmith/jest.config.js
  locksmith/npm-shrinkwrap.json
  locksmith/package-lock.json
  locksmith/package.json
  locksmith/scripts/deploy-elasticbeanstalk.sh
  locksmith/tsconfig.json
Labels: Locksmith, dev tools

#2199 New pic of Ben on About page
  unlock-app/src/static/images/illustrations/ben.jpg
Labels: design

#2133 Restore behavior of unlocked flag
  paywall/src/__tests__/paywall-builder/iframe.test.js
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/lock/UnlockFlag.js
  paywall/src/hooks/browser/useLocalStorage.js
  paywall/src/hooks/browser/usePostMessage.js
  paywall/src/paywall-builder/iframe.js
Labels: BLOCKED

#2250 Make TransactionType values more human-friendly
  paywall/src/constants.js
  unlock-app/src/__tests__/components/content/LogContent.test.js
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/LogContent.js
  unlock-app/src/unlock.ts
Labels: Transaction Log Page
