Repository unlock-protocol/unlock, pull requests merged in 2019-11, with the labels that each got.

#5179 Adds locksmith as part of the development docker-compose setup
  docker/docker-compose.development.yml
Labels: cla-signed

#5184 not using the /event route anymore
  tickets/src/_server.js
Labels: cla-signed

#5186 Adds apollo-server & graphql dependencies
  locksmith/package-lock.json
  locksmith/package.json
Labels: cla-signed

#5185 removed stale components
  tickets/next.config.js
  tickets/src/__tests__/components/content/EventContent.test.js
  tickets/src/__tests__/components/content/EventVerify.test.js
  tickets/src/__tests__/components/content/ValidationIcon.test.js
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/_server.js
  tickets/src/components/content/EventContent.js
  tickets/src/components/content/EventVerify.js
  tickets/src/components/content/validate/ValidationIcon.js
  tickets/src/pages/checkin.js
  tickets/src/pages/event.js
  tickets/src/static/_redirects
  tickets/src/stories/content/EventContent.stories.js
  tickets/src/stories/content/EventVerify.stories.js
  tickets/src/stories/content/ValidationIcon.stories.js
Labels: cla-signed

#5187 removed unused middlewares from the store
  tickets/src/createUnlockStore.js
  tickets/src/pages/_app.js
Labels: cla-signed

#5188 changed stories for NewEventContent
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/content/NewEventContent.tsx
  tickets/src/stories/content/NewEventContent.stories.js
Labels: cla-signed

#5189 removed the rsvp route
  tickets/src/__tests__/utils/routes.test.js
  tickets/src/utils/routes.js
Labels: cla-signed

#5190 removed handling of ununsed actions in walletMiddleware
  tickets/src/__tests__/middlewares/walletMiddleware.test.js
  tickets/src/middlewares/walletMiddleware.js
Labels: cla-signed

#5191 removed the currencyConverter
  tickets/src/__tests__/actions/currencyConvert.test.js
  tickets/src/__tests__/middlewares/currencyConversionMiddleware.test.js
  tickets/src/__tests__/reducers/currencyReducer.test.js
  tickets/src/actions/currencyConvert.js
  tickets/src/middlewares/currencyConversionMiddleware.js
  tickets/src/reducers/currencyReducer.js
Labels: cla-signed

#5192 removed the unused code in PurchaseTicket
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/interface/PurchaseTicket.tsx
Labels: cla-signed

#5194 removed unused lock actions
  tickets/src/__tests__/actions/lock.test.js
  tickets/src/__tests__/reducers/locksReducer.test.js
  tickets/src/actions/lock.js
  tickets/src/reducers/locksReducer.js
Labels: cla-signed

#5193 removed unused actions in web3Middleware
  tickets/src/__tests__/middlewares/web3Middleware.test.js
  tickets/src/middlewares/web3Middleware.js
Labels: cla-signed

#5183 cleaned up tickets by removing all unused code from old ticket approach
  tickets/src/__tests__/actions/email.test.js
  tickets/src/__tests__/actions/key.test.js
  tickets/src/__tests__/actions/ticket.test.js
  tickets/src/__tests__/actions/transaction.test.js
  tickets/src/__tests__/components/content/PayButton.test.js
  tickets/src/__tests__/components/content/TicketCode.test.js
  tickets/src/__tests__/components/content/purchase/Ticket.test.js
  tickets/src/__tests__/components/helpers/BalanceProvider.test.js
  tickets/src/__tests__/components/interface/EventTicket.test.tsx
  tickets/src/__tests__/middlewares/wedlockMiddleware.test.js
  tickets/src/__tests__/reducers/keysReducer.test.js
  tickets/src/__tests__/reducers/ticketsReducer.test.js
  tickets/src/__tests__/reducers/transactionsReducer.test.js
  tickets/src/__tests__/selectors/keys.test.ts
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/actions/email.js
  tickets/src/actions/key.js
  tickets/src/actions/ticket.js
  tickets/src/actions/transaction.js
  tickets/src/components/content/purchase/PayButton.js
  tickets/src/components/content/purchase/Ticket.js
  tickets/src/components/content/purchase/TicketCode.js
  tickets/src/components/helpers/BalanceProvider.js
  tickets/src/components/interface/EventQRCode.tsx
  tickets/src/components/interface/EventTicket.tsx
  tickets/src/constants.ts
  tickets/src/errors.js
  tickets/src/middlewares/wedlockMiddleware.js
  tickets/src/reducers/keysReducer.js
  tickets/src/reducers/ticketsReducer.js
  tickets/src/reducers/transactionsReducer.js
  tickets/src/selectors/keys.ts
  tickets/src/stories/content/PayButton.stories.js
  tickets/src/stories/content/TicketCode.stories.js
  tickets/src/structured_data/unlockEventRSVP.js
Labels: cla-signed

#5197 let's wait for newly deployed locks to be confirming rather than submitted
  tests/test/dashboard.test.js
Labels: cla-signed

#5195 removed the qr code dependencies
  tickets/package-lock.json
  tickets/package.json
Labels: cla-signed

#5198 updated node engine
  locksmith/package.json
  package.json
  rover/package.json
  smart-contracts/package.json
  tests/package.json
  tickets/package.json
  unlock-app/package.json
  unlock-protocol.com/package.json
  wedlocks/package.json
Labels: cla-signed

#5046 Updated the design for the home page
  unlock-protocol.com/next.config.js
  unlock-protocol.com/src/__tests__/components/interface/HomepageButton.test.js
  unlock-protocol.com/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-protocol.com/src/components/content/HomeContent.js
  unlock-protocol.com/src/components/interface/ActionButton.js
  unlock-protocol.com/src/components/interface/Demo.js
  unlock-protocol.com/src/components/interface/Footer.js
  unlock-protocol.com/src/components/interface/Layout.js
  unlock-protocol.com/src/components/interface/buttons/homepage/HomepageButton.js
  unlock-protocol.com/src/components/interface/svg/Key.js
  unlock-protocol.com/src/components/interface/svg/index.js
  unlock-protocol.com/src/static/images/pages/svg/code-hover.svg
  unlock-protocol.com/src/static/images/pages/svg/code.svg
  unlock-protocol.com/src/static/images/pages/svg/control.svg
  unlock-protocol.com/src/static/images/pages/svg/donations.svg
  unlock-protocol.com/src/static/images/pages/svg/hero.svg
  unlock-protocol.com/src/static/images/pages/svg/more-hover.svg
  unlock-protocol.com/src/static/images/pages/svg/more.svg
  unlock-protocol.com/src/static/images/pages/svg/paywall.svg
  unlock-protocol.com/src/static/images/pages/svg/simple-hover.svg
  unlock-protocol.com/src/static/images/pages/svg/simple.svg
  unlock-protocol.com/src/static/images/pages/svg/tickets.svg
  unlock-protocol.com/src/static/images/pages/svg/wordpress.svg
  unlock-protocol.com/src/static/images/svg/key.svg
  unlock-protocol.com/src/stories/content/HomeContent.stories.js
  unlock-protocol.com/src/stories/interface/HomepageButton.stories.js
Labels: cla-signed

#5205 DeveloperOverlay is gone
  unlock-app/src/__tests__/components/developer/DeveloperOverlay.test.js
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/DashboardContent.js
  unlock-app/src/components/content/KeyChainContent.tsx
  unlock-app/src/components/developer/DeveloperOverlay.js
  unlock-app/src/stories/developer/DeveloperOverlay.stories.js
Labels: cla-signed

#5208 Deploy the unlock-subgraph locally as part of the development container stand up
  docker/development/deploy-subgraph.js
  docker/development/subgraph.dockerfile
  docker/docker-compose.development.yml
Labels: cla-signed

#5210 Adding dependencies in support of the aggregation GraphQL service
  locksmith/package-lock.json
  locksmith/package.json
Labels: cla-signed

#5211 A starting point for the aggregating GraphQL service
  locksmith/config/config.js
  locksmith/src/apollo-datasource-graphql.d.ts
  locksmith/src/app.ts
  locksmith/src/graphql/datasource/index.ts
  locksmith/src/graphql/datasource/keyPurchase.ts
  locksmith/src/graphql/datasource/lock.ts
  locksmith/src/graphql/datasource/unlockGraphQLDataSource.ts
  locksmith/src/graphql/resolvers.ts
  locksmith/src/graphql/typeDefinitions.ts
Labels: cla-signed

#5214 Hackathon Blog Post
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/hackathon-ideas.md
  unlock-protocol.com/src/static/blog.rss
  unlock-protocol.com/src/static/images/blog/hackathon-ideas/hero.jpg
Labels: cla-signed

#5212 Add query to get all keys for a given lock
  unlock-app/src/queries/keyholdersByLock.js
Labels: cla-signed

#5206 Bringing a bit more consistency
  scripts/nuke.sh
  unlock-app/src/__tests__/components/interface/VerificationStatus.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/Key.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/KeyDetails.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/QRModal.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/_server.js
  unlock-app/src/components/content/KeychainContent.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/buttons/navigation/Keychain.js
  unlock-app/src/components/interface/buttons/navigation/index.js
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/KeyDetails.tsx
  unlock-app/src/components/interface/keychain/KeychainTypes.ts
  unlock-app/src/components/interface/keychain/QRModal.tsx
  unlock-app/src/pages/keyChain.js
  unlock-app/src/pages/keychain.js
  unlock-app/src/stories/interface/InlineModal.stories.js
  unlock-app/src/stories/keychain/keychain.stories.js
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#5217 Adding links to settings when applicable
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/Header.js
Labels: cla-signed

#5218 Adding documentation around the development docker configuration
  docker/README.md
Labels: cla-signed

#5215 Adding timeMachine function
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/contracts/mocks/TimeMachineMock.sol
  smart-contracts/test/Lock/timeMachine.js
Labels: cla-signed

#5221 Remove transfer fee
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed

#5219 Add a page where lock creators can view keyholder metadata
  unlock-app/src/__tests__/components/interface/MetadataTable.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/pages/members.js
  unlock-app/src/stories/interface/MetadataTable.stories.js
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#5224 Add actions and typed data for metadata request signature
  unlock-app/src/__tests__/actions/keyMetadata.test.ts
  unlock-app/src/actions/keyMetadata.ts
  unlock-app/src/structured_data/keyMetadataTypedData.ts
Labels: cla-signed

#5222 Updates Locksmith's readme to reflect its current responsibilities
  locksmith/README.md
Labels: cla-signed

#5220 adding post about user ejection
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/ejecting-account.md
  unlock-protocol.com/src/static/blog.rss
  unlock-protocol.com/src/static/images/blog/ejecting-account/ejecting.jpg
  unlock-protocol.com/src/static/images/blog/ejecting-account/import.jpg
Labels: cla-signed

#5226 WalletMiddleware responds to request for metadata signature
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/middlewares/walletMiddleware.js
Labels: cla-signed

#5228 adding POAP POST
  unlock-app/src/__tests__/components/interface/RefundButton.test.tsx
  unlock-app/src/components/interface/RefundButton.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
Labels: cla-signed

#5227 fixing size of the modal on the paywall
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/checkout/Checkout.tsx
  paywall/src/components/checkout/CheckoutConfirmingModal.tsx
  paywall/src/components/checkout/CheckoutWrapper.tsx
  paywall/src/components/lock/LockStyles.js
Labels: cla-signed

#4806 Codechecks config for gas reports
  docker/smart-contracts.dockerfile
  scripts/tests.sh
  smart-contracts/codechecks.yml
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: cla-signed, smart contract

#5231 Revert "Codechecks config for gas reports"
  docker/smart-contracts.dockerfile
  scripts/tests.sh
  smart-contracts/codechecks.yml
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: cla-signed

#5234 updated unlock-js to fix minor bug which prevented user ejection
  unlock-js/CHANGELOG.md
  unlock-js/package.json
  unlock-js/src/unlockProvider.js
Labels: cla-signed

#5229 Improved the "No wallet" experience
  paywall/src/__tests__/data-iframe/Mailbox/getBlockchainDataFromLocalStorageCache.test.ts
  paywall/src/__tests__/data-iframe/Mailbox/getCacheKey.test.ts
  paywall/src/__tests__/data-iframe/Mailbox/invalidateLocalStorageCache.test.ts
  paywall/src/__tests__/data-iframe/Mailbox/saveCacheInLocalStorage.test.ts
  paywall/src/__tests__/data-iframe/blockchainHandler/BlockchainHandler/BlockchainHandler.test.ts
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/__tests__/test-helpers/setupBlockchainHelpers.ts
  paywall/src/__tests__/test-helpers/setupMailboxHelpers.ts
  paywall/src/__tests__/unlock.js/CheckoutUIHandler.test.ts
  paywall/src/__tests__/unlock.js/IframeHandler.test.ts
  paywall/src/__tests__/unlock.js/MainWindowHandler/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/enableCryptoWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccounts.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
  paywall/src/__tests__/unlock.js/startup.test.ts
  paywall/src/components/checkout/NoWallet.tsx
  paywall/src/components/content/NewDemoContent.tsx
  paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts
  paywall/src/hooks/usePaywallConfig.js
  paywall/src/unlockTypes.ts
  paywall/src/utils/validators.js
  tests/test/paywall-without-crypto-wallet.test.js
Labels: cla-signed

#5223 Update metadata upload scripts for user uploads
  locksmith/scripts/metadataUpload/readme.md
  locksmith/scripts/metadataUpload/sample_data/userMetadata.json
  locksmith/scripts/metadataUpload/user_metadata_upload.ts
Labels: cla-signed

#5236 fixing the svg size as Chrome renders them slightly differently if we do not force it
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/checkout/NoWallet.tsx
Labels: cla-signed

#5233 Updating getTransferFee function
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed

#5242 Implementing fee in time
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed

#5237 Updated unlock-js in unlock-app
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5238 adding actions for user ejection
  unlock-app/src/__tests__/actions/user.test.ts
  unlock-app/src/actions/user.ts
Labels: cla-signed

#5241 adding ejectUser to storageService
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/services/storageService.js
Labels: cla-signed

#5243 Update keyholdersByLock to include lock address in response
  unlock-app/src/queries/keyholdersByLock.js
Labels: cla-signed

#5244 Improve metadata actions
  unlock-app/src/__tests__/actions/keyMetadata.test.ts
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/actions/keyMetadata.ts
  unlock-app/src/middlewares/walletMiddleware.js
Labels: cla-signed

#5245 Store key metadata in Redux
  unlock-app/src/__tests__/reducers/metadataReducer.test.ts
  unlock-app/src/createUnlockStore.js
  unlock-app/src/reducers/metadataReducer.ts
Labels: cla-signed

#5246 Reverting 2 commits in smart contarcts
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed

#5247 Updates signature validation middleware to handle payloads for get request
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/__tests__/signatureValidation/signPersonal.test.ts
  locksmith/__tests__/signatureValidation/typedData.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/middlewares/signatureValidationMiddleware.ts
Labels: cla-signed

#5232 Start requesting metadata from locksmith
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/middlewares/walletMiddleware.js
  unlock-app/src/services/storageService.js
Labels: cla-signed

#5250 Augment metadata table with additional fields from locksmith
  unlock-app/src/__tests__/utils/metadataMunging.test.ts
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/unlockTypes.ts
  unlock-app/src/utils/metadataMunging.ts
Labels: cla-signed

#5251 Production manual Deploy production-20191107-192655
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/__tests__/signatureValidation/signPersonal.test.ts
  locksmith/__tests__/signatureValidation/typedData.test.ts
  locksmith/scripts/metadataUpload/readme.md
  locksmith/scripts/metadataUpload/sample_data/userMetadata.json
  locksmith/scripts/metadataUpload/user_metadata_upload.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/middlewares/signatureValidationMiddleware.ts
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/checkout/NoWallet.tsx
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-app/src/__tests__/actions/keyMetadata.test.ts
  unlock-app/src/__tests__/actions/user.test.ts
  unlock-app/src/__tests__/middlewares/providerMiddleware.test.ts
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/reducers/metadataReducer.test.ts
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/__tests__/utils/metadataMunging.test.ts
  unlock-app/src/actions/keyMetadata.ts
  unlock-app/src/actions/user.ts
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/createUnlockStore.js
  unlock-app/src/middlewares/providerMiddleware.ts
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/middlewares/walletMiddleware.js
  unlock-app/src/queries/keyholdersByLock.js
  unlock-app/src/reducers/metadataReducer.ts
  unlock-app/src/services/storageService.js
  unlock-app/src/unlockTypes.ts
  unlock-app/src/utils/metadataMunging.ts
Labels: cla-signed

#5255 minor readme text updates on env variables
  README.md
Labels: cla-signed

#5257 lock expiration time style change
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/lock/ConfirmedKeyLock.js
  paywall/src/components/lock/LockStyles.js
  paywall/src/components/lock/NoKeyLock.js
  paywall/src/theme/globalStyle.js
Labels: cla-signed, design

#5262 Renovate: split by repo
  renovate.json
Labels: cla-signed

#5263 added members to readme
  README.md
Labels: cla-signed

#5256 removed lock lookup from locksmith
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/services/storageService.js
Labels: cla-signed

#5264 When signing metadata requests, show wallet check overlay
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/middlewares/walletMiddleware.js
Labels: cla-signed

#5266 Show lock name on verification page, remove temporary refund button
  unlock-app/src/__tests__/components/interface/VerificationStatus.test.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
Labels: cla-signed

#5253 Exposes endpoint for batch User Metadata
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/graphql/datasource/keyholdersByLock.ts
  locksmith/src/operations/lockOperations.js
  locksmith/src/operations/lockOperations.ts
  locksmith/src/routes/metadata.ts
  locksmith/src/utils/signature.ts
Labels: cla-signed

#5267 Renovate: fix dupe groupName & add default minor groupName
  renovate.json
Labels: cla-signed

#5269 Remove unnecessary generics in tests
  paywall/src/__tests__/test-helpers/fakeWindowHelpers.ts
  unlock-app/src/__tests__/services/postOfficeService.test.ts
Labels: cla-signed

#5270 adding post about member's wall
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/member-wall.md
  unlock-protocol.com/src/static/blog.rss
Labels: cla-signed

#5272 setting a global base token URI
  docker/development/deploy-unlock.js
Labels: cla-signed

#5277 Remove unneeded modal infrastructure
  unlock-app/src/__tests__/actions/fullScreenModals.test.ts
  unlock-app/src/__tests__/components/interface/ModalTemplates.test.tsx
  unlock-app/src/__tests__/reducers/fullScreenModalsReducer.test.ts
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/actions/fullScreenModals.ts
  unlock-app/src/components/interface/FullScreenModals.tsx
  unlock-app/src/components/interface/modal-templates/QRDisplay.tsx
  unlock-app/src/components/interface/modal-templates/index.ts
  unlock-app/src/components/interface/modal-templates/styles.ts
  unlock-app/src/reducers/fullScreenModalsReducer.ts
  unlock-app/src/stories/interface/FullScreenModals.stories.js
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#5279 Updating batch data request to accept signature via query parameter
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/routes/metadata.ts
Labels: cla-signed

#5249 WIP: Fixing transferFee tests
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed

#5281 Transfer fee test update
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed, smart contract

#5282 Fix transferFee test
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed, smart contract

#5274 Add storageService method to access batch metadata endpoint
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/services/storageService.js
Labels: cla-signed

#5283 transferFee test fix
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed, smart contract

#5278 removed the refund contract for ethwaterloo
  docker/development/ExternalRefund.json
  docker/development/deploy-external-refund.js
  docker/development/deploy-unlock.js
  docker/development/ganache.dockerfile
Labels: cla-signed

#5275 Scrub external refund from unlock-app
  unlock-app/next.config.js
  unlock-app/src/__tests__/components/interface/RefundButton.test.tsx
  unlock-app/src/components/interface/RefundButton.tsx
  unlock-app/src/config.js
Labels: cla-signed

#5287 adding support for createdAfter when retriving transactions
  locksmith/__tests__/operations/transactionOperations.test.js
  locksmith/src/controllers/transactionController.js
  locksmith/src/operations/transactionOperations.ts
Labels: cla-signed

#5288 Update keyHoldersByLock query and associated functions
  locksmith/src/graphql/datasource/keyholdersByLock.ts
Labels: cla-signed

#5289 Restructuring metadata test for maintainability
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/__tests__/controllers/metadataController/requestingKeyholderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/requestingTokenMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/tokenData.test.ts
  locksmith/__tests__/controllers/metadataController/updateAddressHolderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/updateDefaults.test.ts
  locksmith/__tests__/controllers/metadataController/updateKeyMetadata.test.ts
Labels: cla-signed

#5292 Removing older deployment script
  locksmith/scripts/deploy-elasticbeanstalk.sh
Labels: cla-signed

#5293 Use bulk metadata endpoint on members page
  unlock-app/src/__tests__/actions/keyMetadata.test.ts
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/reducers/metadataReducer.test.ts
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/__tests__/utils/metadataMunging.test.ts
  unlock-app/src/actions/keyMetadata.ts
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/middlewares/walletMiddleware.js
  unlock-app/src/reducers/metadataReducer.ts
  unlock-app/src/services/storageService.js
  unlock-app/src/unlockTypes.ts
  unlock-app/src/utils/metadataMunging.ts
Labels: cla-signed

#5294 refactored the lock action/reducer by removing ADD_LOCK
  unlock-app/src/__tests__/actions/lock.test.js
  unlock-app/src/__tests__/middlewares/web3Middleware.test.js
  unlock-app/src/__tests__/reducers/locksReducer.test.js
  unlock-app/src/actions/lock.js
  unlock-app/src/middlewares/web3Middleware.js
  unlock-app/src/reducers/locksReducer.js
Labels: cla-signed

#5297 Adding a service for graph queries happening through redux
  unlock-app/src/__tests__/services/graphService.test.js
  unlock-app/src/services/graphService.ts
Labels: cla-signed

#5296 changed getTransactionsHashesSentBy into getRecentTransactionsHashesSentBy
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/services/storageService.js
Labels: cla-signed

#5300 Update Locksmith with respective GraphQL Service URI for environment
  .circleci/config.yml
  docker/docker-compose.development.yml
  locksmith/config/config.js
  locksmith/scripts/deploy-elasticbeanstalk-docker.sh
Labels: cla-signed

#5291 Adds blog post regarding documentation
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/user-facing-documentation.md
  unlock-protocol.com/src/static/blog.rss
  unlock-protocol.com/src/static/images/blog/user-facing-documentation/documentation.jpg
Labels: cla-signed

#5302 Extract postmessage listening into one hub
  paywall/src/unlock.js/CheckoutUIHandler.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5301 adding the graph to our ci docker setup
  docker/docker-compose.ci.yml
  scripts/integration-tests.sh
Labels: cla-signed

#5290 Implementing shareKey (partial transfers)
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/shareKey.js
Labels: cla-signed

#5303 Implementing disabling transfers
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/disableTransfers.js
Labels: cla-signed

#5304 fixing blog typos
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/tokenizing-memberships.md
  unlock-protocol.com/blog/user-facing-documentation.md
  unlock-protocol.com/src/static/blog.rss
Labels: cla-signed

#5314 subgraphURI is set from the SUBGRAPH_URI environment variable
  docker/docker-compose.ci.yml
  scripts/set-integration-tests-env-variables.sh
  unlock-app/next.config.js
  unlock-app/src/config.js
Labels: cla-signed

#5312 updated published npm module for version 1.2
  smart-contracts/published-npm-modules/V1.2/PublicLock.json
  smart-contracts/published-npm-modules/V1.2/README.md
  smart-contracts/published-npm-modules/V1.2/Unlock.json
  smart-contracts/published-npm-modules/V1.2/package.json
Labels: cla-signed

#5313 iframeHandler and mainWindowHandler outsource their postmessaging
  paywall/src/__tests__/unlock.js/CheckoutUIHandler.test.ts
  paywall/src/__tests__/unlock.js/MainWindowHandler/init.test.ts
  paywall/src/__tests__/unlock.js/MainWindowHandler/lockStates.test.ts
  paywall/src/messageTypes.ts
  paywall/src/unlock.js/IframeHandler.ts
  paywall/src/unlock.js/MainWindowHandler.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5316 Allow key owners to view private metadata associated with their keys
  locksmith/__tests__/controllers/metadataController/requestingTokenMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/tokenData.test.ts
  locksmith/__tests__/test-helpers/typeDataGenerators.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/utils/lockData.ts
Labels: cla-signed

#5320 Updates test to use typed data generator helpers
  locksmith/__tests__/controllers/metadataController/requestingTokenMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/updateAddressHolderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/updateKeyMetadata.test.ts
  locksmith/__tests__/test-helpers/typeDataGenerators.ts
Labels: cla-signed

#5322 adding abi for version 1.2
  unlock-js/package-lock.json
  unlock-js/package.json
  unlock-js/scripts/compressAbi.js
  unlock-js/src/__tests__/helpers/bytecode.js
  unlock-js/src/__tests__/helpers/fixtures/locks.js
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/abis.js
  unlock-js/src/bytecode.js
Labels: cla-signed

#5325 Pull enableCryptoWallet into postMessageHub
  paywall/src/__tests__/unlock.js/Wallet/enableCryptoWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5323 removed connected-react-router
  tickets/package-lock.json
  tickets/package.json
  tickets/src/__tests__/components/content/NewEventContent.test.ts
  tickets/src/components/content/NewEventContent.tsx
  tickets/src/createUnlockStore.js
  tickets/src/middlewares/eventMiddleware.js
  tickets/src/middlewares/web3Middleware.js
  tickets/src/pages/_app.js
Labels: cla-signed

#5326 Begins updating Locksmith with more idiomatic TS
  locksmith/src/controllers/metadataController.ts
  locksmith/src/operations/metadataOperations.ts
  locksmith/src/operations/userMetadataOperations.ts
  locksmith/src/routes/metadata.ts
  locksmith/src/types.ts
Labels: cla-signed

#5327 showing the lock icon (NFT) on the keychain keys
  unlock-app/src/__tests__/components/interface/VerificationStatus.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/Key.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/KeyDetails.test.tsx
  unlock-app/src/__tests__/hooks/useMetadata.test.js
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/KeychainTypes.ts
  unlock-app/src/hooks/useMetadata.js
  unlock-app/src/queries/keyHolder.js
  unlock-app/src/stories/keychain/keychain.stories.js
Labels: cla-signed

#5328 Move setupUserAccounts to postMessageHub
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccounts.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5319 Refactor MixinSignatures
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinSignatures.sol
  smart-contracts/test/Lock/cancelAndRefundFor.js
  smart-contracts/test/Lock/invalidateOffchainApproval.js
Labels: cla-signed, smart contract

#5332 move setupuseraccountproxywallet to postmessagehub
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5330 adding color-scheme for lock icon generation
  locksmith/package-lock.json
  locksmith/package.json
Labels: cla-signed

#5329 adding method to return svg icon
  locksmith/__tests__/utils/lockIcon.test.ts
  locksmith/package-lock.json
  locksmith/src/color-scheme.d.ts
  locksmith/src/controllers/lockController.js
  locksmith/src/routes/lock.ts
  locksmith/src/utils/lockIcon.ts
Labels: cla-signed

#5321 adding method to deploy template lock contract
  unlock-js/CHANGELOG.md
  unlock-js/scripts/compressAbi.js
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/bytecode.js
  unlock-js/src/unlockService.js
  unlock-js/src/v12/index.js
  unlock-js/src/walletService.js
Labels: cla-signed

#5336 using the lock icon as default for the NFT icon
  locksmith/src/controllers/metadataController.ts
  locksmith/src/operations/metadataOperations.ts
Labels: cla-signed

#5339 Move setupWeb3ProxyWallet to postMessageHub
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5340 forcing the image version for graphprotocol/graph-node
  docker/docker-compose.ci.yml
  docker/docker-compose.development.yml
Labels: cla-signed

#5344 Data iframe handles postMessages more fluidly
  paywall/src/__tests__/unlock.js/IframeHandler.test.ts
  paywall/src/__tests__/unlock.js/PostMessageEmitters/DataIframeMessageEmitter.test.ts
  paywall/src/__tests__/unlock.js/startup.test.ts
  paywall/src/unlock.js/PostMessageEmitters/DataIframeMessageEmitter.ts
  paywall/src/unlock.js/postMessageHub.ts
  paywall/src/utils/postOffice.ts
Labels: cla-signed

#5346 updated graph service and query when retrieving user locks
  unlock-app/src/__tests__/services/graphService.test.js
  unlock-app/src/queries/locksByOwner.js
  unlock-app/src/services/graphService.ts
Labels: cla-signed

#5338 adding the configureUnlock method
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/deploy.js
  unlock-js/src/walletService.js
Labels: cla-signed

#5345 Updated CI to use the right configuration for the graph
  docker/docker-compose.ci.yml
  scripts/set-integration-tests-env-variables.sh
  tests/helpers/environment.js
  tests/helpers/vars.js
Labels: cla-signed

#5348 Updates the version of graph-node available in the local docker image to v0.16.1
  docker/docker-compose.development.yml
Labels: cla-signed

#5349 not throwing when metadata cannot be retrieved
  unlock-app/src/__tests__/hooks/useMetadata.test.js
  unlock-app/src/hooks/useMetadata.js
Labels: cla-signed

#5299 Retrieving the list of locks for a given user from the graph
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/__tests__/middlewares/web3Middleware.test.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/middlewares/web3Middleware.js
Labels: cla-signed

#5357 adding a check on the lock being loaded to remove a race condition in integration tests
  tests/test/dashboard.test.js
Labels: cla-signed

#5355 copied over v11 files for v12
  unlock-js/src/__tests__/v12/createLock.test.js
  unlock-js/src/__tests__/v12/getLock.test.js
  unlock-js/src/__tests__/v12/purchaseKey.test.js
  unlock-js/src/__tests__/v12/updateKeyPrice.test.js
  unlock-js/src/__tests__/v12/web3Service.test.js
  unlock-js/src/__tests__/v12/withdrawFromLock.test.js
  unlock-js/src/v12/createLock.js
  unlock-js/src/v12/getLock.js
  unlock-js/src/v12/purchaseKey.js
  unlock-js/src/v12/updateKeyPrice.js
  unlock-js/src/v12/withdrawFromLock.js
Labels: cla-signed

#5363 Consolidate postMessages that should always be listened to
  paywall/src/__tests__/unlock.js/postmessageHub.test.ts
  paywall/src/__tests__/utils/injectDefaultBalance.test.ts
  paywall/src/unlock.js/postMessageHub.ts
  paywall/src/utils/injectDefaultBalance.ts
Labels: cla-signed

#5364 Extract wallet utils to utils
  paywall/src/__tests__/utils/wallet.test.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/utils/wallet.ts
Labels: cla-signed

#5365 Split consolidated postMessages by source iframe
  paywall/src/__tests__/unlock.js/postmessageHub.test.ts
  paywall/src/unlock.js/postMessageHub.ts
Labels: cla-signed

#5366 Key queries updated to return associated metadata
  locksmith/jest.config.js
  locksmith/src/graphql/datasource/index.ts
  locksmith/src/graphql/datasource/key.ts
  locksmith/src/graphql/datasource/keyPurchase.ts
  locksmith/src/graphql/datasource/metaData.ts
  locksmith/src/graphql/resolvers.ts
  locksmith/src/graphql/typeDefinitions.ts
Labels: cla-signed

#5368 Extracts resolver to conditionally load metadata for single requests
  locksmith/src/graphql/resolvers.ts
Labels: cla-signed

#5374 Adds migration for user metadata lookup
  locksmith/migrations/20191125163907-token_metadata_indicies.js
Labels: cla-signed

#5367 Calculate wallet status at startup
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/unlock.js/postMessageHub.ts
  paywall/src/unlock.js/startup.ts
  paywall/src/utils/wallet.ts
Labels: cla-signed

#5379 Downgrade Truffle and unlock-abi-1-2 [fix master]
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: cla-signed, smart contract

#5382 Safe transfers
  smart-contracts/contracts/mixins/MixinFunds.sol
Labels: cla-signed, smart contract

#5380 Pass the correct flag to checkoutHandlerInit [fixes master regression]
  paywall/src/unlock.js/CheckoutUIHandler.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/unlock.js/postMessageHub.ts
  paywall/src/unlock.js/startup.ts
Labels: cla-signed
