Repository unlock-protocol/unlock, pull requests merged in 2019-02, with the labels that each got.

#1417 make sure this story never kills our tests again, or at least not until the year 3000 :)
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/stories/creator/KeyList.stories.js
Labels: dev tools

#1464 Adds indexes for Lock storage/retrieval
  locksmith/__tests__/app.test.js
  locksmith/migrations/20190207160225-lock_indices.js
Labels: Locksmith

#1480 Add wallet check overlay
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/FullScreenModals.js
  unlock-app/src/pages/_app.js
  unlock-app/src/stories/creator/Dashboard.stories.js
  unlock-app/src/stories/interface/WalletCheckOverlay.stories.js
Labels: frontend, p-2

#1503 fix random ordering of deps
  package.json
Labels: dev tools

#1525 add paywall directory to pre commit and pre push hooks
  .huskyrc.js
Labels: Splitting Unlock-app, dev tools

#1543 Remove flash of MAX_UINT from unlimited key locks
  unlock-app/src/__tests__/components/creator/CreatorLock.test.js
  unlock-app/src/__tests__/components/creator/CreatorLockForm.test.js
  unlock-app/src/__tests__/services/web3Service.test.js
  unlock-app/src/components/creator/CreatorLock.js
  unlock-app/src/components/creator/CreatorLockForm.js
  unlock-app/src/services/web3Service.js
Labels: frontend

#1567 Enables Locksmith in Production
  unlock-app/src/config.js
Labels: in progress

#1576 Revert "Update next in group default to the latest version (#1520)"
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1578 not requiring the artifacts files to exist
  paywall/src/__tests__/hooks/useLock.test.js
  paywall/src/__tests__/hooks/useUnlockContract.test.js
  paywall/src/__tests__/services/walletService.test.js
  paywall/src/__tests__/services/web3Service.test.js
  paywall/src/hooks/useLock.js
  paywall/src/hooks/useUnlockContract.js
  paywall/src/services/walletService.js
  paywall/src/services/web3Service.js
  unlock-app/src/__tests__/services/walletService.test.js
  unlock-app/src/__tests__/services/web3Service.test.js
  unlock-app/src/services/walletService.js
  unlock-app/src/services/web3Service.js
Labels: in progress

#1575 sync services with unlock-app
  paywall/src/__tests__/services/walletService.test.js
  paywall/src/__tests__/services/web3Service.test.js
  paywall/src/services/walletService.js
  paywall/src/services/web3Service.js
Labels: in progress

#1592 using alpine for a smaller based node image
  docker/unlock.dockerfile
Labels: in progress

#1591 Re-ordering docker image to install dependncies less often
  docker/unlock.dockerfile
Labels: in progress

#1595 Clarification to run integration tests locally
  tests/README.md
Labels: in progress

#1552 Solidity coverage
  smart-contracts/.gitignore
  smart-contracts/package.json
  smart-contracts/test/Lock/destroyLock.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/getApproved.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/owners.js
Labels: in progress

#1555 Contract error codes
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/UnlockErrors.sol
  smart-contracts/contracts/UnlockTestV2.sol
  smart-contracts/contracts/UnlockTestV3.sol
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/erc721/getApproved.js
  smart-contracts/test/Lock/erc721/getTokenIdFor.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/expireKeyFor.js
  smart-contracts/test/Lock/getOwnersByPage.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/partialWithdraw.js
  smart-contracts/test/Lock/purchaseFor.js
  smart-contracts/test/Lock/purchaseForFrom.js
  smart-contracts/test/Unlock/behaviors/createLock.js
Labels: in progress

#1590 Removed some of the linting warnings
  paywall/src/__tests__/services/storageService.test.js
  paywall/src/services/storageService.js
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/services/storageService.js
Labels: in progress

#1600 Adding solium
  smart-contracts/.soliumignore
  smart-contracts/.soliumrc.json
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1598 Adds integration test for lock creation & embed existence
  tests/test/dashboard.test.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/services/storageService.js
Labels: in progress

#1611 Upgrades platform to web3 beta37
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-app/src/__tests__/services/web3Service.test.js
Labels: in progress

#1599 When we set the account, also get all the transactions for the locks...
  unlock-app/src/__tests__/middlewares/web3Middleware.test.js
  unlock-app/src/middlewares/web3Middleware.js
Labels: Transaction Log Page, in progress

#1613 Revert "Upgrades platform to web3 beta37 (#1611)"
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-app/src/__tests__/services/web3Service.test.js
Labels: in progress

#1601 Fixing issues reported by Solium
  smart-contracts/contracts/PublicLock.sol
Labels: in progress

#1603 Add web3-eth-abi for contract tests
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1609 Downgrade lint errors regarding quotes / migrate to single quote
  smart-contracts/.soliumrc.json
Labels: in progress

#1607 Add openzeppelin-solidity package
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1605 Standard IERC721Receiver
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/interfaces/IERC721Receiver.sol
Labels: in progress

#1610 Switch from double to single quotes
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/UnlockErrors.sol
  smart-contracts/contracts/UnlockTestV2.sol
  smart-contracts/contracts/UnlockTestV3.sol
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
Labels: in progress

#1616 Re-enable smart contract lint errors
  smart-contracts/.solhint.json
  smart-contracts/.soliumrc.json
Labels: in progress

#1553 Fix eslint contract errors
  smart-contracts/migrations/3_create_proxy.js
  smart-contracts/published-npm-modules/V0/index.js
  smart-contracts/test/Lock/erc721/Non_Public_approve.js
  smart-contracts/test/Lock/erc721/Non_Public_getApproved.js
  smart-contracts/test/Lock/erc721/Non_Public_transferFrom.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/getApproved.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/updateKeyPrice.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/Unlock/behaviors/computeAvailableDiscountFor.js
  smart-contracts/test/Unlock/behaviors/recordConsumedDiscount.js
  smart-contracts/test/Unlock/behaviors/recordKeyPurchase.js
Labels: in progress

#1608 Enable eslint on smart contracts
  smart-contracts/package.json
Labels: in progress

#1619 fix potential endless loop (temp fix until Akeem can clean it up)
  unlock-app/src/middlewares/storageMiddleware.js
Labels: in progress

#1620 enable "Trace" tab in redux devtools
  paywall/src/createUnlockStore.js
  unlock-app/src/createUnlockStore.js
Labels: in progress

#1621 remove that pesky dirty node_modules in wiki when running npm ci
  scripts/postinstall.sh
Labels: in progress

#1624 refactored pollForAccountChanges
  unlock-app/src/__tests__/services/walletService.test.js
  unlock-app/src/services/walletService.js
Labels: in progress

#1623 Updates failure scenarios for Storage service and associated tests
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/services/storageService.js
Labels: in progress

#1625 Add builders for chain explorer URLs to config
  unlock-app/src/__tests__/config.test.js
  unlock-app/src/config.js
Labels: in progress

#1626 Revert "Revert "Upgrades platform to web3 beta37 (#1611)" (#1613)"
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-app/src/__tests__/services/web3Service.test.js
Labels: in progress

#1627 account polling is happening at the middleware level, not inside the service
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/services/walletService.test.js
  unlock-app/src/middlewares/walletMiddleware.js
  unlock-app/src/services/walletService.js
Labels: in progress

#1628 only running eslint on the files in the last commit
  .huskyrc.js
Labels: in progress

#1631 Refactor mixin for disable and destroy related functions
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinDisableAndDestroy.sol
Labels: in progress

#1618 Switch to openzeppelin-solidity (from -eth) for the lock
  smart-contracts/contracts/PublicLock.sol
Labels: in progress

#1630 Refactor mixin for key owner related functions
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/UnlockErrors.sol
  smart-contracts/contracts/mixins/MixinKeyOwner.sol
Labels: in progress

#1633 Refactor mixin for approval related functions
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinApproval.sol
Labels: in progress

#1604 No fallback function
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/UnlockErrors.sol
  smart-contracts/test/Lock/noFallback.js
  smart-contracts/test/Unlock/noFallback.js
Labels: in progress

#1635 Refactor mixin for Keys
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
Labels: in progress

#1632 add missing test dep for paywall
  paywall/package-lock.json
  paywall/package.json
Labels: Splitting Unlock-app, in progress

#1640 Fix lint errors in `noFallback`
  smart-contracts/test/Lock/noFallback.js
  smart-contracts/test/Unlock/noFallback.js
Labels: in progress

#1639 Updates web3service tests to leverage async/await paradigm
  unlock-app/src/__tests__/services/web3Service.test.js
Labels: in progress

#1648 avoid outdated package
  unlock-app/src/__tests__/middlewares/web3Middleware.test.js
Labels: in progress

#1647 update next to version 8.0.2 in paywall
  paywall/package-lock.json
  paywall/package.json
Labels: Splitting Unlock-app, in progress

#1638 Copying the .git folder into docker image to use git commit info in pipelines
  docker/unlock.dockerfile
Labels: in progress

#1634 Removes our test chain id from our Typed Data
  unlock-app/src/__tests__/utils/signature.test.js
  unlock-app/src/structured_data/unlockLock.js
Labels: in progress

#1614 Updates deployment initiator
  .travis.yml
  scripts/deploy-elasticbeanstalk.sh
Labels: in progress

#1645 Fix pre-push for edge cases
  .huskyrc.js
  locksmith/.eslintignore
Labels: dev tools, in progress

#1658 Updates registerServiceWorker to async/await paradigm
  unlock-app/src/registerServiceWorker.js
Labels: in progress

#1657 Updated the build scripts
  .travis.yml
  scripts/build-image.sh
  scripts/pull-image.sh
  scripts/push-image.sh
Labels: in progress

#1596 Add transaction log page
  unlock-app/src/__tests__/pages/log.test.js
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/pages/log.js
  unlock-app/src/stories/creator/Log.stories.js
Labels: in progress

#1661 add new paywallUrl configuration variable
  unlock-app/next.config.js
  unlock-app/src/config.js
Labels: Splitting Unlock-app, in progress

#1659 making the script which deploys to netlify independent of the platform
  scripts/deploy-netlify.sh
  scripts/deploy.sh
Labels: in progress

#1663 fix master, and make next 8 actually work
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1664 deploy.sh does not use env variables but arguments
  .travis.yml
  scripts/deploy.sh
Labels: in progress

#1644 Refactor mixin for core lock data and functions
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
Labels: in progress

#1646 Merge in recent changes from unlock-app to paywall
  paywall/package-lock.json
  paywall/package.json
  paywall/src/__tests__/middlewares/walletMiddleware.test.js
  paywall/src/__tests__/middlewares/web3Middleware.test.js
  paywall/src/__tests__/services/walletService.test.js
  paywall/src/__tests__/services/web3Service.test.js
  paywall/src/middlewares/walletMiddleware.js
  paywall/src/middlewares/web3Middleware.js
  paywall/src/services/walletService.js
Labels: Splitting Unlock-app, in progress

#1666 making the deploy-elasticbeanstalk.sh decoupled from travis
  .travis.yml
  scripts/deploy-elasticbeanstalk.sh
Labels: in progress

#1642 Adding approve for all to meet ERC721 standard
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/test/Lock/erc721/approveForAll.js
  smart-contracts/test/Lock/erc721/transferFrom.js
Labels: in progress

#1667 Add the log page to the config so it can be seen
  unlock-app/next.config.js
Labels: in progress

#1668 Trying circleci for ci
  .circleci/config.yml
  scripts/pull-image.sh
Labels: in progress

#1670 Refactor mixin for the `NoFallback` function
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/mixins/MixinNoFallback.sol
Labels: in progress

#1637 Sascha design qa lock from slide
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/creator/CreatorLockForm.js
  unlock-app/src/components/creator/lock/CreatorLockStatus.js
Labels: in progress

#1676 fixed camel case on currencyConvert
  paywall/src/__tests__/actions/currencyConvert.test.js
  paywall/src/__tests__/middlewares/currencyConversionMiddleware.test.js
  paywall/src/__tests__/reducers/currencyReducer.test.js
  paywall/src/actions/currencyConvert.js
  paywall/src/middlewares/currencyConversionMiddleware.js
  paywall/src/reducers/currencyReducer.js
  unlock-app/src/__tests__/actions/currencyConvert.test.js
  unlock-app/src/__tests__/middlewares/currencyConversionMiddleware.test.js
  unlock-app/src/__tests__/reducers/currencyReducer.test.js
  unlock-app/src/actions/currencyConvert.js
  unlock-app/src/middlewares/currencyConversionMiddleware.js
  unlock-app/src/reducers/currencyReducer.js
Labels: in progress

#1680 renamed mutationObserver
  paywall/paywall-builder/index.js
  paywall/paywall-builder/mutationObserver.js
  paywall/src/__tests__/paywall-builder/index.test.js
  paywall/src/__tests__/paywall-builder/mutationObserver.test.js
  unlock-app/src/__tests__/paywall-builder/index.test.js
  unlock-app/src/__tests__/paywall-builder/mutationObserver.test.js
  unlock-app/src/paywall-builder/index.js
  unlock-app/src/paywall-builder/mutationObserver.js
Labels: in progress

#1674 fixing syntax for IS_PULL_REQUEST en variable
  .circleci/config.yml
  scripts/circleci/set-is-pull-request.sh
Labels: in progress

#1671 Update interface for previously added functions
  smart-contracts/contracts/interfaces/IERC721.sol
Labels: in progress

#1669 Refactor mixin for refunds
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
Labels: in progress

#1665 upgrade react-redux to 6.0.2
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1695 Remove console log from test
  smart-contracts/test/Lock/disableLock.js
Labels: in progress

#1696 upgrade eslint-plugin-react-hooks
  package-lock.json
  package.json
Labels: in progress

#1706 Adds dependencies associated with the addition of block times
  locksmith/npm-shrinkwrap.json
  locksmith/package-lock.json
  locksmith/package.json
Labels: in progress

#1705 Migration associated with capturing Block mined times
  locksmith/migrations/20190225165108-create-block.js
Labels: in progress

#1708 Moving NODE_ENV to package.json
  smart-contracts/package.json
  smart-contracts/test/Unlock/UnlockProxy.js
Labels: in progress

#1710 Fix mutability in reducers
  paywall/src/reducers/keysReducer.js
  paywall/src/reducers/locksReducer.js
  unlock-app/src/reducers/keysReducer.js
  unlock-app/src/reducers/locksReducer.js
Labels: in progress

#1711 Refactored creatorLockForm which now takes a full lock object as props rather than individual lock properties
  unlock-app/src/__tests__/components/creator/CreatorLockForm.test.js
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/creator/CreatorLock.js
  unlock-app/src/components/creator/CreatorLockForm.js
  unlock-app/src/stories/creator/CreatorLockForm-errors.stories.js
  unlock-app/src/stories/creator/CreatorLockForm.stories.js
Labels: in progress

#1719 moving jest to the root of the repo
  package-lock.json
  package.json
  paywall/jest.config.js
  paywall/package-lock.json
  paywall/package.json
  unlock-app/jest.config.js
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: in progress

#1725 Remove solidity-coverage
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: in progress

#1722 Not saving the locks when the price is not changed
  unlock-app/src/__tests__/components/creator/CreatorLockForm.test.js
  unlock-app/src/components/creator/CreatorLockForm.js
Labels: in progress

#1718 remove all the hooks relating to web3
  paywall/__mocks__/web3.js
  paywall/src/__tests__/hooks/asyncActions/accounts.test.js
  paywall/src/__tests__/hooks/asyncActions/locks.test.js
  paywall/src/__tests__/hooks/components/Wallet.test.js
  paywall/src/__tests__/hooks/components/Web3.test.js
  paywall/src/__tests__/hooks/useLock.test.js
  paywall/src/__tests__/hooks/useUnlockContract.test.js
  paywall/src/__tests__/hooks/utils/usePoll.test.js
  paywall/src/__tests__/hooks/web3/useAccount.test.js
  paywall/src/__tests__/hooks/web3/useWallet.test.js
  paywall/src/__tests__/hooks/web3/useWeb3.test.js
  paywall/src/hooks/asyncActions/accounts.js
  paywall/src/hooks/asyncActions/locks.js
  paywall/src/hooks/components/Wallet.js
  paywall/src/hooks/components/Web3.js
  paywall/src/hooks/useLock.js
  paywall/src/hooks/useUnlockContract.js
  paywall/src/hooks/utils/usePoll.js
  paywall/src/hooks/web3/useAccount.js
  paywall/src/hooks/web3/useWallet.js
  paywall/src/hooks/web3/useWeb3.js
Labels: in progress

#1721 update next to 8.0.3 in paywall
  paywall/package-lock.json
  paywall/package.json
Labels: in progress

#1702 Test upgrading Unlock.sol from v0 to v1
  smart-contracts/test/Unlock/upgrades.js
Labels: in progress

#1730 renamed storeLockCreation into storeLockName
  unlock-app/src/__tests__/actions/storage.test.js
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/actions/storage.js
  unlock-app/src/middlewares/storageMiddleware.js
  unlock-app/src/middlewares/walletMiddleware.js
Labels: in progress

#1733 Bring the split paywall up to speed so that it works again
  paywall/pages/_app.js
  paywall/paywall-builder/build.js
  paywall/src/__tests__/components/lock/Overlay.test.js
  paywall/src/__tests__/middlewares/storageMiddleware.test.js
  paywall/src/__tests__/middlewares/web3Middleware.test.js
  paywall/src/__tests__/paywall-builder/build.test.js
  paywall/src/__tests__/services/storageService.test.js
  paywall/src/_server.js
  paywall/src/components/lock/Overlay.js
  paywall/src/middlewares/storageMiddleware.js
  paywall/src/middlewares/web3Middleware.js
  paywall/src/services/storageService.js
Labels: Splitting Unlock-app, in progress

#1715 Updates Locksmith with the ability to utilize a user config to local development
  locksmith/.gitignore
  locksmith/.sequelizerc
Labels: in progress

#1741 new test for Paywall component in split-off paywall
  paywall/src/__tests__/components/Paywall.test.js
Labels: Splitting Unlock-app, in progress

#1743 use the config context from withConfig instead of rolling a new one in useConfig.js
  paywall/src/__tests__/hooks/browser/useListenForPostMessage.test.js
  paywall/src/__tests__/hooks/browser/usePostMessage.test.js
  paywall/src/__tests__/hooks/helpers.js
  paywall/src/__tests__/hooks/utils/useConfig.test.js
  paywall/src/hooks/utils/useConfig.js
Labels: Splitting Unlock-app, in progress

#1700 Pull requests should be connected to filed issues
  PULL_REQUEST_TEMPLATE.md
Labels: in progress

#1746 fix all the eslint errors, and 2 bugs in paywall tests
  paywall/src/__tests__/actions/accounts.test.js
  paywall/src/__tests__/actions/currencyConvert.test.js
  paywall/src/__tests__/actions/error.test.js
  paywall/src/__tests__/actions/key.test.js
  paywall/src/__tests__/actions/keysPages.test.js
  paywall/src/__tests__/actions/lock.test.js
  paywall/src/__tests__/actions/modal.test.js
  paywall/src/__tests__/actions/network.test.js
  paywall/src/__tests__/actions/provider.test.js
  paywall/src/__tests__/actions/signature.test.js
  paywall/src/__tests__/actions/storage.test.js
  paywall/src/__tests__/actions/transaction.test.js
  paywall/src/__tests__/actions/walletStatus.test.js
  paywall/src/__tests__/components/creator/FatalError.test.js
  paywall/src/__tests__/components/developer/DeveloperOverlay.test.js
  paywall/src/__tests__/components/helpers/BalanceProvider.test.js
  paywall/src/__tests__/components/helpers/BrowserOnly.test.js
  paywall/src/__tests__/components/helpers/Duration.test.js
  paywall/src/__tests__/components/helpers/SuspendedError.test.js
  paywall/src/__tests__/components/interface/Button.test.js
  paywall/src/__tests__/components/interface/GlobalErrorConsumer.test.js
  paywall/src/__tests__/components/lock/Lock.test.js
  paywall/src/__tests__/components/lock/Overlay.test.js
  paywall/src/__tests__/hooks/browser/useListenForPostMessage.test.js
  paywall/src/__tests__/hooks/browser/useLocalStorage-no-localStorage.test.js
  paywall/src/__tests__/hooks/browser/useLocalStorage.test.js
  paywall/src/__tests__/middlewares/currencyConversionMiddleware.test.js
  paywall/src/__tests__/middlewares/interWindowCommunicationMiddleware.test.js
  paywall/src/__tests__/paywall-builder/blocker.test.js
  paywall/src/__tests__/paywall-builder/build.test.js
  paywall/src/__tests__/paywall-builder/iframe.test.js
  paywall/src/__tests__/paywall-builder/index.test.js
  paywall/src/__tests__/paywall-builder/mutationObserver.test.js
  paywall/src/__tests__/paywall-builder/script.test.js
  paywall/src/__tests__/reducers/accountReducer.test.js
  paywall/src/__tests__/reducers/currencyReducer.test.js
  paywall/src/__tests__/reducers/errorsReducer.test.js
  paywall/src/__tests__/reducers/keysPagesReducer.test.js
  paywall/src/__tests__/reducers/keysReducer.test.js
  paywall/src/__tests__/reducers/locksReducer.test.js
  paywall/src/__tests__/reducers/modalsReducer.test.js
  paywall/src/__tests__/reducers/networkReducer.test.js
  paywall/src/__tests__/reducers/providerReducer.test.js
  paywall/src/__tests__/reducers/transactionsReducer.test.js
  paywall/src/__tests__/reducers/walletStatusReducer.test.js
  paywall/src/__tests__/selectors/currency.test.js
  paywall/src/__tests__/services/walletService.test.js
  paywall/src/__tests__/services/web3Service.test.js
  paywall/src/__tests__/utils/routes.test.js
  paywall/src/actions/storage.js
  paywall/src/middlewares/walletMiddleware.js
Labels: Splitting Unlock-app, in progress

#1709 Merge MixinKeyOwner into MixinKeys
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/contracts/mixins/MixinKeyOwner.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
Labels: in progress

#1723 Add missing `memory` keyword
  smart-contracts/contracts/PublicLock.sol
Labels: in progress

#1724 Adding missing `view` keyword
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
Labels: in progress

#1726 Cast address to payable address
  smart-contracts/contracts/mixins/MixinLockCore.sol
Labels: in progress

#1727 Add missing BigNumber
  smart-contracts/test/Lock/Lock.js
  smart-contracts/test/Lock/cancelAndRefund.js
Labels: in progress

#1728 Change address 0 to 0x00..0
  smart-contracts/test/Unlock/UnlockProxy.js
Labels: in progress

#1729 Specify gas when using TestHelper
  smart-contracts/test/Unlock/UnlockProxy.js
  smart-contracts/test/Unlock/behaviors/createLock.js
  smart-contracts/test/Unlock/behaviors/createLockWithInfiniteKeys.js
Labels: in progress

#1747 adding test config and excluding files in __test/test-helpers
  locksmith/__tests__/test-helpers/authorizationHeaders.js
  locksmith/jest.config.js
  paywall/jest.config.js
  paywall/src/__tests__/test-helpers/helpers.js
  unlock-app/jest.config.js
  unlock-app/src/__tests__/test-helpers/fixtures/signatureData.js
  unlock-app/src/__tests__/utils/signature.test.js
Labels: in progress

#1716 Adding safeTransferFrom functions to Lock contract for erc721 compliance
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/UnlockErrors.sol
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/mixins/MixinDisableAndDestroy.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/erc721/onERC721Received.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
Labels: in progress

#1748 Add test case for transfers when sold out
  smart-contracts/test/Lock/erc721/transferFrom.js
Labels: in progress

#1749 Registering the erc721 interface
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/test/Lock/erc721/compliance.js
Labels: in progress

#1750 Updates Locksmith Deployment script to truncate deployment messages
  scripts/deploy-elasticbeanstalk.sh
Labels: in progress

#1735 Adding coverage and ratchet levels
  locksmith/.gitignore
  locksmith/jest.config.js
  paywall/jest.config.js
  unlock-app/jest.config.js
Labels: in progress

#1672 Adding a Lock name field
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/mixins/MixinLockMetadata.sol
  smart-contracts/test/Lock/erc721/name.js
Labels: in progress

#1755 rework lock parsing to use URL, add origin url parameter
  paywall/src/__tests__/utils/routes.test.js
  paywall/src/constants.js
  paywall/src/utils/routes.js
Labels: Splitting Unlock-app, in progress

#1758 add origin to URL
  paywall/paywall-builder/build.js
  paywall/src/__tests__/paywall-builder/build.test.js
Labels: Splitting Unlock-app, in progress

#1766 connecting the origin to postMessage handling in the paywall
  paywall/src/__tests__/hooks/browser/useListenForPostMessage.test.js
  paywall/src/__tests__/hooks/browser/usePostMessage.test.js
  paywall/src/hooks/browser/useListenForPostMessage.js
  paywall/src/hooks/browser/usePostMessage.js
Labels: Splitting Unlock-app

#1778 enable storybook on the paywall
  paywall/.storybook/addons.js
  paywall/.storybook/config.js
  paywall/package-lock.json
  paywall/package.json
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/__tests__/storybook/storyshots.test.js
  paywall/stories/lock/Overlay.stories.js
Labels: in progress

#1783 add missing svgs and make storybook smart enough to load them
  paywall/package.json
  paywall/static/images/illustrations/error.svg
  paywall/static/images/illustrations/network.svg
  paywall/static/images/illustrations/wallet.svg
Labels: in progress

#1791 Adding actions to sign data blobs
  unlock-app/src/__tests__/actions/signature.test.js
  unlock-app/src/actions/signature.js
Labels: in progress
