Repository unlock-protocol/unlock, pull requests merged in 2019-06, with the labels that each got.

#3615 Added Blog and Twitter buttons to landing page
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-protocol.com/src/components/interface/Footer.js
  unlock-protocol.com/src/components/interface/Header.js
  unlock-protocol.com/src/components/interface/buttons/layout/Blog.js
  unlock-protocol.com/src/components/interface/buttons/layout/Twitter.js
  unlock-protocol.com/src/components/interface/buttons/layout/index.js
  unlock-protocol.com/src/components/interface/svg/Blog.js
  unlock-protocol.com/src/components/interface/svg/index.js
  unlock-protocol.com/src/static/images/svg/blog.svg
  unlock-protocol.com/src/stories/interface/LayoutButtons.stories.js
Labels: design

#3616 Added background cover image
  unlock-app/src/static/images/illustrations/background-cover.jpg
Labels: design

#3669 Introducing a basic grid
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/helpers/Grid.tsx
  unlock-app/src/stories/helpers/Grid.stories.js
Labels: frontend

#3718 add currencyContractAddress to validation
  paywall/src/__tests__/utils/validators.test.js
  paywall/src/components/lock/NoKeyLock.js
  paywall/src/utils/validators.js
Labels: p-1
