Repository unlock-protocol/unlock, pull requests merged in 2019-04, with the labels that each got.

#2544 Add actions needed to coordinate authentication
  unlock-app/src/__tests__/actions/authentication.test.js
  unlock-app/src/actions/authentication.js
Labels: User Accounts

#2540 Initial version of Unlock Provider
  unlock-app/src/__tests__/services/unlockProvider.test.js
  unlock-app/src/services/unlockProvider.js
Labels: User Accounts

#2543 Initial Key Chain authentication screen
  unlock-app/src/__tests__/components/interface/Authentication.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/KeyChainContent.js
  unlock-app/src/components/interface/AuthenticationPrompt.tsx
  unlock-app/src/stories/interface/AuthenticationPrompt.stories.js
Labels: User Accounts

#2577 Add Sign Up Page to KeyChain
  unlock-app/src/__tests__/components/interface/SignUp.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/KeyChainContent.js
  unlock-app/src/components/interface/SignUp.tsx
  unlock-app/src/stories/interface/SignUp.stories.js
Labels: User Accounts, frontend

#2626 Shuffle some storageService tokens and add TODOs
  unlock-app/src/services/storageService.js
Labels: User Accounts

#2643 Add basic wedlocks service
  unlock-app/src/__tests__/services/wedlockService.test.js
  unlock-app/src/services/wedlockService.ts
Labels: User Accounts

#2651 Introduce wedlocks middleware
  unlock-app/src/__tests__/middlewares/wedlocksMiddleware.test.ts
  unlock-app/src/middlewares/wedlocksMiddleware.ts
Labels: Epic, User Accounts

#2655 Storage middleware now ready to handle user creation
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/middlewares/storageMiddleware.js
Labels: Epic, User Accounts

#2669 Add component for finishing signup process
  unlock-app/src/__tests__/components/interface/FinishSignup.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/FinishSignup.tsx
  unlock-app/src/stories/interface/FinishSignup.stories.js
Labels: User Accounts, frontend

#2812 Introduces storage for user's stripe customer id in data store
  locksmith/migrations/20190420180959-add_stripe_customer_id_to_user_reference.js
Labels: Locksmith, User Accounts

#2813 Updates user reference model with the ability to access stripe customer details
  locksmith/src/models/userReference.ts
Labels: Locksmith, User Accounts

#2814 Introduces our initial Payment Processing code
  locksmith/__tests__/payment/paymentProcessor.test.ts
  locksmith/src/payment/paymentProcessor.ts
Labels: Locksmith, User Accounts

#2829 Adding pricing stub
  locksmith/__tests__/controllers/priceController.test.ts
  locksmith/package-lock.json
  locksmith/package.json
  locksmith/src/app.js
  locksmith/src/controllers/priceController.ts
  locksmith/src/routes/price.ts
  locksmith/src/types.ts
  locksmith/src/utils/keyPricer.ts
Labels: Locksmith, User Accounts

#2854 Purchase controller updated to charge eligible users
  locksmith/__tests__/controllers/purchaseController.test.js
  locksmith/src/controllers/purchaseController.ts
  locksmith/src/types.ts
Labels: Locksmith, User Accounts
