Repository unlock-protocol/unlock, pull requests merged in 2019-10, with the labels that each got.

#4917 Adds metadata operation allowing users to persist their own data associated with a given lock
  locksmith/__tests__/controllers/linkDrop.test.js
  locksmith/__tests__/operations/userMetadataOperations.test.ts
  locksmith/migrations/20191001184934-usermetadataConstraint.js
  locksmith/src/models/index.ts
  locksmith/src/models/usertokenmetadata.ts
  locksmith/src/operations/userMetadataOperations.ts
Labels: cla-signed

#4916 Update the event email template
  wedlocks/src/__tests__/templates/confirmEvent.test.js
  wedlocks/src/templates/confirmEvent.js
Labels: cla-signed

#4918 Emitting additional logging information around emails sent
  wedlocks/src/route.js
Labels: cla-signed

#4919 Update wording for EthWaterloo and dispatch correctly
  wedlocks/src/__tests__/templates/confirmEvent.test.js
  wedlocks/src/templates/confirmEvent.js
Labels: cla-signed

#4920 Showing the loading state until all locks have been loaded
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/checkout/Checkout.tsx
  paywall/src/stories/checkout/Checkout.stories.js
Labels: cla-signed

#4921 Refactored several methods to bring flexibilty in the API calls.
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v0/purchaseKey.test.js
  unlock-js/src/__tests__/v0/updateKeyPrice.test.js
  unlock-js/src/__tests__/v0/withdrawFromLock.test.js
  unlock-js/src/__tests__/v01/createLock.test.js
  unlock-js/src/__tests__/v01/purchaseKey.test.js
  unlock-js/src/__tests__/v01/updateKeyPrice.test.js
  unlock-js/src/__tests__/v01/withdrawFromLock.test.js
  unlock-js/src/__tests__/v02/purchaseKey.test.js
  unlock-js/src/__tests__/v02/updateKeyPrice.test.js
  unlock-js/src/__tests__/v02/withdrawFromLock.test.js
  unlock-js/src/__tests__/v10/purchaseKey.test.js
  unlock-js/src/__tests__/v10/updateKeyPrice.test.js
  unlock-js/src/__tests__/v10/withdrawFromLock.test.js
  unlock-js/src/__tests__/v11/purchaseKey.test.js
  unlock-js/src/__tests__/v11/updateKeyPrice.test.js
  unlock-js/src/__tests__/v11/withdrawFromLock.test.js
  unlock-js/src/__tests__/walletService.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v0/purchaseKey.js
  unlock-js/src/v0/updateKeyPrice.js
  unlock-js/src/v0/withdrawFromLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v01/purchaseKey.js
  unlock-js/src/v01/updateKeyPrice.js
  unlock-js/src/v01/withdrawFromLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v02/purchaseKey.js
  unlock-js/src/v02/updateKeyPrice.js
  unlock-js/src/v02/withdrawFromLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v10/updateKeyPrice.js
  unlock-js/src/v10/withdrawFromLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/v11/updateKeyPrice.js
  unlock-js/src/v11/withdrawFromLock.js
  unlock-js/src/walletService.js
Labels: cla-signed

#4925 Special case for event date
  tickets/src/__tests__/components/interface/EventInfo.test.tsx
  tickets/src/components/interface/EventInfo.tsx
Labels: cla-signed

#4927 Production manual Deploy production-20191002-154527
  locksmith/__tests__/controllers/linkDrop.test.js
  locksmith/__tests__/operations/userMetadataOperations.test.ts
  locksmith/migrations/20191001184934-usermetadataConstraint.js
  locksmith/src/models/index.ts
  locksmith/src/models/usertokenmetadata.ts
  locksmith/src/operations/userMetadataOperations.ts
  paywall/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  paywall/src/components/checkout/Checkout.tsx
  paywall/src/stories/checkout/Checkout.stories.js
  tickets/src/__tests__/components/interface/EventInfo.test.tsx
  tickets/src/components/interface/EventInfo.tsx
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v0/purchaseKey.test.js
  unlock-js/src/__tests__/v0/updateKeyPrice.test.js
  unlock-js/src/__tests__/v0/withdrawFromLock.test.js
  unlock-js/src/__tests__/v01/createLock.test.js
  unlock-js/src/__tests__/v01/purchaseKey.test.js
  unlock-js/src/__tests__/v01/updateKeyPrice.test.js
  unlock-js/src/__tests__/v01/withdrawFromLock.test.js
  unlock-js/src/__tests__/v02/purchaseKey.test.js
  unlock-js/src/__tests__/v02/updateKeyPrice.test.js
  unlock-js/src/__tests__/v02/withdrawFromLock.test.js
  unlock-js/src/__tests__/v10/purchaseKey.test.js
  unlock-js/src/__tests__/v10/updateKeyPrice.test.js
  unlock-js/src/__tests__/v10/withdrawFromLock.test.js
  unlock-js/src/__tests__/v11/purchaseKey.test.js
  unlock-js/src/__tests__/v11/updateKeyPrice.test.js
  unlock-js/src/__tests__/v11/withdrawFromLock.test.js
  unlock-js/src/__tests__/walletService.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v0/purchaseKey.js
  unlock-js/src/v0/updateKeyPrice.js
  unlock-js/src/v0/withdrawFromLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v01/purchaseKey.js
  unlock-js/src/v01/updateKeyPrice.js
  unlock-js/src/v01/withdrawFromLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v02/purchaseKey.js
  unlock-js/src/v02/updateKeyPrice.js
  unlock-js/src/v02/withdrawFromLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v10/updateKeyPrice.js
  unlock-js/src/v10/withdrawFromLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/v11/updateKeyPrice.js
  unlock-js/src/v11/withdrawFromLock.js
  unlock-js/src/walletService.js
  wedlocks/src/__tests__/templates/confirmEvent.test.js
  wedlocks/src/route.js
  wedlocks/src/templates/confirmEvent.js
Labels: cla-signed

#4926 Adds endpoint for storing UserMetadata associated with Locks
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/operations/userMetadataOperations.ts
  locksmith/src/routes/metadata.ts
Labels: cla-signed

#4923 add `blockchainData()` method to `window.unlockProtocol`
  paywall/src/__tests__/unlock.js/MainWindowHandler/blockchainData.test.ts
  paywall/src/unlock.js/MainWindowHandler.ts
Labels: cla-signed

#4922 Removed owner from createLock
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v0/createLock.test.js
  unlock-js/src/__tests__/v01/createLock.test.js
  unlock-js/src/__tests__/v02/createLock.test.js
  unlock-js/src/__tests__/v10/createLock.test.js
  unlock-js/src/__tests__/v11/createLock.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/walletService.js
Labels: cla-signed

#4929 retrieving locks from locksmith
  tickets/src/__tests__/middlewares/web3Middleware.test.js
  tickets/src/__tests__/services/storageService.test.js
  tickets/src/middlewares/web3Middleware.js
  tickets/src/services/storageService.js
Labels: cla-signed

#4930 getting erc20Address and decimals from the contract when purchasing a key
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v10/purchaseKey.test.js
  unlock-js/src/__tests__/v11/purchaseKey.test.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/walletService.js
Labels: cla-signed

#4931 updateKeyPrice now uses the right decimals for erc20 contracts
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v0/updateKeyPrice.test.js
  unlock-js/src/__tests__/v01/updateKeyPrice.test.js
  unlock-js/src/__tests__/v02/updateKeyPrice.test.js
  unlock-js/src/__tests__/v10/updateKeyPrice.test.js
  unlock-js/src/__tests__/v11/updateKeyPrice.test.js
  unlock-js/src/v0/updateKeyPrice.js
  unlock-js/src/v01/updateKeyPrice.js
  unlock-js/src/v02/updateKeyPrice.js
  unlock-js/src/v10/updateKeyPrice.js
  unlock-js/src/v11/updateKeyPrice.js
Labels: cla-signed

#4936 Accounts iframe buffers received postmessages
  paywall/src/__tests__/unlock.js/PostMessageEmitters/AccountsIframeMessageEmitter.test.ts
  paywall/src/unlock.js/PostMessageEmitters/AccountsIframeMessageEmitter.ts
Labels: cla-signed

#4933 Paywall tells accounts iframe if page is locked/unlocked
  paywall/src/__tests__/unlock.js/MainWindowHandler/init.test.ts
  paywall/src/unlock.js/MainWindowHandler.ts
Labels: cla-signed

#4935 Add remaining Unlock-abi packages
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: cla-signed

#4937 Account iframe listens for locked/unlocked
  unlock-app/src/__tests__/services/postOfficeService.test.ts
  unlock-app/src/messageTypes.ts
  unlock-app/src/services/postOfficeService.ts
Labels: cla-signed

#4939 Updating token metadata endpoint to include User Metadata
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/__tests__/operations/userMetadataOperations.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/operations/metadataOperations.ts
  locksmith/src/operations/userMetadataOperations.ts
Labels: cla-signed

#4938 Wait for the iframe to initialize before draining buffer
  paywall/src/__tests__/unlock.js/PostMessageEmitters/AccountsIframeMessageEmitter.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccounts.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/unlock.js/PostMessageEmitters/AccountsIframeMessageEmitter.ts
Labels: cla-signed

#4940 Page {locked,unlocked} status available in redux for account iframe
  unlock-app/src/__tests__/actions/pageStatus.test.ts
  unlock-app/src/__tests__/middlewares/postOfficeMiddleware.test.ts
  unlock-app/src/__tests__/reducers/pageStatusReducer.test.ts
  unlock-app/src/actions/pageStatus.ts
  unlock-app/src/createUnlockStore.js
  unlock-app/src/middlewares/postOfficeMiddleware.ts
  unlock-app/src/reducers/pageStatusReducer.ts
Labels: cla-signed

#4941 AccountContent recognizes when user has a key
  unlock-app/src/__tests__/components/content/AccountContent.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/AccountContent.tsx
  unlock-app/src/stories/content/AccountContent.stories.js
Labels: cla-signed

#4942 Add unlock-abi-1-1
  smart-contracts/package.json
Labels: cla-signed

#4932 adding ethwaterloo post
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/ethwaterloo-tickets.md
  unlock-protocol.com/src/static/images/blog/ethwaterloo-tickets/credit-card.png
  unlock-protocol.com/src/static/images/blog/ethwaterloo-tickets/ethwaterloo.png
  unlock-protocol.com/src/static/images/blog/ethwaterloo-tickets/event-page.png
  unlock-protocol.com/src/static/images/blog/ethwaterloo-tickets/sign-in.png
Labels: cla-signed

#4915 Increase upgrades test coverage
  smart-contracts/test/Unlock/upgrades/latestVersion.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
  smart-contracts/test/Unlock/upgrades/v1ToLatest.js
  smart-contracts/test/Unlock/upgrades/v2ToLatest.js
  smart-contracts/test/Unlock/upgrades/v3ToLatest.js
  smart-contracts/test/Unlock/upgrades/v4ToLatest.js
  smart-contracts/test/Unlock/upgrades/v5ToLatest.js
Labels: cla-signed

#4944 Update unlock-js across all apps
  docker/development/package-lock.json
  docker/development/package.json
  locksmith/package-lock.json
  locksmith/package.json
  paywall/package-lock.json
  paywall/package.json
  tickets/package-lock.json
  tickets/package.json
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#4947 prevent Safari from throwing errors when accessing localstorage
  unlock-app/src/utils/localStorage.ts
Labels: cla-signed

#4951 Fix determination of expensiveness
  paywall/src/__tests__/data-iframe/blockchainHandler/BlockchainHandler/BlockchainHandler.test.ts
  paywall/src/__tests__/utils/locks.test.js
  paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts
  paywall/src/stories/lock/Lock.stories.js
  paywall/src/utils/locks.js
Labels: cla-signed

#4952 Production manual Deploy production-20191005-200311
  paywall/src/__tests__/data-iframe/blockchainHandler/BlockchainHandler/BlockchainHandler.test.ts
  paywall/src/__tests__/utils/locks.test.js
  paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts
  paywall/src/stories/lock/Lock.stories.js
  paywall/src/utils/locks.js
Labels: cla-signed

#4953 createLock now returns a Promise of the deployed lock address
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v0/createLock.test.js
  unlock-js/src/__tests__/v01/createLock.test.js
  unlock-js/src/__tests__/v02/createLock.test.js
  unlock-js/src/__tests__/v10/createLock.test.js
  unlock-js/src/__tests__/v11/createLock.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/walletService.js
Labels: cla-signed

#4959 Adding model and migration for Ejection
  locksmith/migrations/20191007172410-mark_ejection.js
  locksmith/src/models/user.ts
Labels: cla-signed

#4957 changed the button to create or update an event
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/content/HomeContent.js
Labels: cla-signed

#4960 Fix zos initMethod for upgrade tests
  smart-contracts/test/Unlock/UnlockProxy.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
  smart-contracts/test/Unlock/upgrades/v1ToLatest.js
  smart-contracts/test/Unlock/upgrades/v2ToLatest.js
  smart-contracts/test/Unlock/upgrades/v3ToLatest.js
  smart-contracts/test/Unlock/upgrades/v4ToLatest.js
  smart-contracts/test/Unlock/upgrades/v5ToLatest.js
Labels: cla-signed, smart contract

#4963 Revert "Update all non-major dependencies"
  locksmith/package-lock.json
  locksmith/package.json
  package-lock.json
  package.json
  paywall/package-lock.json
  paywall/package.json
  smart-contracts/package-lock.json
  smart-contracts/package.json
  smart-contracts/test/helpers/walletServiceMock.js
  tickets/package-lock.json
  tickets/package.json
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-js/package-lock.json
  unlock-js/package.json
  unlock-protocol.com/package-lock.json
  unlock-protocol.com/package.json
  wedlocks/package-lock.json
  wedlocks/package.json
Labels: cla-signed

#4966 locks with a keyPrice of 0 are not too expensive
  paywall/src/__tests__/utils/locks.test.js
  paywall/src/utils/locks.js
Labels: cla-signed

#4967 Production manual Deploy production-20191008-085005
  locksmith/migrations/20191007172410-mark_ejection.js
  locksmith/src/models/user.ts
  paywall/src/__tests__/utils/locks.test.js
  paywall/src/utils/locks.js
  smart-contracts/test/Unlock/UnlockProxy.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
  smart-contracts/test/Unlock/upgrades/v1ToLatest.js
  smart-contracts/test/Unlock/upgrades/v2ToLatest.js
  smart-contracts/test/Unlock/upgrades/v3ToLatest.js
  smart-contracts/test/Unlock/upgrades/v4ToLatest.js
  smart-contracts/test/Unlock/upgrades/v5ToLatest.js
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/content/HomeContent.js
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v0/createLock.test.js
  unlock-js/src/__tests__/v01/createLock.test.js
  unlock-js/src/__tests__/v02/createLock.test.js
  unlock-js/src/__tests__/v10/createLock.test.js
  unlock-js/src/__tests__/v11/createLock.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/walletService.js
Labels: cla-signed

#4964 Renovate: separate patch PR from minor PR
  renovate.json
Labels: cla-signed

#4790 Deploy PublicLock using a minimal proxy
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/CloneFactory.sol
  smart-contracts/migrations/3_create_proxy.js
  smart-contracts/test/Lock/erc721/tokenSymbol.js
  smart-contracts/test/Lock/erc721/tokenURI.js
  smart-contracts/test/Lock/grantKeys.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Unlock/UnlockProxy.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
  smart-contracts/test/Unlock/upgrades/v1ToLatest.js
  smart-contracts/test/Unlock/upgrades/v2ToLatest.js
  smart-contracts/test/Unlock/upgrades/v3ToLatest.js
  smart-contracts/test/Unlock/upgrades/v4ToLatest.js
  smart-contracts/test/Unlock/upgrades/v5ToLatest.js
  smart-contracts/test/helpers/deployLocks.js
Labels: cla-signed, smart contract

#4961 Migrate to `unlock-abi-0` package
  smart-contracts/package-lock.json
  smart-contracts/package.json
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
Labels: cla-signed, smart contract

#4943 unlock-provider gains personal_sign method
  unlock-js/CHANGELOG.md
  unlock-js/package.json
  unlock-js/src/__tests__/unlockProvider.test.js
  unlock-js/src/unlockProvider.js
Labels: cla-signed

#4962 Switch from using fractions to basisPoints
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Lock/erc721/approveForAll.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/freeTrial.js
  smart-contracts/test/Lock/getHasValidKey.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/transferFee.js
Labels: cla-signed, smart contract

#4970 Simplify deploy helper
  smart-contracts/test/helpers/deployLocks.js
Labels: cla-signed, smart contract

#4971 Solidity 0.5.12
  smart-contracts/contracts/Migrations.sol
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/UnlockDiscountToken.sol
  smart-contracts/contracts/UnlockUtils.sol
  smart-contracts/contracts/interfaces/IERC721.sol
  smart-contracts/contracts/interfaces/IERC721Enumerable.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/interfaces/IUnlockEventHooks.sol
  smart-contracts/contracts/mixins/CloneFactory.sol
  smart-contracts/contracts/mixins/MixinApproval.sol
  smart-contracts/contracts/mixins/MixinDisableAndDestroy.sol
  smart-contracts/contracts/mixins/MixinERC721Enumerable.sol
  smart-contracts/contracts/mixins/MixinEventHooks.sol
  smart-contracts/contracts/mixins/MixinFunds.sol
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinLockMetadata.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/contracts/test-artifacts/TestErc20Noop.sol
  smart-contracts/contracts/test-artifacts/TestErc20PausableToken.sol
  smart-contracts/contracts/test-artifacts/TestErc20Token.sol
  smart-contracts/contracts/test-artifacts/TestKeySoldHook.sol
  smart-contracts/contracts/test-artifacts/TestNoop.sol
  smart-contracts/test/Unlock/TestUnlock.sol
  smart-contracts/truffle-config.js
Labels: cla-signed, smart contract

#4783 Uniswap token value to track GDP in ETH
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUniswap.sol
  smart-contracts/test/Unlock/uniswapValue.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
Labels: cla-signed, smart contract

#4969 Unlock app handles messages for unlock provider web3 calls
  unlock-app/src/__tests__/actions/web3call.test.ts
  unlock-app/src/__tests__/middlewares/postOfficeMiddleware.test.ts
  unlock-app/src/__tests__/middlewares/providerMiddleware.test.ts
  unlock-app/src/__tests__/services/postOfficeService.test.ts
  unlock-app/src/actions/web3call.ts
  unlock-app/src/messageTypes.ts
  unlock-app/src/middlewares/postOfficeMiddleware.ts
  unlock-app/src/middlewares/providerMiddleware.ts
  unlock-app/src/services/postOfficeService.ts
  unlock-app/src/windowTypes.ts
Labels: cla-signed

#4968 Allowing absolute URL for og tags
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/jest.setup.js
  unlock-protocol.com/next.config.js
  unlock-protocol.com/src/components/page/OpenGraphTags.js
  unlock-protocol.com/src/components/page/TwitterTags.js
  unlock-protocol.com/src/constants.js
  unlock-protocol.com/src/pages/post.js
Labels: cla-signed

#4958 add `signData` method to `window.unlockProtocol`
  paywall/src/EventEmitterTypes.ts
  paywall/src/__tests__/data-iframe/Mailbox/Mailbox.test.ts
  paywall/src/__tests__/data-iframe/Mailbox/setupPostMessageListeners.test.ts
  paywall/src/__tests__/test-helpers/setupBlockchainHelpers.ts
  paywall/src/__tests__/unlock.js/MainWindowHandler/setupUnlockProtocolVariable.test.ts
  paywall/src/__tests__/unlock.js/MainWindowHandler/signData.test.ts
  paywall/src/__tests__/unlock.js/PostMessageEmitters/DataIframeMessageEmitter.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/__tests__/utils/Callbacker.test.ts
  paywall/src/constants.js
  paywall/src/data-iframe/Mailbox.ts
  paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts
  paywall/src/data-iframe/blockchainHandler/blockChainTypes.ts
  paywall/src/messageTypes.ts
  paywall/src/unlock.js/MainWindowHandler.ts
  paywall/src/unlock.js/PostMessageEmitters/DataIframeMessageEmitter.ts
  paywall/src/unlock.js/Wallet.ts
  paywall/src/utils/Callbacker.ts
  paywall/src/windowTypes.ts
Labels: cla-signed

#4972 Adding ejection action and operation
  locksmith/__tests__/controllers/linkDrop.test.js
  locksmith/__tests__/controllers/transactionController.test.js
  locksmith/__tests__/controllers/userController.test.ts
  locksmith/__tests__/controllers/userController/ejection.test.ts
  locksmith/__tests__/controllers/userController/emailUpdate.test.ts
  locksmith/__tests__/controllers/userController/keys.test.ts
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/__tests__/controllers/userController/paymentDetails.test.ts
  locksmith/__tests__/controllers/userController/privateKey.test.ts
  locksmith/__tests__/controllers/userController/recoveryPhrase.test.ts
  locksmith/__tests__/controllers/userController/userCreation.test.ts
  locksmith/__tests__/operations/userOperations.test.ts
  locksmith/src/controllers/userController.ts
  locksmith/src/operations/userOperations.ts
  locksmith/src/routes/user.ts
Labels: cla-signed

#4976 Excluding ejected account from recovery phrase requests
  locksmith/__tests__/controllers/userController/recoveryPhrase.test.ts
  locksmith/src/controllers/userController.ts
  locksmith/src/operations/userOperations.ts
Labels: cla-signed

#4977 Shifting UseBlockChainData to TS
  paywall/src/components/content/CheckoutContent.tsx
  paywall/src/hooks/useBlockchainData.ts
  paywall/src/unlockTypes.ts
Labels: cla-signed

#4979 Private key ejection aware
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/__tests__/controllers/userController/privateKey.test.ts
  locksmith/src/controllers/userController.ts
Labels: cla-signed

#4978 Moving duration helper to typescript
  paywall/src/components/helpers/Duration.tsx
Labels: cla-signed

#4974 using an absolute path
  unlock-protocol.com/src/components/page/OpenGraphTags.js
Labels: cla-signed

#4954 Adding walletService integration tests
  smart-contracts/published-npm-modules/V0.1/README.md
  unlock-js/src/__tests__/deploy.test.js
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/__tests__/integration/web3ServiceIntegration.test.js
  unlock-js/src/__tests__/unlockService.test.js
  unlock-js/src/__tests__/v0/getLock.test.js
  unlock-js/src/unlockService.js
  unlock-js/src/v11/createLock.js
Labels: cla-signed

#4973 adding post about linkdrop
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/linkdrop.md
  unlock-protocol.com/src/components/content/BlogIndex.js
  unlock-protocol.com/src/static/images/blog/linkdrop/Linkdrop.png
Labels: cla-signed

#4981 snapshot update
  unlock-protocol.com/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
Labels: cla-signed

#4984 Adding dobrokhvalov
  .clabot
Labels: cla-signed

#4982 Update linkdrop.md (Hotfix for linkdrop links)
  unlock-protocol.com/blog/linkdrop.md
Labels: cla-signed

#4980 encoding addresses in recovery emails
  unlock-app/src/__tests__/middlewares/wedlocksMiddleware.test.ts
  unlock-app/src/__tests__/services/wedlockService.test.js
  unlock-app/src/middlewares/wedlocksMiddleware.ts
  unlock-app/src/services/wedlockService.ts
Labels: cla-signed

#4985 Update token expiry presentation
  locksmith/__tests__/utils/keyData.test.ts
  locksmith/src/utils/keyData.ts
Labels: cla-signed

#4989 Update email update to be ejection aware
  locksmith/__tests__/controllers/userController/emailUpdate.test.ts
  locksmith/src/controllers/userController.ts
Labels: cla-signed

#4988 Return a 404 when attempting to update ejected users payment details
  locksmith/__tests__/controllers/userController/paymentDetails.test.ts
  locksmith/src/controllers/userController.ts
Labels: cla-signed

#4990 Assert your identity from the /identity page
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-app/src/__tests__/components/content/IdentityContent.test.tsx
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/reducers/signatureReducer.test.js
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/components/content/IdentityContent.tsx
  unlock-app/src/createUnlockStore.js
  unlock-app/src/middlewares/walletMiddleware.js
  unlock-app/src/pages/identity.tsx
  unlock-app/src/reducers/signatureReducer.js
  unlock-app/src/utils/Error.ts
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#4991 remove old unneeded test files
  smart-contracts/test/Lock/Non_Public_purchaseFor.js
  smart-contracts/test/Lock/erc721/Non_Public_approve.js
  smart-contracts/test/Lock/erc721/Non_Public_getApproved.js
  smart-contracts/test/Lock/erc721/Non_Public_transferFrom.js
Labels: cla-signed

#4992 hardcoding image url for coinfund-rabbithole event
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/interface/EventInfo.tsx
  tickets/src/services/eventService.js
Labels: cla-signed

#4996 making paywall test more deterministic
  paywall/src/stories/checkout/Checkout.stories.js
Labels: cla-signed

#4997 Removing key endpoint and associated code
  locksmith/__tests__/controllers/userController/emailUpdate.test.ts
  locksmith/__tests__/controllers/userController/keys.test.ts
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/__tests__/controllers/userController/paymentDetails.test.ts
  locksmith/__tests__/controllers/userController/privateKey.test.ts
  locksmith/__tests__/controllers/userController/recoveryPhrase.test.ts
  locksmith/__tests__/controllers/userController/userCreation.test.ts
  locksmith/__tests__/utils/ownedKeys.test.ts
  locksmith/src/controllers/userController.ts
  locksmith/src/routes/user.ts
  locksmith/src/utils/ownedKeys.ts
Labels: cla-signed

#4994 Update website to work with Node 10
  docker/unlock-core.dockerfile
  locksmith/Dockerfile
  paywall/package.json
  rover/Dockerfile
  smart-contracts/package.json
  tickets/package.json
  unlock-app/package.json
  unlock-protocol.com/package.json
  unlock-protocol.com/src/utils/blog.js
Labels: cla-signed

#4999 Revert "Update website to work with Node 10"
  docker/unlock-core.dockerfile
  locksmith/Dockerfile
  paywall/package.json
  rover/Dockerfile
  smart-contracts/package.json
  tickets/package.json
  unlock-app/package.json
  unlock-protocol.com/package.json
  unlock-protocol.com/src/utils/blog.js
Labels: cla-signed

#4998 Updating user creation to be aware of ejected accounts
  locksmith/__tests__/controllers/userController/userCreation.test.ts
  locksmith/src/controllers/userController.ts
Labels: cla-signed

#5000 Fix invalid comment in EventInfo
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/interface/EventInfo.tsx
Labels: cla-signed, frontend, p-0

#5001 Production manual Deploy production-20191011-114041
  locksmith/__tests__/controllers/userController/emailUpdate.test.ts
  locksmith/__tests__/controllers/userController/keys.test.ts
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/__tests__/controllers/userController/paymentDetails.test.ts
  locksmith/__tests__/controllers/userController/privateKey.test.ts
  locksmith/__tests__/controllers/userController/recoveryPhrase.test.ts
  locksmith/__tests__/controllers/userController/userCreation.test.ts
  locksmith/__tests__/utils/ownedKeys.test.ts
  locksmith/src/controllers/userController.ts
  locksmith/src/routes/user.ts
  locksmith/src/utils/ownedKeys.ts
  paywall/src/stories/checkout/Checkout.stories.js
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/interface/EventInfo.tsx
Labels: cla-signed

#5002 Add QR scanner lib for verification
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5003 Updating ejection to fail when attempting to eject multiple times
  locksmith/__tests__/controllers/userController/ejection.test.ts
  locksmith/src/controllers/userController.ts
  locksmith/src/operations/userOperations.ts
Labels: cla-signed

#5004 Returning an error if attempting to update the password of an ejected account
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/src/controllers/userController.ts
Labels: cla-signed

#4788 Add a tip to ERC-20 lock purchases
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/cancelAndRefundFor.js
  smart-contracts/test/Lock/destroyLock.js
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/approveForAll.js
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/erc721/enumerable.js
  smart-contracts/test/Lock/erc721/getApproved.js
  smart-contracts/test/Lock/erc721/getTokenIdFor.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/tokenURI.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/expireKeyFor.js
  smart-contracts/test/Lock/freeTrial.js
  smart-contracts/test/Lock/fullRefund.js
  smart-contracts/test/Lock/gas.js
  smart-contracts/test/Lock/getBalance.js
  smart-contracts/test/Lock/getHasValidKey.js
  smart-contracts/test/Lock/getOwnersByPage.js
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeySoldHook.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/purchaseFor.js
  smart-contracts/test/Lock/purchaseForFrom.js
  smart-contracts/test/Lock/purchaseTip.js
  smart-contracts/test/Lock/transferFee.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/Unlock/lockTotalSales.js
  smart-contracts/test/Unlock/uniswapValue.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
  smart-contracts/test/Unlock/upgrades/v1ToLatest.js
  smart-contracts/test/Unlock/upgrades/v2ToLatest.js
  smart-contracts/test/Unlock/upgrades/v3ToLatest.js
  smart-contracts/test/Unlock/upgrades/v4ToLatest.js
  smart-contracts/test/Unlock/upgrades/v5ToLatest.js
Labels: cla-signed, smart contract

#5009 Deploying Unlock to Kovan network
  smart-contracts/truffle-config.js
  smart-contracts/zos.kovan.json
Labels: cla-signed

#5015 Keychain is slightly prettier
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/KeyChainContent.js
  unlock-app/src/stories/keyChain/keyChain.stories.js
Labels: cla-signed

#5016 Remove identity page
  unlock-app/src/__tests__/components/content/IdentityContent.test.tsx
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/components/content/IdentityContent.tsx
  unlock-app/src/pages/identity.tsx
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#5014 Make sure to zero out eth balance for logged out users
  paywall/src/__tests__/unlock.js/CheckoutUIHandler.test.ts
  paywall/src/__tests__/unlock.js/Wallet/enableCryptoWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccounts.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
  paywall/src/__tests__/unlock.js/startup.test.ts
  paywall/src/unlock.js/CheckoutUIHandler.ts
  paywall/src/unlock.js/constants.ts
  paywall/src/unlock.js/startup.ts
  paywall/src/unlock.js/startupTypes.ts
Labels: cla-signed

#5018 updateKeyPrice yields a promise with the new price once mined
  unlock-js/src/__tests__/v0/updateKeyPrice.test.js
  unlock-js/src/__tests__/v01/updateKeyPrice.test.js
  unlock-js/src/__tests__/v02/updateKeyPrice.test.js
  unlock-js/src/__tests__/v10/updateKeyPrice.test.js
  unlock-js/src/__tests__/v11/updateKeyPrice.test.js
  unlock-js/src/v0/updateKeyPrice.js
  unlock-js/src/v01/updateKeyPrice.js
  unlock-js/src/v02/updateKeyPrice.js
  unlock-js/src/v10/updateKeyPrice.js
  unlock-js/src/v11/updateKeyPrice.js
  unlock-js/src/walletService.js
  unlock-js/src/web3Service.js
Labels: cla-signed

#5019 walletService dispatches personal_sign for unlock-provider
  unlock-js/CHANGELOG.md
  unlock-js/package.json
  unlock-js/src/__tests__/walletService.test.js
  unlock-js/src/walletService.js
Labels: cla-signed

#5021 Update unlock-js in all apps to 0.3.18
  locksmith/package-lock.json
  locksmith/package.json
  paywall/package-lock.json
  paywall/package.json
  tickets/package-lock.json
  tickets/package.json
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5020 adding tests for updateKeyPrice
  unlock-js/src/__tests__/helpers/fixtures/locks.js
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/__tests__/v0/getLock.test.js
  unlock-js/src/__tests__/v01/getLock.test.js
  unlock-js/src/__tests__/v02/getLock.test.js
  unlock-js/src/v0/getLock.js
  unlock-js/src/v01/getLock.js
  unlock-js/src/v02/getLock.js
  unlock-js/src/web3Service.js
Labels: cla-signed

#5022 rather than using the commit, use the diff to master
  .circleci/config.yml
  scripts/monorepo.sh
Labels: cla-signed

#5017 Add `resetTrackedValue`
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/test/Unlock/resetTrackedValue.js
Labels: cla-signed, smart contract

#5025 Adding test coverage for unsigned ejection scenario
  locksmith/__tests__/controllers/userController/ejection.test.ts
  locksmith/package.json
  locksmith/src/controllers/userController.ts
  locksmith/src/routes/user.ts
Labels: cla-signed

#5010 Bump hardlydifficult-ethereum-contracts (for `Clone2Factory`)
  smart-contracts/package-lock.json
  smart-contracts/package.json
  smart-contracts/test/Unlock/uniswapValue.js
  smart-contracts/test/test-artifacts/Uniswap.js
Labels: cla-signed, smart contract

#5030 Update reducer to track multiple signatures at the same time
  unlock-app/src/__tests__/actions/signature.test.js
  unlock-app/src/__tests__/middlewares/walletMiddleware.test.js
  unlock-app/src/__tests__/reducers/signatureReducer.test.js
  unlock-app/src/actions/signature.js
  unlock-app/src/middlewares/walletMiddleware.js
  unlock-app/src/reducers/signatureReducer.js
Labels: cla-signed

#5023 updated node engine to use 10.16.3
  docker/unlock-core.dockerfile
  locksmith/Dockerfile
  locksmith/package.json
  package.json
  paywall/package.json
  rover/Dockerfile
  rover/package.json
  smart-contracts/package.json
  tests/package.json
  tickets/package.json
  unlock-app/package.json
  unlock-js/package.json
  unlock-protocol.com/package.json
  unlock-protocol.com/scripts/build-blog.js
  unlock-protocol.com/scripts/build-rss.js
  unlock-protocol.com/src/__tests__/utils/blog.test.js
  unlock-protocol.com/src/static/blog.rss
  unlock-protocol.com/src/utils/blog.js
  wedlocks/package.json
Labels: cla-signed

#5027 refactored keyPurchase to yield a promise with the token id
  unlock-js/src/__tests__/v0/purchaseKey.test.js
  unlock-js/src/__tests__/v01/purchaseKey.test.js
  unlock-js/src/__tests__/v02/purchaseKey.test.js
  unlock-js/src/__tests__/v10/purchaseKey.test.js
  unlock-js/src/__tests__/v11/purchaseKey.test.js
  unlock-js/src/v0/purchaseKey.js
  unlock-js/src/v01/purchaseKey.js
  unlock-js/src/v02/purchaseKey.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/walletService.js
Labels: cla-signed

#5034 Add file-saver and types
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5029 Add a modal for QR codes
  unlock-app/src/__tests__/actions/fullScreenModals.test.ts
  unlock-app/src/__tests__/components/interface/ModalTemplates.test.tsx
  unlock-app/src/__tests__/reducers/fullScreenModalsReducer.test.ts
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/actions/fullScreenModals.ts
  unlock-app/src/components/interface/FullScreenModals.tsx
  unlock-app/src/components/interface/modal-templates/QRDisplay.tsx
  unlock-app/src/components/interface/modal-templates/index.ts
  unlock-app/src/components/interface/modal-templates/styles.ts
  unlock-app/src/reducers/fullScreenModalsReducer.ts
  unlock-app/src/stories/interface/FullScreenModals.stories.js
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#5038 Revert "Unlock app handles messages for unlock provider web3 calls (#…
  unlock-app/src/__tests__/actions/web3call.test.ts
  unlock-app/src/__tests__/middlewares/postOfficeMiddleware.test.ts
  unlock-app/src/__tests__/middlewares/providerMiddleware.test.ts
  unlock-app/src/__tests__/services/postOfficeService.test.ts
  unlock-app/src/actions/web3call.ts
  unlock-app/src/messageTypes.ts
  unlock-app/src/middlewares/postOfficeMiddleware.ts
  unlock-app/src/middlewares/providerMiddleware.ts
  unlock-app/src/services/postOfficeService.ts
  unlock-app/src/windowTypes.ts
Labels: cla-signed

#5041 Removes outdated video from Readme
  README.md
Labels: cla-signed

#3654 Hang on to account info when receiving SET_ACCOUNT, etc
  unlock-app/src/__tests__/reducers/privateKeyReducer.test.ts
  unlock-app/src/reducers/privateKeyReducer.ts
Labels: cla-signed

#5043 Add the key icon to the svgs
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/svg/Key.js
  unlock-app/src/components/interface/svg/index.js
  unlock-app/src/static/images/svg/key.svg
Labels: cla-signed

#5042 Make sure to store encrypted key after user signs up
  unlock-app/src/__tests__/middlewares/storageMiddleware.test.js
  unlock-app/src/middlewares/storageMiddleware.js
Labels: cla-signed

#5024 Display QR code per-key on keychain
  unlock-app/src/__tests__/components/interface/keyChain/KeyDetails.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/KeyChainContent.js
  unlock-app/src/components/content/KeyChainContent.tsx
  unlock-app/src/components/interface/keyChain/KeyDetails.tsx
Labels: cla-signed

#5049 update to 0.3.19 in all apps
  locksmith/package-lock.json
  locksmith/package.json
  paywall/package-lock.json
  paywall/package.json
  tickets/package-lock.json
  tickets/package.json
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5048 personal_sign just returns the signature for consistency
  unlock-js/CHANGELOG.md
  unlock-js/package.json
  unlock-js/src/__tests__/unlockProvider.test.js
  unlock-js/src/unlockProvider.js
Labels: cla-signed

#5051 KeyChain message for no keys updated to match figma
  unlock-app/src/__tests__/components/interface/keyChain/KeyDetails.test.tsx
  unlock-app/src/components/interface/keyChain/KeyDetails.tsx
  unlock-app/src/static/images/illustrations/key.svg
Labels: cla-signed

#5039 Frontend component for account ejection
  unlock-app/src/__tests__/components/interface/user-account/EjectAccount.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/SettingsContent.tsx
  unlock-app/src/components/interface/svg/Attention.js
  unlock-app/src/components/interface/svg/index.js
  unlock-app/src/components/interface/user-account/EjectAccount.tsx
  unlock-app/src/components/interface/user-account/styles.tsx
  unlock-app/src/static/images/svg/attention.svg
  unlock-app/src/stories/interface/UserAccount.stories.js
  unlock-app/src/theme/globalStyle.js
Labels: cla-signed

#5050 Adding blog post about tokenized memberships
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/tokenizing-memberships.md
  unlock-protocol.com/src/static/blog.rss
  unlock-protocol.com/src/static/images/blog/tokenized-memberships.jpg
Labels: cla-signed

#5047 Removing video from readme of unlock-app
  unlock-app/README.md
Labels: cla-signed

#5054 fixed snapshots
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
Labels: cla-signed

#5052 Partitioning user provided metadata between public and protected
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/__tests__/operations/userMetadataOperations.test.ts
  locksmith/src/operations/userMetadataOperations.ts
Labels: cla-signed

#5058 Update unlock-js to 0.3.20
  locksmith/package-lock.json
  locksmith/package.json
  paywall/package-lock.json
  paywall/package.json
  tickets/package-lock.json
  tickets/package.json
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5062 Stub verification page
  unlock-app/src/__tests__/components/content/VerificationContent.test.tsx
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/pages/verification.js
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#5063 Add template for key ownership email
  wedlocks/src/__tests__/templates/keyOwnership.test.js
  wedlocks/src/templates/keyOwnership.js
Labels: cla-signed

#5065 adding ethers as it is required to use ens resolution
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5064 Add key ownership template to index
  wedlocks/src/templates/index.js
Labels: cla-signed

#5066 WedlockService can send QR code emails
  unlock-app/src/__tests__/services/wedlockService.test.js
  unlock-app/src/services/wedlockService.ts
Labels: cla-signed

#5067 all addresses use the same component
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/creator/CreatorLock.js
  unlock-app/src/components/creator/LockStyles.js
  unlock-app/src/components/creator/lock/KeyList.js
  unlock-app/src/components/interface/Account.tsx
  unlock-app/src/components/interface/Address.tsx
Labels: cla-signed

#5068 Adding ability to refund outside of a Lock for local development
  docker/development/ExternalRefund.json
  docker/development/deploy-external-refund.js
  docker/development/deploy-unlock.js
  docker/development/ganache.dockerfile
Labels: cla-signed

#5070 Add InlineModal component
  unlock-app/src/__tests__/components/interface/InlineModal.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/InlineModal.tsx
  unlock-app/src/stories/interface/InlineModal.stories.js
Labels: cla-signed

#5071 Adding dependencies to test hooks
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5073 Update storyshots
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
Labels: cla-signed

#5077 Add test for unique tokenIds
  smart-contracts/test/Lock/erc721/uniqueTokenIds.js
Labels: cla-signed

#5078 Fix comment in _assignNewTokenId
  smart-contracts/contracts/mixins/MixinKeys.sol
Labels: cla-signed

#5072 Reverse resolving ENS domains when displaying addresses
  unlock-app/package-lock.json
  unlock-app/package.json
  unlock-app/src/__tests__/hooks/useEns.test.js
  unlock-app/src/components/interface/Address.tsx
  unlock-app/src/hooks/useEns.js
Labels: cla-signed

#5031 Create Lock clone using `create2`
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/CloneFactory.sol
  smart-contracts/test/Lock/createLockWithInfiniteKeys.js
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Unlock/behaviors/createLock.js
  smart-contracts/test/Unlock/createLockClone2.js
  smart-contracts/test/Unlock/gas.js
  smart-contracts/test/Unlock/uniswapValue.js
  smart-contracts/test/Unlock/upgrades/v0ToLatest.js
  smart-contracts/test/Unlock/upgrades/v1ToLatest.js
  smart-contracts/test/Unlock/upgrades/v2ToLatest.js
  smart-contracts/test/Unlock/upgrades/v3ToLatest.js
  smart-contracts/test/Unlock/upgrades/v4ToLatest.js
  smart-contracts/test/Unlock/upgrades/v5ToLatest.js
  smart-contracts/test/helpers/deployLocks.js
Labels: cla-signed, smart contract

#5080 Wedlocks middleware handles QR_EMAIL action
  unlock-app/src/__tests__/actions/user.test.ts
  unlock-app/src/__tests__/middlewares/wedlocksMiddleware.test.ts
  unlock-app/src/actions/user.ts
  unlock-app/src/middlewares/wedlocksMiddleware.ts
Labels: cla-signed

#5075 Add QR modal based on InlineModal
  unlock-app/src/__tests__/components/interface/keyChain/QRModal.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/keyChain/QRModal.tsx
  unlock-app/src/components/interface/modal-templates/styles.ts
  unlock-app/src/stories/interface/InlineModal.stories.js
Labels: cla-signed

#5081 Don't prompt for signature on newEvent
  tickets/src/__tests__/middlewares/walletMiddleware.test.js
  tickets/src/middlewares/walletMiddleware.js
Labels: cla-signed

#5083 Introducing shim to exclude protected fields from requests
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/operations/metadataOperations.ts
  locksmith/src/operations/userMetadataOperations.ts
Labels: cla-signed

#5087 Adds evaluation method to middleware
  locksmith/__tests__/signatureValidationMiddleware.test.ts
  locksmith/src/middlewares/signatureValidationMiddleware.ts
Labels: cla-signed

#5085 Using the new QR modal on the keychain
  unlock-app/src/__tests__/components/interface/keyChain/Key.test.tsx
  unlock-app/src/__tests__/components/interface/keyChain/KeyDetails.test.tsx
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/KeyChainContent.tsx
  unlock-app/src/components/interface/keyChain/Key.tsx
  unlock-app/src/components/interface/keyChain/KeyDetails.tsx
  unlock-app/src/components/interface/keyChain/KeychainTypes.ts
  unlock-app/src/stories/keyChain/keyChain.stories.js
Labels: cla-signed

#5089 Add QR svg icon
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/interface/svg/About.js
  tickets/src/components/interface/svg/AppStore.js
  tickets/src/components/interface/svg/Arrow.js
  tickets/src/components/interface/svg/Checkmark.js
  tickets/src/components/interface/svg/ChevronUp.js
  tickets/src/components/interface/svg/Close.js
  tickets/src/components/interface/svg/Code.js
  tickets/src/components/interface/svg/Copy.js
  tickets/src/components/interface/svg/Download.js
  tickets/src/components/interface/svg/Edit.js
  tickets/src/components/interface/svg/Email.js
  tickets/src/components/interface/svg/Etherscan.js
  tickets/src/components/interface/svg/Export.js
  tickets/src/components/interface/svg/Github.js
  tickets/src/components/interface/svg/Hamburger.js
  tickets/src/components/interface/svg/Home.js
  tickets/src/components/interface/svg/Jobs.js
  tickets/src/components/interface/svg/KeyText.js
  tickets/src/components/interface/svg/LockClosed.js
  tickets/src/components/interface/svg/LockOpen.js
  tickets/src/components/interface/svg/Log.js
  tickets/src/components/interface/svg/Preview.js
  tickets/src/components/interface/svg/Qr.js
  tickets/src/components/interface/svg/Telegram.js
  tickets/src/components/interface/svg/Twitter.js
  tickets/src/components/interface/svg/Unlock.js
  tickets/src/components/interface/svg/UnlockWordMark.js
  tickets/src/components/interface/svg/Upload.js
  tickets/src/components/interface/svg/Withdraw.js
  tickets/src/components/interface/svg/index.js
  tickets/src/static/images/svg/qr.svg
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/interface/svg/Qr.js
  unlock-app/src/components/interface/svg/index.js
  unlock-app/src/static/images/svg/qr.svg
Labels: cla-signed

#5088 Remove QR from NewEventContent and link to Keychain
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/content/NewEventContent.tsx
  tickets/src/components/interface/PurchaseSuccess.tsx
Labels: cla-signed

#5082 adding keyPurchase to walletService integration tests
  .circleci/config.yml
  unlock-js/package.json
  unlock-js/src/__tests__/helpers/fixtures/locks.js
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/web3Service.js
Labels: cla-signed

#5092 When presented with a signature proving lock ownership expose protected information
  locksmith/__tests__/controllers/metadataController.test.ts
  locksmith/src/controllers/metadataController.ts
  locksmith/src/routes/metadata.ts
Labels: cla-signed

#5095 Use environment variables in tickets for app and static
  tickets/next.config.js
  tickets/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  tickets/src/components/content/CreateContent.js
  tickets/src/config.js
Labels: cla-signed

#5096 Add eth-sig-util so we can verify signatures on QRs
  unlock-app/package-lock.json
  unlock-app/package.json
Labels: cla-signed

#5099 A more full-featured verification page
  unlock-app/src/__tests__/components/content/VerificationContent.test.tsx
  unlock-app/src/__tests__/components/interface/VerificationStatus.test.tsx
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
Labels: cla-signed

#5098 not catching errors anymore when sending transactions
  unlock-js/CHANGELOG.md
  unlock-js/package.json
  unlock-js/src/__tests__/helpers/walletServiceHelper.js
  unlock-js/src/__tests__/v0/createLock.test.js
  unlock-js/src/__tests__/v0/purchaseKey.test.js
  unlock-js/src/__tests__/v0/updateKeyPrice.test.js
  unlock-js/src/__tests__/v0/withdrawFromLock.test.js
  unlock-js/src/__tests__/v01/createLock.test.js
  unlock-js/src/__tests__/v01/purchaseKey.test.js
  unlock-js/src/__tests__/v01/updateKeyPrice.test.js
  unlock-js/src/__tests__/v01/withdrawFromLock.test.js
  unlock-js/src/__tests__/v02/createLock.test.js
  unlock-js/src/__tests__/v02/purchaseKey.test.js
  unlock-js/src/__tests__/v02/updateKeyPrice.test.js
  unlock-js/src/__tests__/v02/withdrawFromLock.test.js
  unlock-js/src/__tests__/v10/createLock.test.js
  unlock-js/src/__tests__/v10/purchaseKey.test.js
  unlock-js/src/__tests__/v10/updateKeyPrice.test.js
  unlock-js/src/__tests__/v10/withdrawFromLock.test.js
  unlock-js/src/__tests__/v11/createLock.test.js
  unlock-js/src/__tests__/v11/purchaseKey.test.js
  unlock-js/src/__tests__/v11/updateKeyPrice.test.js
  unlock-js/src/__tests__/v11/withdrawFromLock.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v0/purchaseKey.js
  unlock-js/src/v0/updateKeyPrice.js
  unlock-js/src/v0/withdrawFromLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v01/purchaseKey.js
  unlock-js/src/v01/updateKeyPrice.js
  unlock-js/src/v01/withdrawFromLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v02/purchaseKey.js
  unlock-js/src/v02/updateKeyPrice.js
  unlock-js/src/v02/withdrawFromLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v10/updateKeyPrice.js
  unlock-js/src/v10/withdrawFromLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/v11/updateKeyPrice.js
  unlock-js/src/v11/withdrawFromLock.js
Labels: cla-signed

#5086 Adding the PublicLock interface
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/interfaces/IPublicLock.sol
Labels: cla-signed

#5097 withdraw now yields the withdrawn amount
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/__tests__/v0/withdrawFromLock.test.js
  unlock-js/src/__tests__/v01/withdrawFromLock.test.js
  unlock-js/src/__tests__/v02/withdrawFromLock.test.js
  unlock-js/src/__tests__/v10/withdrawFromLock.test.js
  unlock-js/src/__tests__/v11/withdrawFromLock.test.js
  unlock-js/src/v0/withdrawFromLock.js
  unlock-js/src/v01/withdrawFromLock.js
  unlock-js/src/v02/withdrawFromLock.js
  unlock-js/src/v10/withdrawFromLock.js
  unlock-js/src/v11/withdrawFromLock.js
  unlock-js/src/walletService.js
Labels: cla-signed

#5102 Add a query to get locks by owner from the graph
  unlock-app/src/queries/locksByOwner.js
Labels: cla-signed

#5101 Add comment to graph usage in VerificationStatus
  unlock-app/src/components/interface/VerificationStatus.tsx
Labels: cla-signed

#5117 Show QR immediately on signing
  unlock-app/src/__tests__/components/interface/keyChain/Key.test.tsx
  unlock-app/src/components/interface/keyChain/Key.tsx
Labels: cla-signed

#5118 Add message to existing tickets verification page for NewEvent QRs
  tickets/src/__tests__/components/content/EventVerify.test.js
  tickets/src/__tests__/utils/routes.test.js
  tickets/src/components/content/EventVerify.js
  tickets/src/constants.ts
  tickets/src/utils/routes.js
Labels: cla-signed

#5116 adding callbacks to transactions
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  unlock-js/src/v0/createLock.js
  unlock-js/src/v0/purchaseKey.js
  unlock-js/src/v0/updateKeyPrice.js
  unlock-js/src/v0/withdrawFromLock.js
  unlock-js/src/v01/createLock.js
  unlock-js/src/v01/purchaseKey.js
  unlock-js/src/v01/updateKeyPrice.js
  unlock-js/src/v01/withdrawFromLock.js
  unlock-js/src/v02/createLock.js
  unlock-js/src/v02/purchaseKey.js
  unlock-js/src/v02/updateKeyPrice.js
  unlock-js/src/v02/withdrawFromLock.js
  unlock-js/src/v10/createLock.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v10/updateKeyPrice.js
  unlock-js/src/v10/withdrawFromLock.js
  unlock-js/src/v11/createLock.js
  unlock-js/src/v11/purchaseKey.js
  unlock-js/src/v11/updateKeyPrice.js
  unlock-js/src/v11/withdrawFromLock.js
  unlock-js/src/walletService.js
Labels: cla-signed

#5112 Default to login on the Keychain page
  unlock-app/src/__tests__/storybook/__snapshots__/storyshots.test.js.snap
  unlock-app/src/components/content/KeyChainContent.tsx
Labels: cla-signed

#5115 Get refund contract address from environment variable
  unlock-app/next.config.js
  unlock-app/src/config.js
Labels: cla-signed

#5120 replacing managedPurchaseStablecoinAddress with the previously existing erc20ContractAddress
  paywall/src/__tests__/unlock.js/CheckoutUIHandler.test.ts
  paywall/src/__tests__/unlock.js/Wallet/enableCryptoWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/init.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccounts.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
  paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
  paywall/src/__tests__/unlock.js/startup.test.ts
  paywall/src/unlock.js/CheckoutUIHandler.ts
  paywall/src/unlock.js/constants.ts
  paywall/src/unlock.js/startupTypes.ts
Labels: cla-signed

#5119 not requiring the user to approve the lock on their erc20 if the approval amount is large enough
  unlock-js/CHANGELOG.md
  unlock-js/src/__tests__/v10/purchaseKey.test.js
  unlock-js/src/__tests__/v11/purchaseKey.test.js
  unlock-js/src/erc20.js
  unlock-js/src/v10/purchaseKey.js
  unlock-js/src/v11/purchaseKey.js
Labels: cla-signed

#5121 Adding Ethereum name service post
  unlock-protocol.com/blog/blog.index
  unlock-protocol.com/blog/ethereum-name-service.md
  unlock-protocol.com/src/static/blog.rss
  unlock-protocol.com/src/static/images/blog/ethereum-name-service/ens-enabled.png
  unlock-protocol.com/src/static/images/blog/ethereum-name-service/ethereum-name-service.png
Labels: cla-signed

#5123 bumping to version 0.4.0
  unlock-js/CHANGELOG.md
  unlock-js/package.json
Labels: cla-signed

#5124 updating unlockjs in the paywall
  paywall/package-lock.json
  paywall/package.json
  paywall/src/__tests__/data-iframe/blockchainHandler/BlockchainHandler/purchaseKey.test.ts
  paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts
  paywall/src/data-iframe/blockchainHandler/blockChainTypes.ts
Labels: cla-signed
