Repository unlock-protocol/unlock, pull requests merged in 2021-12, with the labels that each got.

#7830 Production Deploy
  packages/networks/src/networks/bsc.ts
  packages/networks/src/networks/polygon.ts
  packages/networks/src/networks/xdai.ts
  smart-contracts/.openzeppelin/unknown-100.json
  smart-contracts/.openzeppelin/unknown-137.json
  smart-contracts/.openzeppelin/unknown-56.json
  subgraph/subgraph.template.yaml
Labels: cla-signed

#7831 adding a fix for the unlock provider
  unlock-app/src/components/interface/LoginPrompt.tsx
  unlock-app/src/hooks/useAuthenticateHandler.ts
  unlock-app/src/hooks/useAutoLogin.ts
Labels: cla-signed

#7874 Production Deploy
  unlock-app/src/components/interface/LoginPrompt.tsx
  unlock-app/src/hooks/useAuthenticateHandler.ts
  unlock-app/src/hooks/useAutoLogin.ts
Labels: cla-signed

#7876 Revert auto login as it breaks the checkout flow
  unlock-app/src/components/content/CheckoutContent.tsx
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/components/interface/LoginPrompt.tsx
  unlock-app/src/components/interface/buttons/AuthenticateButton.js
  unlock-app/src/hooks/useAppStorage.ts
  unlock-app/src/hooks/useAuthenticate.ts
  unlock-app/src/hooks/useAuthenticateHandler.ts
  unlock-app/src/hooks/useAutoLogin.ts
  unlock-app/src/hooks/useProvider.ts
Labels: cla-signed

#7877 Production Deploy
  unlock-app/src/components/content/CheckoutContent.tsx
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/components/interface/LoginPrompt.tsx
  unlock-app/src/components/interface/buttons/AuthenticateButton.js
  unlock-app/src/hooks/useAppStorage.ts
  unlock-app/src/hooks/useAuthenticate.ts
  unlock-app/src/hooks/useAuthenticateHandler.ts
  unlock-app/src/hooks/useAutoLogin.ts
  unlock-app/src/hooks/useProvider.ts
Labels: cla-signed

#7875 adding retroactive funding blog post
  unlock-protocol-com/blog/retroactive-funding.md
Labels: cla-signed

#7879 Ignore accounts files for specific networks
  smart-contracts/.gitignore
Labels: cla-signed

#7883 Renovate minor and patch updates - eslint fix
  Dockerfile
  docker/development/eth-node/package.json
  docker/development/eth-node/yarn.lock
  docker/docker-compose.yml
  locksmith/.eslintrc.js
  newsletter/package.json
  package.json
  packages/contracts/package.json
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/networks/package.json
  packages/paywall-config/test.html
  packages/paywall/package.json
  packages/types/package.json
  packages/unlock-assets/package.json
  packages/unlock-express/package.json
  packages/unlock-js/.eslintrc.js
  packages/unlock-js/package.json
  paywall-app/package.json
  unlock-app/.eslintrc.js
  unlock-protocol-com/.eslintrc.js
  unlock-protocol-com/package.json
  yarn.lock
Labels: cla-signed, run-all-tests

#7889 Remove manual copy function due to moving files directly into public
  unlock-app/package.json
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#7888 fix(README): Fix path to unlock-word-icon
  README.es.md
  README.md
Labels: cla-signed

#7890 mintgate case study blog post
  unlock-protocol-com/blog/mintgate-unlock-case-study.md
  unlock-protocol-com/public/images/blog/mintgate-unlock-case-study/homepage-mintgate-150h.png
  unlock-protocol-com/public/images/blog/mintgate-unlock-case-study/mintgate-thumbnail.png
Labels: cla-signed

#7893 thedefiant case study
  unlock-protocol-com/blog/thedefiant-case-study.md
  unlock-protocol-com/public/images/blog/thedefiant-case-study/homepage-thedefiant-150h.png
  unlock-protocol-com/public/images/blog/thedefiant-case-study/thedefiant-thumbnail.png
Labels: cla-signed

#7821 Serialize and duplicate a Lock
  packages/contracts/README.md
  packages/contracts/package.json
  packages/contracts/src/abis/utils/LockSerializer.json
  packages/contracts/src/contracts/PublicLock/IPublicLockV8sol8.sol
  packages/contracts/src/contracts/utils/LockSerializer.sol
  packages/networks/package.json
  packages/networks/src/networks/rinkeby.ts
  packages/types/package.json
  packages/types/src/types/unlockTypes.ts
  packages/unlock-js/package.json
  smart-contract-extensions/package.json
  smart-contracts/README.md
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/utils/LockSerializer.sol
  smart-contracts/hardhat.config.js
  smart-contracts/package.json
  smart-contracts/scripts/deployments/index.js
  smart-contracts/scripts/deployments/lock.js
  smart-contracts/scripts/deployments/serializer.js
  smart-contracts/scripts/deployments/unlock.js
  smart-contracts/scripts/lock/clone.js
  smart-contracts/scripts/lock/listManagers.js
  smart-contracts/scripts/lock/samples.js
  smart-contracts/scripts/lock/serialize.js
  smart-contracts/scripts/setters/set-template.js
  smart-contracts/tasks/deploy.js
  smart-contracts/tasks/lock.js
  smart-contracts/tasks/set.js
  smart-contracts/test/LockSerializer/_compareValues.js
  smart-contracts/test/LockSerializer/serialize.js
  smart-contracts/test/scripts/deploy/lock.js
  yarn.lock
Labels: cla-signed

#7897 link doesnt point to the right place
  unlock-app/src/components/content/DashboardContent.js
Labels: cla-signed

#7896 Ccarfi add casestudies to home page
  unlock-protocol-com/public/images/blog/mintgate-unlock-case-study/homepage-mintgate-150h.png
  unlock-protocol-com/src/components/content/HomeContent.js
Labels: cla-signed

#7895 LockSerializer packaging
  packages/contracts/src/abis/utils/LockSerializer.json
  packages/contracts/src/contracts/utils/LockSerializer.sol
  packages/contracts/src/index.ts
  packages/contracts/src/utils/parser.ts
  packages/networks/src/networks/polygon.ts
  packages/networks/src/networks/rinkeby.ts
  packages/networks/src/networks/xdai.ts
  smart-contracts/.gitignore
Labels: cla-signed

#7903 adding optimism blog post
  unlock-protocol-com/blog/optimism.md
  unlock-protocol-com/public/images/blog/optimism.png
Labels: cla-signed

#7901 Renovate npm next vulnerability fix
  newsletter/.eslintrc.js
  newsletter/package.json
  newsletter/pages/_document.jsx
  unlock-app/package.json
  yarn.lock
Labels: cla-signed

#7906 Content Rooms blog post
  unlock-protocol-com/blog/contentrooms.md
  unlock-protocol-com/public/images/blog/contentrooms-logo-510.png
Labels: cla-signed

#7909 Update contentrooms.md
  unlock-protocol-com/blog/contentrooms.md
Labels: cla-signed

#7796 Gas refund on purchase
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/purchaseGasRefund.js
Labels: cla-signed

#7882 Locksmith route to migrate lock
  locksmith/jest.config.js
  locksmith/migrations/20211202121847-create-lock-migrations.js
  locksmith/package.json
  locksmith/src/controllers/lockController.js
  locksmith/src/models/index.ts
  locksmith/src/models/lockMigrations.ts
  locksmith/src/operations/lockOperations.ts
  locksmith/src/routes/lock.ts
  locksmith/src/utils/lockManagers.ts
  locksmith/src/utils/lockMigrate.ts
  locksmith/tsconfig.json
  packages/contracts/src/abis/utils/LockSerializer.json
  packages/contracts/src/utils/parser.ts
  packages/networks/src/networks/localhost.ts
  smart-contracts/README.md
  yarn.lock
Labels: cla-signed

#7912 WordPress plugin blog post
  unlock-protocol-com/blog/unlock-protocol-wordpress-plugin.md
  unlock-protocol-com/blog/wordpress-plugin.md
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-admin-button-colors-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-admin-image-content-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-admin-networks-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-block-menu-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-image-block-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-locked-content-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-log-in-with-crypto-wallet-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-member-content-min.png
  unlock-protocol-com/public/images/blog/unlock-wordpress-plugin/unlock-wp-unlock-block-min.png
Labels: cla-signed

#7902 Lock migration UI
  packages/eslint-config/index.js
  packages/unlock-js/src/v4/getLock.js
  packages/unlock-js/src/v6/getLock.js
  packages/unlock-js/src/v7/getLock.js
  paywall-app/.eslintrc.js
  paywall-app/package.json
  unlock-app/.gitignore
  unlock-app/jest.config.js
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/components/content/CloneContent.tsx
  unlock-app/src/components/creator/CreatorLock.js
  unlock-app/src/components/creator/lock/LockIconBar.js
  unlock-app/src/pages/clone.js
  unlock-app/src/utils/exportStatic.js
  unlock-app/tsconfig.json
  unlock-app/tsconfig.test.json
  unlock-protocol-com/package.json
  yarn.lock
Labels: cla-signed

#7920 fixed link
  unlock-app/src/components/content/CloneContent.tsx
  unlock-app/src/components/creator/CreatorLock.js
Labels: cla-signed

#7915 Set max number of keys
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/setMaxNumberOfKeys.js
Labels: cla-signed

#7921 Fix lock migration
  locksmith/src/utils/lockMigrate.ts
  packages/networks/src/networks/polygon.ts
  unlock-app/src/components/content/CloneContent.tsx
Labels: cla-signed

#7922 adding support for eip1559
  packages/unlock-js/src/v6/purchaseKey.js
  packages/unlock-js/src/v7/purchaseKey.js
  packages/unlock-js/src/v8/purchaseKey.js
Labels: cla-signed

#7925 add mintgate video
  unlock-protocol-com/blog/mintgate-unlock-case-study.md
Labels: cla-signed

#7926 Ccarfi chroma signet blog post
  unlock-protocol-com/blog/chroma-signet-case-study.md
  unlock-protocol-com/public/images/blog/chroma-signet-unlock-case-study/chroma-signet-150h.png
  unlock-protocol-com/public/images/blog/chroma-signet-unlock-case-study/chroma-signet-thumbnail.png
Labels: cla-signed

#7929 disabling auto login for the checkout page
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/pages/_app.js
  unlock-app/src/pages/checkout.js
Labels: cla-signed

#7930 Production Deploy
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/pages/_app.js
  unlock-app/src/pages/checkout.js
  unlock-protocol-com/blog/chroma-signet-case-study.md
  unlock-protocol-com/blog/mintgate-unlock-case-study.md
  unlock-protocol-com/public/images/blog/chroma-signet-unlock-case-study/chroma-signet-150h.png
  unlock-protocol-com/public/images/blog/chroma-signet-unlock-case-study/chroma-signet-thumbnail.png
Labels: cla-signed

#7931 Cohort 5 blog post
  unlock-protocol-com/blog/cohort-5-grantees.md
  unlock-protocol-com/public/images/blog/cohort-5/cohort-5.png
Labels: cla-signed

#7914 Try/catch on Unlock callbacks
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/purchaseWithoutUnlock.js
Labels: smart contract, cla-signed, v9

#7932 Lock: add method to update expiration duration
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/setExpirationDuration.js
Labels: smart contract, cla-signed, v9

#7935 Fix mistake in time machine test
  smart-contracts/test/Lock/timeMachine.js
Labels: smart contract, cla-signed

#7933 fixing close button on checkout modal
  unlock-app/src/components/interface/checkout/Checkout.tsx
  unlock-app/src/components/interface/checkout/EnjoyYourMembership.tsx
Labels: cla-signed

#7936 web3jam blog post
  unlock-protocol-com/blog/web3jam.md
  unlock-protocol-com/public/images/blog/web3jam/temp.md
  unlock-protocol-com/public/images/blog/web3jam/web3jam-card.png
Labels: cla-signed

#7797 Add key manager to lock purchase
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/approveBeneficiary.js
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/disableLock.js
  smart-contracts/test/Lock/disableTransfers.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/approveForAll.js
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/erc721/enumerable.js
  smart-contracts/test/Lock/erc721/getTokenIdFor.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/tokenURI.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/erc721/uniqueTokenIds.js
  smart-contracts/test/Lock/expireAndRefundFor.js
  smart-contracts/test/Lock/freeTrial.js
  smart-contracts/test/Lock/gas.js
  smart-contracts/test/Lock/getHasValidKey.js
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeyPurchaseHook.js
  smart-contracts/test/Lock/onTokenURIHook.js
  smart-contracts/test/Lock/onValidKeyHook.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/permissions/isKeyManager.js
  smart-contracts/test/Lock/permissions/keyManager.js
  smart-contracts/test/Lock/permissions/setKeyManager.js
  smart-contracts/test/Lock/purchaseFor.js
  smart-contracts/test/Lock/purchaseForFrom.js
  smart-contracts/test/Lock/purchaseGasRefund.js
  smart-contracts/test/Lock/purchaseTip.js
  smart-contracts/test/Lock/purchaseWithoutUnlock.js
  smart-contracts/test/Lock/setExpirationDuration.js
  smart-contracts/test/Lock/setMaxNumberOfKeys.js
  smart-contracts/test/Lock/shareKey.js
  smart-contracts/test/Lock/timeMachine.js
  smart-contracts/test/Lock/transfer.js
  smart-contracts/test/Lock/transferFee.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/LockSerializer/serialize.js
  smart-contracts/test/Unlock/lockTotalSales.js
  smart-contracts/test/Unlock/resetTrackedValue.js
  smart-contracts/test/Unlock/uniswapValue.js
  smart-contracts/test/Unlock/upgrades.js
  smart-contracts/test/Unlock/upgrades.mainnet.js
  smart-contracts/test/UnlockDiscountToken/mintingTokens.js
  smart-contracts/test/UnlockDiscountToken/transferingTokens.js
  smart-contracts/test/UnlockDiscountToken/upgrades.js
Labels: smart contract, cla-signed, v9

#7886 feat: Add fleek deployment
  .github/disabled-workflows/_fleek.yml
  .github/disabled-workflows/deploy.yml
  newsletter/.fleek.json
  newsletter/package.json
  newsletter/scripts/deploy-fleek.sh
  paywall-app/.fleek.json
  paywall-app/package.json
  paywall-app/scripts/deploy-fleek.sh
  unlock-app/.fleek.json
  unlock-app/package.json
  unlock-app/scripts/deploy-fleek.sh
  unlock-app/tsconfig.json
  unlock-protocol-com/.fleek.json
  unlock-protocol-com/.gitignore
  unlock-protocol-com/package.json
  unlock-protocol-com/scripts/deploy-fleek.sh
  yarn.lock
Labels: cla-signed

#7939 2021 year in review blog post
  unlock-protocol-com/blog/unlock-2021-review.md
  unlock-protocol-com/public/images/blog/unlock-2021-review/5-network-logos.png
  unlock-protocol-com/public/images/blog/unlock-2021-review/creditcard.png
  unlock-protocol-com/public/images/blog/unlock-2021-review/decentraland.png
  unlock-protocol-com/public/images/blog/unlock-2021-review/fireworks-min.jpg
  unlock-protocol-com/public/images/blog/unlock-2021-review/swordybot.png
  unlock-protocol-com/public/images/blog/unlock-2021-review/unlockdao.png
  unlock-protocol-com/public/images/blog/unlock-2021-review/wordpress.jpeg
Labels: cla-signed

#7927 Non expiring memberships
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/nonExpiring.js
  smart-contracts/test/fixtures/locks.js
Labels: smart contract, cla-signed, v9

#7928 Add storage gaps to PublicLock
  smart-contracts/contracts/mixins/MixinDisable.sol
  smart-contracts/contracts/mixins/MixinERC721Enumerable.sol
  smart-contracts/contracts/mixins/MixinFunds.sol
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinLockMetadata.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinRoles.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
Labels: smart contract, cla-signed, v9
