Repository unlock-protocol/unlock, pull requests merged in 2022-10, with the labels that each got.

#9734 fix(locksmith, unlock-js): fixing gas issue on polygon by forcing estimate to be preserved
  locksmith/package.json
  locksmith/src/fulfillment/dispatcher.ts
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/package.json
  packages/unlock-js/src/PublicLock/v10/purchaseKey.js
  packages/unlock-js/src/PublicLock/v10/purchaseKeys.js
  yarn.lock
Labels: cla-signed

#9796 feat(unlock-app) - fix locks by network
  unlock-app/src/components/creator/lock/LocksByNetwork.tsx
Labels: cla-signed

#9805 feat(unlock-app) - change currency from update price modal
  unlock-app/src/components/interface/locks/Manage/modals/UpdatePriceModal.tsx
Labels: cla-signed

#9807 feat()unlock-app - add demo link
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#9806 feat(unlock-app) - replace expire checkbox with toggle switch
  unlock-app/src/components/interface/members/airdrop/AirdropManualForm.tsx
Labels: cla-signed

#9810 feat(unlock-app) - link to blockscan
  unlock-app/src/components/interface/locks/Manage/elements/MetadataCard.tsx
Labels: cla-signed

#9811 fix(unlock-app): Show error on transaction failure
  unlock-app/next.config.js
  unlock-app/src/components/interface/checkout/ClaimMembershipCheckout.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/hooks/useAccount.ts
Labels: cla-signed

#9814 feat(unlock-app): Add link to keychain on the mint and renewed page
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Renewed.tsx
Labels: cla-signed

#9798 fix(smart-contracts): check if a token exists by checking its tokenId
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/isValidKey.js
Labels: cla-signed, publicLock v12

#9815 remove(unlock-app): Remove old grant keys form
  unlock-app/src/components/creator/members/GrantKeysDrawer.tsx
Labels: cla-signed

#9724 feat(subgraph): add total keys property
  docker/development/subgraph/startup.sh
  subgraph/schema.graphql
  subgraph/src/public-lock.ts
  subgraph/src/unlock.ts
  subgraph/tests/keys.test.ts
  subgraph/tests/locks.test.ts
  tests/test/helpers/fixtures.ts
  tests/test/helpers/keys.ts
  tests/test/helpers/subgraph.ts
  tests/test/subgraph.ts
Labels: cla-signed

#9822 feat(unlock-app) - enable recurring
  unlock-app/src/components/interface/locks/Manage/elements/EnableRecurring.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
Labels: cla-signed

#9816 feature(wedlocks): refactored templates processing for better image extraction
  wedlocks/config-builder.js
  wedlocks/src/__tests__/route.test.js
  wedlocks/src/__tests__/templates/confirmEmail.test.js
  wedlocks/src/__tests__/templates/index.test.js
  wedlocks/src/__tests__/templates/keyMined.test.js
  wedlocks/src/__tests__/templates/keyOwnership.test.js
  wedlocks/src/__tests__/templates/welcome.test.js
  wedlocks/src/functions/handler/handler.js
  wedlocks/src/route.js
  wedlocks/src/templates/base/index.js
  wedlocks/src/templates/confirmEmail.js
  wedlocks/src/templates/debug.js
  wedlocks/src/templates/index.js
  wedlocks/src/templates/keyMined.js
  wedlocks/src/templates/keyOwnership.js
  wedlocks/src/templates/locks/index.js
  wedlocks/src/templates/prepare.js
  wedlocks/src/templates/welcome.js
  wedlocks/src/wrap.js
Labels: cla-signed

#9817 wedlocks(feature): La Degen templates
  wedlocks/src/templates/locks/index.js
  wedlocks/src/templates/locks/keyMined-0x0Da7C68203a9331baEB388BC7e17430F188E4061.js
  wedlocks/src/templates/locks/keyMined-0x5f1c54dEDE0d96F49EEd8F57f653b24d41f4BDd6.js
  wedlocks/src/templates/locks/keyMined-0x838327F343382526e10E14ef6E9F588E69B37230.js
  wedlocks/static/attachments/bomdia.png
  wedlocks/static/attachments/ladegen.png
  wedlocks/static/attachments/postcard-degen.png
  wedlocks/static/attachments/postcard-vip.png
Labels: cla-signed

#9823 fix(wedlocks): install netlify cli used for deployments
  wedlocks/package.json
  yarn.lock
Labels: cla-signed

#9825 fix(unlock-app): Respect the count parameter in airdrop form
  unlock-app/src/components/interface/members/airdrop/AirdropBulkForm.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropDrawer.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropManualForm.tsx
Labels: cla-signed

#9812 feat(unlock-app) - force switch network manage lock page
  unlock-app/src/components/interface/locks/Manage/index.tsx
  unlock-app/src/hooks/useProvider.ts
Labels: cla-signed

#9827 chore(actions): run integration tests in parallel with unit tests
  .github/workflows/_tests.yml
Labels: cla-signed

#9828 feat(unlock-app) - fix generated url
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#9803 update stripe links url
  locksmith/src/operations/stripeOperations.ts
Labels: cla-signed

#9802 feat(unlock-app) - update links for new dashboard
  unlock-app/src/__tests__/components/content/DashboardContent.test.js
  unlock-app/src/__tests__/components/interface/Header.test.js
  unlock-app/src/__tests__/pages/pages.test.js
  unlock-app/src/components/content/DashboardContent.jsx
  unlock-app/src/components/content/HomeContent.jsx
  unlock-app/src/components/interface/Header.jsx
  unlock-app/src/components/interface/buttons/ActionButton.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockFormSummary.tsx
  unlock-app/src/components/interface/locks/List/index.tsx
Labels: cla-signed

#9829 feat(unlock-app) - fix form validation
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdateQuantityModal.tsx
Labels: cla-signed

#9832 feat(unlock-app) - pass keyprice as string
  unlock-app/src/components/interface/locks/Create/CreateLock.tsx
Labels: cla-signed

#9826 chore(*): removing support for Rinkeby!
  CONTRIBUTING.md
  README.md
  locksmith/README.md
  locksmith/__tests__/controllers/hookController.test.ts
  locksmith/__tests__/controllers/hubPublisherController.test.ts
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/__tests__/graphql/datasource/key.test.ts
  locksmith/__tests__/graphql/datasource/lock.test.ts
  packages/hardhat-helpers/README.md
  packages/hardhat-helpers/src/etherscan.js
  packages/hardhat-plugin/src/networks.json
  packages/networks/src/networks/index.ts
  packages/networks/src/networks/rinkeby.ts
  packages/unlock-express/index.js
  packages/unlock-js/examples/networks.js
  packages/unlock-js/examples/purchase-key.js
  packages/unlock-js/scripts/deploy-template.js
  provider/src/index.ts
  scripts/production-pull-request-template.sh
  smart-contracts/.openzeppelin/rinkeby.json
  smart-contracts/README.md
  smart-contracts/openzeppelin-cli-export.json
  smart-contracts/scripts/all_networks.sh
  smart-contracts/scripts/deployments/index.js
  smart-contracts/scripts/multisig/_helpers.js
  smart-contracts/scripts/multisig/submitTx.js
  smart-contracts/scripts/upgrade/submitLockVersion.js
  subgraph/networks.json
  unlock-app/src/__tests__/components/creator/CreatorAccount.test.js
  unlock-app/src/utils/supportedErc20.ts
  unlock-protocol-com/blog/create-first-lock.md
  unlock-protocol-com/blog/webflow-integration.md
Labels: cla-signed

#9834 fix(wedlocks): deployment script fixed
  wedlocks/scripts/deploy-netlify.sh
Labels: cla-signed

#9694 fix(subgraph): improve `deploy-all` task
  subgraph/bin/networks.js
  subgraph/bin/thegraph
  subgraph/networks.json
  subgraph/package.json
Labels: cla-signed

#9722 docs(subgraph): instructions to add properties to graph
  subgraph/README.md
Labels: cla-signed

#9837 feature(wedlocks): adding arbitrum hackathon emaila
  wedlocks/src/templates/locks/index.js
  wedlocks/src/templates/locks/keyMined-0xc4bcBaa594843881Fc3957C9104965D0f7cFb1FF.js
Labels: cla-signed

#9836 feature(networks): adding opensea link for optimism
  packages/networks/src/networks/optimism.ts
Labels: cla-signed

#9841 feat(unlock-app) - replace useDebounce hook with react-use one
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/components/interface/locks/Create/modals/SelectCurrencyModal.tsx
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/Members.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
  unlock-app/src/hooks/useDebouce.ts
  unlock-app/src/pages/members.jsx
Labels: cla-signed

#9842 feat(unlock-app) - remove styled-component
  unlock-app/src/components/content/CloneContent.tsx
  unlock-app/src/components/interface/Header.jsx
  unlock-app/src/components/interface/Loading.tsx
  unlock-app/src/components/interface/checkout/Locks.tsx
  unlock-app/src/components/interface/checkout/MultipleRecipients.tsx
  unlock-app/src/components/lock/Icon.jsx
Labels: cla-signed

#9839 Ccarfi sept 22 product update
  unlock-protocol-com/blog/sept-22-update.md
  unlock-protocol-com/public/images/blog/sept-22-update/sept-22-banner.png
Labels: cla-signed

#9845 fix(locksmith): fixing metadata
  locksmith/src/controllers/metadataController.ts
Labels: cla-signed

#9847 feat(unlock-app) - show actions to lock manager
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/TotalBar.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
  unlock-app/src/hooks/useLockManager.ts
Labels: cla-signed

#9821 feat(unlock-app) - delete old dashboard
  unlock-app/jest.config.js
  unlock-app/src/__tests__/components/creator/CreatorLock.test.js
  unlock-app/src/__tests__/components/creator/CreatorLocks.test.js
  unlock-app/src/__tests__/components/creator/lock/Withdraw.test.js
  unlock-app/src/__tests__/components/helpers/Balance.test.js
  unlock-app/src/__tests__/components/helpers/BalanceProvider.test.js
  unlock-app/src/__tests__/components/interface/MetadataTable.test.tsx
  unlock-app/src/components/creator/CreatorLock.jsx
  unlock-app/src/components/creator/CreatorLockForm.jsx
  unlock-app/src/components/creator/CreatorLocks.jsx
  unlock-app/src/components/creator/FatalError.tsx
  unlock-app/src/components/creator/LockStyles.jsx
  unlock-app/src/components/creator/lock/AppStore.jsx
  unlock-app/src/components/creator/lock/CreatorLockStatus.jsx
  unlock-app/src/components/creator/lock/LockIconBar.jsx
  unlock-app/src/components/helpers/Balance.jsx
  unlock-app/src/components/helpers/BalanceProvider.jsx
  unlock-app/src/components/interface/Alert.tsx
  unlock-app/src/components/interface/Errors.tsx
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/components/interface/buttons/ActionButton.tsx
  unlock-app/src/components/interface/buttons/lock/Account.jsx
  unlock-app/src/components/interface/buttons/lock/AppStore.jsx
  unlock-app/src/components/interface/buttons/lock/Code.jsx
  unlock-app/src/components/interface/buttons/lock/Copy.jsx
  unlock-app/src/components/interface/buttons/lock/Demo.jsx
  unlock-app/src/components/interface/buttons/lock/Download.jsx
  unlock-app/src/components/interface/buttons/lock/Edit.jsx
  unlock-app/src/components/interface/buttons/lock/Explorer.jsx
  unlock-app/src/components/interface/buttons/lock/ExportLock.jsx
  unlock-app/src/components/interface/buttons/lock/Members.jsx
  unlock-app/src/components/interface/buttons/lock/Upload.jsx
  unlock-app/src/components/interface/buttons/lock/Verifiers.tsx
  unlock-app/src/components/interface/buttons/lock/Withdraw.jsx
  unlock-app/src/components/interface/buttons/lock/index.jsx
  unlock-app/src/components/interface/checkout/LogInButton.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/components/interface/modal-templates/WalletCheck.tsx
  unlock-app/src/components/interface/modal-templates/index.ts
  unlock-app/src/components/interface/modal-templates/styles.ts
  unlock-app/src/components/interface/user-account/styles.tsx
  unlock-app/src/components/lock/Icon.jsx
  unlock-app/src/theme/media.ts
Labels: cla-signed

#9840 feat(unlock-app) - update dashboard links and page content
  README.md
  unlock-app/src/components/content/DashboardContent.jsx
  unlock-protocol-com/next.config.js
  unlock-protocol-com/src/config/unlock.ts
Labels: cla-signed

#9843 feat(unlock-app) - show loading when user start typing
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
Labels: cla-signed

#9853 feat(unlock-app) - remove styed component
  unlock-app/src/components/creator/FatalError.tsx
  unlock-app/src/components/creator/lock/CreditCardSettings.jsx
  unlock-app/src/components/interface/checkout/Checkout.tsx
  unlock-app/src/components/interface/checkout/CheckoutMethod.tsx
  unlock-app/src/components/interface/checkout/CheckoutStyles.tsx
  unlock-app/src/components/interface/checkout/CryptoCheckout.tsx
  unlock-app/src/components/interface/checkout/FormStyles.tsx
  unlock-app/src/components/interface/checkout/LockVariations.tsx
  unlock-app/src/components/interface/checkout/MetadataForm.tsx
  unlock-app/src/components/interface/checkout/OauthConnect.tsx
  unlock-app/src/components/interface/checkout/SwitchPayment.tsx
Labels: cla-signed

#9819 Gitcoin round 15 blog post
  unlock-protocol-com/blog/gitcoin-round-15.md
  unlock-protocol-com/public/images/blog/gitcoin-round-15.png
Labels: cla-signed

#9799 fix(smart-contracts): pass `tokenId` as param to the `onPurchase` hook
  smart-contracts/contracts/interfaces/hooks/ILockKeyPurchaseHook.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/test-artifacts/TestEventHooks.sol
  smart-contracts/test/Lock/onKeyPurchaseHook.js
Labels: cla-signed, publicLock v12

#9844 feat(unlock-app) - remove styled component
  unlock-app/src/components/content/DemoContent.jsx
Labels: cla-signed

#9800 feat(smart-contracts): add `onKeyExtend` hook
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/interfaces/hooks/ILockKeyExtendHook.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/test-artifacts/TestEventHooks.sol
  smart-contracts/test/Lock/hooks/erc1155BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc20BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc721BalanceOfHook.js
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeyExtendHook.js
  smart-contracts/test/Lock/onKeyPurchaseHook.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/onTokenURIHook.js
  smart-contracts/test/Lock/onValidKeyHook.js
  smart-contracts/test/Lock/purchaseWithoutUnlock.js
  smart-contracts/test/Lock/renewMembershipFor.js
Labels: cla-signed, publicLock v12

#9859 feat(networks): Add v2 subgraph endpoints
  packages/networks/src/networks/arbitrum.ts
  packages/networks/src/networks/avalanche.ts
  packages/networks/src/networks/bsc.ts
  packages/networks/src/networks/celo.ts
  packages/networks/src/networks/goerli.ts
  packages/networks/src/networks/localhost.ts
  packages/networks/src/networks/mainnet.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/src/networks/optimism.ts
  packages/networks/src/networks/polygon.ts
  packages/networks/src/networks/xdai.ts
Labels: cla-signed

#9857 fix(locksmith): Revert "fixing metadata (#9845)"
  locksmith/src/controllers/metadataController.ts
Labels: cla-signed

#9863 fix(wedlocks) fixed arbitrum template
  wedlocks/src/templates/locks/keyMined-0xc4bcBaa594843881Fc3957C9104965D0f7cFb1FF.js
Labels: cla-signed

#9861 feat(unlock-app) - fix lock card component
  unlock-app/src/components/interface/locks/List/elements/LockCard.tsx
Labels: cla-signed

#9862 feat(unlock-app) - add de-authenticate support
  unlock-app/public/images/illustrations/disconnect-wallet.svg
  unlock-app/src/components/interface/AppHeader.tsx
Labels: cla-signed

#9865 feat(unlock-app) - app layout for dashboard pages
  unlock-app/src/components/content/KeychainContent.tsx
  unlock-app/src/components/content/SettingsContent.tsx
  unlock-app/src/components/interface/keychain/KeyDetails.tsx
  unlock-app/src/components/interface/layouts/AppLayout.tsx
  unlock-app/src/components/interface/locks/Create/index.tsx
  unlock-app/src/components/interface/locks/List/index.tsx
  unlock-app/src/pages/locks/create.tsx
  unlock-app/src/pages/locks/index.tsx
  unlock-app/src/pages/locks/lock.tsx
Labels: cla-signed

#9854 feat(provider): Add proxy path for proxifying request
  package.json
  provider/package.json
  provider/src/index.ts
  yarn.lock
Labels: cla-signed

#9856 feat(unlock-app): Support password and captcha for claim
  locksmith/package.json
  locksmith/src/controllers/purchaseController.ts
  locksmith/src/fulfillment/dispatcher.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/useCheckoutItems.ts
  unlock-app/src/hooks/useAccount.ts
  unlock-app/src/hooks/useCards.ts
  yarn.lock
Labels: cla-signed

#9730 feat(checkout): Add a way for users to attach data from their backend for contract purchase
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Renew.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.typegen.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/utils.ts
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#9851 feat(unlock-app) - add download csv
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#9872 feat(unlock-app) - more cleanups
  unlock-app/src/components/creator/FatalError.tsx
  unlock-app/src/components/interface/Address.tsx
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/components/interface/user-account/styles.tsx
Labels: cla-signed

#9871 feat(unlock-app) - show low price credit card
  unlock-app/src/components/creator/ConnectCard.tsx
  unlock-app/src/components/creator/lock/CreditCardSettings.jsx
  unlock-app/src/components/interface/locks/Manage/elements/CardPayment.tsx
Labels: cla-signed

#9855 chore(unlock-app): Update react-query to @tanstack/react-query
  unlock-app/package.json
  unlock-app/src/components/content/SettingsContent.tsx
  unlock-app/src/components/creator/lock/LocksByNetwork.tsx
  unlock-app/src/components/creator/members/ExtendKeysDrawer.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/CardPayment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Payment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Renew.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/locks/Create/CreateLock.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockFormSummary.tsx
  unlock-app/src/components/interface/locks/Create/modals/SelectCurrencyModal.tsx
  unlock-app/src/components/interface/locks/Manage/elements/CardPayment.tsx
  unlock-app/src/components/interface/locks/Manage/elements/EnableRecurring.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/Members.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MetadataCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/TotalBar.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdateDurationModal.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdatePriceModal.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdateQuantityModal.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropDrawer.tsx
  unlock-app/src/hooks/useLockManager.ts
  unlock-app/src/pages/_app.tsx
  yarn.lock
Labels: cla-signed

#9874 feat(unlock-app) - clean up
  unlock-app/src/__tests__/components/interface/checkout/SwitchPayment.test.tsx
  unlock-app/src/components/interface/Layout.jsx
  unlock-app/src/components/interface/checkout/ClaimMembershipCheckout.tsx
  unlock-app/src/components/interface/checkout/FormStyles.tsx
  unlock-app/src/components/interface/checkout/RecommendWallets.tsx
  unlock-app/src/components/interface/checkout/SwitchPayment.tsx
Labels: cla-signed

#9866 feat(ci): Add publish action to publish packages automatically
  .github/workflows/publish.yml
  .yarnrc.yml
  package.json
  packages/contracts/package.json
  packages/hardhat-plugin/package.json
  packages/hardhat-plugin/src/networks.json
  packages/networks/package.json
  packages/paywall/package.json
  packages/types/package.json
  packages/ui/package.json
  packages/unlock-js/package.json
  yarn.lock
Labels: cla-signed

#9878 fix(unlock-app): Hide claim button when user has enough money to pay using crypto
  unlock-app/src/components/interface/checkout/alpha/Checkout/Payment.tsx
Labels: cla-signed

#9879 ethonline blog post
  unlock-protocol-com/blog/ethonline-2022.md
  unlock-protocol-com/public/images/blog/ethonline-2022/ethonline-share.png
  unlock-protocol-com/public/images/blog/ethonline-2022/homebase.png
  unlock-protocol-com/public/images/blog/ethonline-2022/raindrop.jpeg
Labels: cla-signed

#9881 fix(ui): Remove post install script from ui library
  packages/ui/package.json
Labels: cla-signed

#9884 rename(networks): Xdai subgraph was renamed to gnosis with v2
  packages/hardhat-plugin/src/networks.json
  packages/networks/package.json
  packages/networks/src/networks/xdai.ts
Labels: cla-signed

#9875 feat(unlock-app) - cleanup part 4
  unlock-app/src/__tests__/components/content/RecoverContent.test.js
  unlock-app/src/__tests__/components/interface/Header.test.js
  unlock-app/src/components/content/HomeContent.jsx
  unlock-app/src/components/content/RecoverContent.tsx
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/components/interface/AppFooter.tsx
  unlock-app/src/components/interface/AppHeader.tsx
  unlock-app/src/components/interface/Container.tsx
  unlock-app/src/components/interface/Footer.jsx
  unlock-app/src/components/interface/Header.jsx
  unlock-app/src/components/interface/Layout.jsx
  unlock-app/src/components/interface/buttons/PageNavButton.jsx
  unlock-app/src/components/interface/buttons/layout/About.jsx
  unlock-app/src/components/interface/buttons/layout/Bars.jsx
  unlock-app/src/components/interface/buttons/layout/ChevronUp.jsx
  unlock-app/src/components/interface/buttons/layout/Discord.jsx
  unlock-app/src/components/interface/buttons/layout/Github.jsx
  unlock-app/src/components/interface/buttons/layout/Jobs.jsx
  unlock-app/src/components/interface/buttons/layout/Newsletter.jsx
  unlock-app/src/components/interface/buttons/layout/Twitter.jsx
  unlock-app/src/components/interface/buttons/layout/index.jsx
  unlock-app/src/components/interface/buttons/navigation/Dashboard.jsx
  unlock-app/src/components/interface/buttons/navigation/Keychain.jsx
  unlock-app/src/components/interface/buttons/navigation/Settings.jsx
  unlock-app/src/components/interface/buttons/navigation/index.jsx
  unlock-app/src/components/interface/layouts/AppLayout.tsx
  unlock-app/src/components/interface/locks/Manage/elements/EnableRecurring.tsx
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/ImageBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MemberCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/PaginationBar.tsx
Labels: cla-signed

#9882 cleanup(locksmith): Remove purchase emailer list scripts
  locksmith/package.json
  locksmith/scripts/purchase_emailer/emailList.ts
  locksmith/scripts/purchase_emailer/querier.ts
  yarn.lock
Labels: cla-signed

#9894 rename(networks): Unlock was renamed to mainnet-v2
  packages/hardhat-plugin/src/networks.json
  packages/networks/src/networks/mainnet.ts
Labels: cla-signed

#9885 fix(smart-contracts): remove unused TODOs and names from docstrings
  smart-contracts/contracts/mixins/MixinFunds.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinLockMetadata.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: cla-signed, publicLock v12

#9896 feat(unlock-app) - add lock version
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
Labels: cla-signed

#9883 refactor(unlock-js): Rename export explicitly to avoid confusion
  packages/unlock-js/package.json
  packages/unlock-js/src/index.ts
  packages/unlock-js/src/locksmithService.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9895 fix(subgraph): don't index locks below v5
  subgraph/src/unlock.ts
Labels: cla-signed

#9899 feat(unlock-app) - fix copy address
  unlock-app/src/components/interface/locks/Manage/elements/MemberCard.tsx
Labels: cla-signed

#9891 feat(unlock-app) - clean up part 5
  unlock-app/jest.config.js
  unlock-app/src/__tests__/components/interface/Button.test.js
  unlock-app/src/components/interface/checkout/CallToAction.tsx
  unlock-app/src/components/interface/checkout/CardConfirmationCheckout.tsx
  unlock-app/src/components/interface/checkout/LockVariations.tsx
Labels: cla-signed

#9900 feat(unlock-app): Respect the paywallConfig messageToSign if passed along with oauth parameters
  unlock-app/src/components/interface/checkout/alpha/Connect/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/index.tsx
  unlock-app/src/components/interface/checkout/alpha/index.tsx
Labels: cla-signed

#9502 feat(unlock-app) - disable cancellations when balance on lock is not enough
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/src/PublicLock/v10/getCancelAndRefundValueFor.js
  packages/unlock-js/src/PublicLock/v7/getCancelAndRefundValueFor.js
  packages/unlock-js/src/walletService.ts
  packages/unlock-js/src/web3Service.ts
  unlock-app/src/__tests__/components/interface/keychain/CancelAndRefundModal.test.tsx
  unlock-app/src/__tests__/hooks/useKeychain.test.ts
  unlock-app/src/__tests__/utils/strings.test.js
  unlock-app/src/__tests__/utils/url.test.ts
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/keychain/CancelAndRefundModal.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/locks/Manage/elements/Members.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  unlock-app/src/hooks/useKeychain.ts
Labels: cla-signed

#9902 feature(wedlocks): adding template for rekt
  wedlocks/src/templates/locks/index.js
  wedlocks/src/templates/locks/keyMined-0x7d9904bdCE826cADE55459083252C41E23e1F7F9.js
  wedlocks/static/attachments/function.png
  wedlocks/static/attachments/rekt.png
Labels: cla-signed

#9901 feat(unlock-app) - Fix change network
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockFormSummary.tsx
Labels: cla-signed

#9897 fix(unlock-app): Simplify the template for bulk airdrop
  unlock-app/public/templates/airdrop.csv
Labels: cla-signed

#9905 feat(unlock-app) - reset page on search
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/Members.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#9906 Rekt template
  wedlocks/src/templates/locks/index.js
Labels: cla-signed

#9903 feat(all): Add express, various config and helper packages to auto publish and build
  package.json
  packages/contracts/package.json
  packages/eslint-config/package.json
  packages/hardhat-helpers/package.json
  packages/hardhat-plugin/package.json
  packages/jest-config/package.json
  packages/networks/package.json
  packages/paywall/package.json
  packages/types/package.json
  packages/ui/package.json
  packages/unlock-js/package.json
  yarn.lock
Labels: cla-signed

#9880 feat(ui): Add new ticket UI component
  packages/ui/.storybook/main.js
  packages/ui/lib/components/Ticket/Ticket.stories.tsx
  packages/ui/lib/components/Ticket/Ticket.tsx
  packages/ui/lib/index.tsx
  packages/ui/lib/utils.ts
  packages/ui/package.json
  packages/ui/public/images/lock.png
  packages/ui/public/images/qrcode.png
  yarn.lock
Labels: cla-signed

#9890 fix(smart-contracts): add timestamp to expiration event
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/shareKey.js
  smart-contracts/test/Lock/timeMachine.js
Labels: cla-signed, publicLock v12

#9909 feat(subgraph): add arbitrum one to networks config
  subgraph/networks.json
Labels: cla-signed

#9674 feat(locksmith) - show expired and now expired key when search for keyId
  locksmith/src/graphql/datasource/keysByQuery.ts
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
Labels: cla-signed

#9914 openapi blog post
  unlock-protocol-com/blog/open-api-support.md
  unlock-protocol-com/public/images/blog/open-api-support/unlock-api-share.png
Labels: cla-signed

#9915 fix(unlock-protocol-com): Image is png, not jpeg
  unlock-protocol-com/blog/open-api-support.md
Labels: cla-signed

#9908 feat(subgraph): add support for new `ExpirationDuration` format
  packages/contracts/src/abis/PublicLock/PublicLockV12.json
  packages/contracts/src/index.ts
  subgraph/abis/PublicLock.json
  subgraph/abis/PublicLockV12.json
  subgraph/src/public-lock.ts
  subgraph/subgraph.yaml
  subgraph/tests/keys-utils.ts
  subgraph/tests/keys.test.ts
Labels: cla-signed, publicLock v12

#9892 fix(smart-contracts): remove concept of `beneficiary`
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinErrors.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/utils/LockSerializer.sol
  smart-contracts/test/Lock/approveBeneficiary.js
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/expireAndRefundFor.js
  smart-contracts/test/Lock/permissions/beneficiary.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/Lock/withdrawByAddress.js
Labels: cla-signed, publicLock v12

#9921 feat(unlock-app) - 9920 show lock balances on list
  unlock-app/src/components/interface/locks/List/elements/LockCard.tsx
Labels: cla-signed

#9860 feat(unlock-app) - update pagination component
  unlock-app/src/components/interface/locks/Manage/elements/PaginationBar.tsx
Labels: cla-signed

#9888 fix(smart-contracts): use single function `updateLockConfig` to set lock key params
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/burn.js
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/expirationDuration.js
  smart-contracts/test/Lock/extendRenewable.js
  smart-contracts/test/Lock/getHasValidKey.js
  smart-contracts/test/Lock/maxKeysPerAddress.js
  smart-contracts/test/Lock/maxNumberOfKeys.js
  smart-contracts/test/Lock/onKeyExtendHook.js
  smart-contracts/test/Lock/onKeyPurchaseHook.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/permissions/keyManager.js
  smart-contracts/test/Lock/purchaseFor.js
  smart-contracts/test/Lock/purchaseForFrom.js
  smart-contracts/test/Lock/renewMembershipFor.js
  smart-contracts/test/Lock/setReferrerFee.js
  smart-contracts/test/Lock/shareKey.js
  smart-contracts/test/Lock/soldOut.js
  smart-contracts/test/Lock/totalKeys.js
  smart-contracts/test/Lock/transfer.js
  smart-contracts/test/Lock/updateLockConfig.js
  smart-contracts/test/Lock/upgrades/v11.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/UnlockDiscountToken/mintingTokens.js
  smart-contracts/test/UnlockDiscountToken/transferingTokens.js
  smart-contracts/test/UnlockDiscountToken/upgrades.js
  smart-contracts/test/fixtures/locks.js
  smart-contracts/test/helpers/deployLocks.js
Labels: cla-signed, publicLock v12

#9893 feat(unlock-app) - replace modal with component
  unlock-app/jest.config.js
  unlock-app/src/__tests__/components/interface/ExpireAndRefundModal.test.tsx
  unlock-app/src/__tests__/components/interface/InlineModal.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/CancelAndRefundModal.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/QRModal.test.tsx
  unlock-app/src/components/interface/ExpireAndRefundModal.tsx
  unlock-app/src/components/interface/InlineModal.tsx
  unlock-app/src/components/interface/keychain/CancelAndRefundModal.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/QRModal.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MemberCard.tsx
  unlock-app/src/components/interface/modal-templates/index.ts
  unlock-app/src/components/interface/modal-templates/styles.ts
Labels: cla-signed

#9912 fix(smart-contracts): add tests for missing return statements in interface
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/test/Lock/interface.js
  smart-contracts/test/Unlock/interface.js
  smart-contracts/test/helpers/index.js
  smart-contracts/test/helpers/interface.js
Labels: cla-signed, publicLock v12

#9916 remove(unlock): Transaction router and related methods
  locksmith/__tests__/controllers/transactionController.test.js
  locksmith/__tests__/operations/transactionOperations.test.js
  locksmith/src/controllers/transactionController.js
  locksmith/src/models/index.ts
  locksmith/src/models/transaction.ts
  locksmith/src/operations/transactionOperations.ts
  locksmith/src/routes/index.ts
  locksmith/src/routes/transaction.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9929 fix(unlock-app): Stop double prompting for message request
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9927 feat(unlock-app)- convert to zod
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#9932 fix(smart-contracts): show missing function in interfaces test
  smart-contracts/test/Lock/interface.js
  smart-contracts/test/Unlock/interface.js
Labels: cla-signed

#9858 feat(unlock-js): Add subgraph service
  .prettierignore
  package.json
  packages/unlock-js/.eslintignore
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/codegen.ts
  packages/unlock-js/examples/subgraph.js
  packages/unlock-js/package.json
  packages/unlock-js/src/index.ts
  packages/unlock-js/src/subgraph/index.ts
  packages/unlock-js/src/subgraph/schema.graphql
  unlock-app/package.json
  yarn.lock
Labels: cla-signed

#9930 refactor(locksmith): Remove namespace usage
  locksmith/__tests__/controllers/userController/cards.test.ts
  locksmith/__tests__/controllers/userController/ejection.test.ts
  locksmith/__tests__/controllers/userController/emailUpdate.test.ts
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/__tests__/controllers/userController/paymentDetails.test.ts
  locksmith/__tests__/controllers/userController/recoveryPhrase.test.ts
  locksmith/__tests__/controllers/userController/userCreation.test.ts
  locksmith/jest.config.js
  locksmith/src/controllers/userController.ts
  locksmith/src/operations/stripeOperations.ts
  locksmith/src/operations/userOperations.ts
  locksmith/src/routes/index.ts
  locksmith/src/routes/user.ts
  locksmith/src/utils/middlewares/auth.ts
  yarn.lock
Labels: cla-signed

#9886 feat(contracts): Merge metadata setters into a single `setLockMetadata`
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinLockMetadata.sol
  smart-contracts/test/Lock/erc721/tokenName.js
  smart-contracts/test/Lock/erc721/tokenSymbol.js
  smart-contracts/test/Lock/erc721/tokenURI.js
  smart-contracts/test/Lock/setLockMetadata.js
  smart-contracts/test/LockSerializer/serialize.js
  smart-contracts/test/fixtures/metadata.js
Labels: cla-signed, publicLock v12

#9933 fix(ci) : typo in ci subgraph script
  docker/development/subgraph/startup.sh
Labels: cla-signed

#9938 feat(unlock-protocol-com): Add airdrop blog post
  unlock-protocol-com/blog/csv-airdrop.md
  unlock-protocol-com/public/images/blog/unlock-csv-airdrop/main.png
  unlock-protocol-com/public/images/blog/unlock-csv-airdrop/members.png
Labels: cla-signed

#9940 Update AirdropBulkForm.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropBulkForm.tsx
Labels: cla-signed

#9939 feat(smart-contracts): add `onGrantKey` hook
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/interfaces/hooks/ILockKeyGrantHook.sol
  smart-contracts/contracts/interfaces/hooks/ILockKeyTransferHook.sol
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/test-artifacts/TestEventHooks.sol
  smart-contracts/contracts/test-artifacts/TestPublicLockUpgraded.sol
  smart-contracts/test/Lock/hooks/erc1155BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc20BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc721BalanceOfHook.js
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeyExtendHook.js
  smart-contracts/test/Lock/onKeyGrantHook.js
  smart-contracts/test/Lock/onKeyPurchaseHook.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/onTokenURIHook.js
  smart-contracts/test/Lock/onValidKeyHook.js
  smart-contracts/test/Lock/purchaseWithoutUnlock.js
  smart-contracts/test/Lock/renewMembershipFor.js
  smart-contracts/test/Lock/upgrades/v12.js
  yarn.lock
Labels: cla-signed, publicLock v12

#9945 feat(contracts): match optimizer runs value btw contracts package and local dev
  packages/contracts/hardhat.config.js
Labels: smart contract, cla-signed

#9943 feat(contracts): release PublicLock v12
  packages/contracts/package.json
  packages/contracts/src/abis/PublicLock/PublicLockV12.json
  packages/contracts/src/contracts/PublicLock/IPublicLockV12.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV12.sol
  packages/hardhat-plugin/package.json
  yarn.lock
Labels: cla-signed, publicLock v12

#9947 Minor grammatical fix
  unlock-app/src/components/interface/locks/Manage/elements/Members.tsx
Labels: cla-signed

#9948 fix(smart-contracts): make beneficiary payable again
  docker/development/eth-node/package.json
  docker/development/eth-node/yarn.lock
  packages/contracts/package.json
  packages/contracts/src/abis/PublicLock/PublicLockV12.json
  packages/contracts/src/contracts/PublicLock/PublicLockV12.sol
  packages/hardhat-plugin/package.json
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/scripts/lock/testUpgrade.js
  yarn.lock
Labels: cla-signed

#9950 fix(smart-contracts): bump gnosis and etherscan versions
  packages/hardhat-helpers/src/etherscan.js
  smart-contracts/package.json
  smart-contracts/scripts/deployments/template.js
  smart-contracts/scripts/multisig/submitTx.js
  smart-contracts/scripts/upgrade/submitLockVersion.js
  yarn.lock
Labels: cla-signed

#9956 chore(locksmith): Update jest
  locksmith/package.json
  yarn.lock
Labels: cla-signed

#9953 feat(unlock-app): Lenient handling of redirect uri in checkout url
  unlock-app/src/components/interface/checkout/alpha/index.tsx
Labels: cla-signed

#9958 feat(unlock-app) - add address to schema
  packages/unlock-js/src/subgraph/schema.graphql
Labels: cla-signed

#9955 Fix: typos
  README.md
Labels: cla-signed

#9959 feat(unlock-app) - use locks with subgraph service
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/package.json
  unlock-app/src/__tests__/hooks/useLocks.test.js
  unlock-app/src/hooks/useLocks.js
Labels: cla-signed

#9935 feat(unlock-app): Support forever in recurring option
  packages/ui/lib/components/Badge/Badge.tsx
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/src/PublicLock/v10/purchaseKey.js
  packages/unlock-js/src/PublicLock/v10/purchaseKeys.js
  packages/unlock-js/src/walletService.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/hooks/useLock.ts
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#9964 feat(locksmith) update jest
  locksmith/Dockerrun.aws.json
  locksmith/jest.config.js
  locksmith/package.json
  yarn.lock
Labels: cla-signed

#9963 doc(subgraph): README how to debug deployed subgraph
  subgraph/README.md
Labels: cla-signed

#9967 feature(unlock-protocol.com): minor copy changes
  unlock-protocol-com/src/components/pages/Developers/index.tsx
  unlock-protocol-com/src/components/pages/Home/sections/Connect.tsx
  unlock-protocol-com/src/components/pages/Home/sections/MembershipExplained.tsx
  unlock-protocol-com/src/components/pages/Home/sections/Recipes.tsx
  unlock-protocol-com/src/components/pages/Home/sections/Steps.tsx
  unlock-protocol-com/src/config/constants.ts
Labels: cla-signed

#9970 blog(unlock-protocol): Email required blog post
  unlock-protocol-com/blog/email-required.md
  unlock-protocol-com/public/images/blog/email-required/collecting-email.png
  unlock-protocol-com/public/images/blog/email-required/email-required-share.png
Labels: cla-signed

#9974 feat(unlock-app) - set default filter to 'all'
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/Members.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#9976 feat(locksmith): Move key and lock source to subgraph v2
  locksmith/src/graphql/datasource/key.ts
  locksmith/src/graphql/datasource/keysToRenew.ts
  locksmith/src/graphql/datasource/lock.ts
  locksmith/src/websub/jobs/keys.ts
  locksmith/src/websub/jobs/locks.ts
  locksmith/src/websub/jobs/renewFiatKeys.ts
  locksmith/src/websub/jobs/renewKeys.ts
Labels: cla-signed

#9975 feat(unlock-app) - Allow for 0 supply
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockFormSummary.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdateQuantityModal.tsx
Labels: cla-signed

#9979 feat(unlock-app) - keys list v2
  locksmith/__tests__/controllers/v2/keyController.test.ts
  locksmith/__tests__/operations/keysOperations.test.ts
  locksmith/src/graphql/datasource/keysByQuery.ts
  locksmith/src/operations/keysOperations.ts
  locksmith/src/operations/metadataOperations.ts
  unlock-app/src/components/interface/locks/Manage/elements/FilterBar.tsx
Labels: cla-signed

#9981 fix(websub): Use token ID
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/graphql/datasource/key.ts
  locksmith/src/graphql/datasource/keysToRenew.ts
  locksmith/src/graphql/datasource/lock.ts
  locksmith/src/operations/wedlocksOperations.ts
  locksmith/src/websub/jobs/renewFiatKeys.ts
  locksmith/src/websub/jobs/renewKeys.ts
Labels: cla-signed

#9983 feat(unlock-app) - Keychain subgraph v2
  unlock-app/public/images/illustrations/img-error.svg
  unlock-app/src/__tests__/components/interface/keychain/Key.test.tsx
  unlock-app/src/__tests__/components/interface/keychain/KeyDetails.test.tsx
  unlock-app/src/components/interface/keychain/CancelAndRefundModal.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/KeyDetails.tsx
  unlock-app/src/components/interface/keychain/KeyMetadataModal.tsx
  unlock-app/src/components/interface/keychain/KeychainTypes.ts
  unlock-app/src/components/interface/keychain/QRModal.tsx
  unlock-app/src/queries/keyHolder.js
Labels: cla-signed

#9978 refactor(locksmith): Remove graphql server
  locksmith/__tests__/controllers/metadataController/readAddressHolderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/requestingKeyholderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/requestingTokenMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/tokenData.test.ts
  locksmith/__tests__/controllers/metadataController/updateAddressHolderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/updateDefaults.test.ts
  locksmith/__tests__/controllers/metadataController/updateKeyMetadata.test.ts
  locksmith/__tests__/graphql/datasource/keyHolder.test.ts
  locksmith/package.json
  locksmith/src/app.ts
  locksmith/src/graphql/datasource/index.ts
  locksmith/src/graphql/datasource/key.ts
  locksmith/src/graphql/datasource/keyHolder.ts
  locksmith/src/graphql/datasource/keyPurchase.ts
  locksmith/src/graphql/datasource/keyholdersByLock.ts
  locksmith/src/graphql/datasource/keysToRenew.ts
  locksmith/src/graphql/datasource/lock.ts
  locksmith/src/graphql/datasource/locksByOwner.ts
  locksmith/src/graphql/datasource/metaData.ts
  locksmith/src/graphql/resolvers.ts
  locksmith/src/graphql/typeDefinitions.ts
  yarn.lock
Labels: cla-signed

#9986 fix(locksmith): Initialise cors middleware properly
  locksmith/src/app.ts
Labels: cla-signed

#9988 fix(locksmith): Add graphql-tag dependency explicitly
  locksmith/package.json
  yarn.lock
Labels: cla-signed

#9989 feat(unlock-app): Allow an additional delimiter for csv import
  unlock-app/src/components/interface/members/airdrop/AirdropBulkForm.tsx
Labels: cla-signed

#9987 fix(unlock-js): fix test runner on CI
  packages/unlock-js/hardhat.config.js
  packages/unlock-js/package.json
  packages/unlock-js/src/__tests__/helpers/abis/ERC1967Proxy.json
  packages/unlock-js/src/__tests__/helpers/deployUnlock.js
  packages/unlock-js/src/__tests__/helpers/setTemplate.js
Labels: cla-signed

#9990 feat(unock-app) - add append/prepend options to select component
  packages/ui/lib/components/Select/Select.stories.tsx
  packages/ui/lib/components/Select/Select.tsx
Labels: cla-signed

#9992 fix(locksmith): fixing email sending
  locksmith/src/graphql/datasource/key.ts
  locksmith/src/graphql/datasource/lock.ts
  locksmith/src/operations/wedlocksOperations.ts
Labels: cla-signed

#9994 feat(unlock-protocol-com): blog post for lock v12 release
  unlock-protocol-com/blog/lock-v12-release.md
  unlock-protocol-com/public/images/blog/lock-v12-release/lock-v12-release-share.png
Labels: cla-signed

#9991 feat(unlock-app) - add description to toggle switch component
  packages/ui/lib/components/Form/FieldLayout.tsx
  packages/ui/lib/components/ToggleSwitch/ToggleSwitch.stories.tsx
  packages/ui/lib/components/ToggleSwitch/ToggleSwitch.tsx
Labels: cla-signed

#9997 feat(ui): Add textbox to ui library
  packages/ui/lib/components/Form/TextBox.stories.tsx
  packages/ui/lib/components/Form/TextBox.tsx
  packages/ui/lib/components/Form/index.tsx
  packages/ui/lib/index.tsx
Labels: cla-signed

#9993 feat(unlock-app) - add field description in zod
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#9977 fix(unlock-js): split the tests functions into their own files
  packages/unlock-js/README.md
  packages/unlock-js/hardhat.config.js
  packages/unlock-js/jest.config.js
  packages/unlock-js/package.json
  packages/unlock-js/src/__tests__/helpers/configureUnlock.js
  packages/unlock-js/src/__tests__/helpers/integration.js
  packages/unlock-js/src/__tests__/integration/lock/approveBeneficiary.js
  packages/unlock-js/src/__tests__/integration/lock/cancelAndRefund.js
  packages/unlock-js/src/__tests__/integration/lock/expireAndRefundFor.js
  packages/unlock-js/src/__tests__/integration/lock/extendKey.js
  packages/unlock-js/src/__tests__/integration/lock/grantKey.js
  packages/unlock-js/src/__tests__/integration/lock/grantKeyExtension.js
  packages/unlock-js/src/__tests__/integration/lock/grantKeys.js
  packages/unlock-js/src/__tests__/integration/lock/keyGranter.js
  packages/unlock-js/src/__tests__/integration/lock/maxKeysPerAddress.js
  packages/unlock-js/src/__tests__/integration/lock/mergeKeys.js
  packages/unlock-js/src/__tests__/integration/lock/purchaseKey.js
  packages/unlock-js/src/__tests__/integration/lock/purchaseKeys.js
  packages/unlock-js/src/__tests__/integration/lock/setExpirationDuration.js
  packages/unlock-js/src/__tests__/integration/lock/setMaxNumberOfKeys.js
  packages/unlock-js/src/__tests__/integration/lock/shareKeyToAddress.js
  packages/unlock-js/src/__tests__/integration/lock/shareKeyToTokenId.js
  packages/unlock-js/src/__tests__/integration/lock/updateKeyPrice.js
  packages/unlock-js/src/__tests__/integration/lock/withdrawFromLock.js
  packages/unlock-js/src/__tests__/integration/single.js
  packages/unlock-js/src/__tests__/integration/unlock/lockCreation.js
  packages/unlock-js/src/__tests__/integration/unlock/unlockConfig.js
  packages/unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  yarn.lock
Labels: cla-signed

#9995 fix(contracts): fix script to generate contract docs
  packages/contracts/src/contracts/PublicLock/IPublicLockV12.sol
  scripts/docs-contracts-pr.sh
Labels: cla-signed

#10000 fix(checkout): Error message on quantity screen
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
Labels: cla-signed

#9998 feat(unlock-js): add metadata setters
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/package.json
  packages/unlock-js/src/PublicLock/v10/index.js
  packages/unlock-js/src/PublicLock/v4/index.js
  packages/unlock-js/src/PublicLock/v4/setBaseTokenURI.js
  packages/unlock-js/src/PublicLock/v4/updateLockName.js
  packages/unlock-js/src/PublicLock/v4/updateLockSymbol.js
  packages/unlock-js/src/PublicLock/v6/index.js
  packages/unlock-js/src/PublicLock/v7/index.js
  packages/unlock-js/src/PublicLock/v8/index.js
  packages/unlock-js/src/PublicLock/v9/index.js
  packages/unlock-js/src/__tests__/integration/lock/setBaseTokenURI.js
  packages/unlock-js/src/__tests__/integration/lock/updateLockName.js
  packages/unlock-js/src/__tests__/integration/lock/updateLockSymbol.js
  packages/unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  packages/unlock-js/src/walletService.ts
Labels: cla-signed

#10001 fixing typo in emails for degen party
  wedlocks/src/templates/locks/keyMined-0x0Da7C68203a9331baEB388BC7e17430F188E4061.js
  wedlocks/src/templates/locks/keyMined-0x5f1c54dEDE0d96F49EEd8F57f653b24d41f4BDd6.js
  wedlocks/src/templates/locks/keyMined-0x838327F343382526e10E14ef6E9F588E69B37230.js
Labels: cla-signed

#10004 using new graph to retrieve locks list
  unlock-app/src/__tests__/hooks/useLocks.test.js
  unlock-app/src/__tests__/services/graphService.test.js
  unlock-app/src/__tests__/services/storageService.test.js
  unlock-app/src/components/creator/lock/LocksByNetwork.tsx
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/hooks/useLocks.js
  unlock-app/src/queries/locksByManager.js
  unlock-app/src/services/graphService.ts
  unlock-app/src/services/storageService.ts
  unlock-app/src/utils/withGraphService.js
Labels: cla-signed

#9968 feat(unlock-js): adds support for v12
  packages/unlock-js/scripts/compressAbi.js
  packages/unlock-js/src/PublicLock/index.ts
  packages/unlock-js/src/PublicLock/v12/approveBeneficiary.js
  packages/unlock-js/src/PublicLock/v12/index.js
  packages/unlock-js/src/PublicLock/v12/setBaseTokenURI.js
  packages/unlock-js/src/PublicLock/v12/setExpirationDuration.js
  packages/unlock-js/src/PublicLock/v12/setMaxKeysPerAddress.js
  packages/unlock-js/src/PublicLock/v12/setMaxNumberOfKeys.js
  packages/unlock-js/src/PublicLock/v12/updateLockName.js
  packages/unlock-js/src/PublicLock/v12/updateLockSymbol.js
  packages/unlock-js/src/PublicLock/v12/withdrawFromLock.js
  packages/unlock-js/src/__tests__/helpers/fixtures/locks.js
  packages/unlock-js/src/__tests__/integration/lock/approveBeneficiary.js
  packages/unlock-js/src/__tests__/integration/lock/setBaseTokenURI.js
  packages/unlock-js/src/__tests__/integration/lock/withdrawFromLock.js
  packages/unlock-js/src/__tests__/integration/unlock/lockCreation.js
  packages/unlock-js/src/__tests__/integration/walletServiceIntegration.test.js
  packages/unlock-js/src/abis.ts
  packages/unlock-js/src/walletService.ts
Labels: cla-signed, publicLock v12

#10007 feat(unlock-app) - make `communication` optional
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Renew.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Renewed.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
Labels: cla-signed

#9934 feat(unlock-app) - Checkout url
  unlock-app/package.json
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/BasicConfigForm.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/CheckoutForm.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/CheckoutPreview.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/DynamicForm.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/LocksForm.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/index.tsx
  unlock-app/src/pages/locks/checkout-url.tsx
  unlock-app/src/unlockTypes.ts
  yarn.lock
Labels: cla-signed

#10019 feat(ui): Allow custom react node in the form inputs
  packages/ui/lib/components/Form/FieldLayout.tsx
  packages/ui/lib/components/Form/Input.stories.tsx
  packages/ui/lib/components/Form/Input.tsx
  packages/ui/lib/components/Form/TextBox.tsx
Labels: cla-signed

#10021 feat(unlock-app) - add field layout to select component
  packages/ui/lib/components/Select/Select.stories.tsx
  packages/ui/lib/components/Select/Select.tsx
Labels: cla-signed

#10022 feat(unlock-app) - support for input type number
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/DynamicForm.tsx
Labels: cla-signed

#10023 feat(unlock-app) - add message when locks are not present for network
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/LocksForm.tsx
Labels: cla-signed

#10027 feat(ui): Change modal to fit our new blur background and padding system
  packages/ui/lib/components/Modal/Modal.stories.tsx
  packages/ui/lib/components/Modal/Modal.tsx
  unlock-app/src/components/content/VerifiersContent.tsx
  unlock-app/src/components/interface/AppHeader.tsx
  unlock-app/src/components/interface/ConnectWalletModal.tsx
  unlock-app/src/components/interface/DownloadWallet.tsx
  unlock-app/src/components/interface/ExpireAndRefundModal.tsx
  unlock-app/src/components/interface/keychain/CancelAndRefundModal.tsx
  unlock-app/src/components/interface/keychain/KeyMetadataModal.tsx
  unlock-app/src/components/interface/keychain/QRModal.tsx
  unlock-app/src/components/interface/layouts/AppLayout.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MetadataCard.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdateDurationModal.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdatePriceModal.tsx
  unlock-app/src/components/interface/locks/Manage/modals/UpdateQuantityModal.tsx
Labels: cla-signed

#10028 feat(unlock-app) - fix set default option select component
  packages/ui/lib/components/Select/Select.tsx
Labels: cla-signed

#10026 fix(hardhat-plugin): allow to pass `unlockAddress` when creating a lock
  packages/hardhat-plugin/CHANGELOG.md
  packages/hardhat-plugin/package.json
  packages/hardhat-plugin/src/createLock.ts
Labels: cla-signed
