Repository unlock-protocol/unlock, pull requests merged in 2022-06, with the labels that each got.

#8875 feat(locksmith) - fix error message
  locksmith/src/controllers/v2/authController.ts
Labels: cla-signed

#8941 Retroactive funding retro post
  unlock-protocol-com/blog/retro-retro-active-funding.md
  unlock-protocol-com/public/images/blog/retro-retroactive-funding.png
  unlock-protocol-com/src/components/pages/Home/sections/Connect.tsx
Labels: cla-signed

#8861 fix(smart-contracts): remove unused logic from PublicLock contract
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: cla-signed

#8944 feat(unlock-app): Add redesigned connect oauth flow
  unlock-app/src/components/content/CheckoutContent.tsx
  unlock-app/src/components/creator/ConnectCard.tsx
  unlock-app/src/components/interface/checkout/CallToAction.tsx
  unlock-app/src/components/interface/checkout/alpha/Bottom.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Container.tsx
  unlock-app/src/components/interface/checkout/alpha/Shell.tsx
  unlock-app/src/components/interface/checkout/alpha/SignInOrUp.tsx
  unlock-app/src/components/interface/checkout/alpha/index.tsx
  unlock-app/src/components/interface/svg/index.tsx
  unlock-app/src/contexts/AuthenticationContext.ts
  unlock-app/src/hooks/useCheckoutCommunication.ts
  unlock-app/src/pages/_app.tsx
  unlock-app/src/pages/alpha/checkout.tsx
  unlock-app/src/services/storageService.ts
  unlock-app/src/theme/globalStyle.js
  unlock-app/src/unlockTypes.ts
  unlock-app/src/utils/getOAuthFromSearch.ts
  unlock-app/src/utils/oauth.ts
  unlock-app/src/utils/withConfig.js
  unlock-app/src/utils/withStorageService.tsx
  unlock-app/tsconfig.json
  yarn.lock
Labels: cla-signed

#8945 feat(smart-contracts): bump PublicLock solc version to 0.8.13
  smart-contracts/contracts/PublicLock.sol
  smart-contracts/contracts/UnlockUtils.sol
  smart-contracts/hardhat.config.js
Labels: cla-signed

#8950 fix(networks) renamed xdai to gnosis chain
  packages/networks/src/networks/xdai.ts
Labels: cla-signed

#8949 chore(dependencies): removed stale dependencies
  locksmith/package.json
  packages/unlock-assets/package.json
  yarn.lock
Labels: cla-signed

#8952 chore(paywall-config) removed paywall-config
  packages/paywall-config/README.md
  packages/paywall-config/package.json
  packages/paywall-config/public/Unlock-WordMark.png
  packages/paywall-config/public/favicon.ico
  packages/paywall-config/public/index.html
  packages/paywall-config/public/logo192.png
  packages/paywall-config/public/logo512.png
  packages/paywall-config/public/manifest.json
  packages/paywall-config/public/robots.txt
  packages/paywall-config/src/App.js
  packages/paywall-config/src/_test_/Form.test.js
  packages/paywall-config/src/components/Forms.js
  packages/paywall-config/src/components/config.js
  packages/paywall-config/src/index.css
  packages/paywall-config/src/index.js
  packages/paywall-config/test.html
Labels: cla-signed

#8874 feature(unlock-app) - verifiers use token and login fix
  unlock-app/src/components/content/VerifiersContent.tsx
  unlock-app/src/components/interface/verifiers/VerifiersList.tsx
  unlock-app/src/hooks/useToken.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#8954 Revert "fix(deps): update packages/eslint-config (#8922)"
  packages/eslint-config/package.json
  yarn.lock
Labels: cla-signed

#8956 chore(unlock-app): Remove exportPath function from next config
  unlock-app/next.config.js
  unlock-app/src/__tests__/pages/pages.test.js
  unlock-app/src/__tests__/utils/exportStatic.test.js
  unlock-app/src/pages/index.js
  unlock-app/src/utils/exportStatic.js
Labels: cla-signed

#8962 fix(readme): yarn workspace command typo
  README.md
Labels: cla-signed

#8859 feat(unlock-app) - Login and authorized endpoints
  packages/unlock-js/src/locksmithService.ts
  unlock-app/package.json
  unlock-app/src/components/content/VerifiersContent.tsx
  unlock-app/src/components/interface/verifiers/VerifiersList.tsx
  unlock-app/src/hooks/useAppStorage.ts
  unlock-app/src/services/storageService.ts
  yarn.lock
Labels: cla-signed

#8951 chore(smart-contracts) Dry-up networks
  smart-contracts/networks.js
  smart-contracts/package.json
  yarn.lock
Labels: cla-signed

#8967 feat(unlock-app) - set *withAuth* default value for getEndpoint fn
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#8957 chore(monorepo) Warning lint
  package.json
Labels: cla-signed

#8964 fix(smart-contracts): dedupe zero address check when creating a key
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
Labels: cla-signed

#8970 Update the logo and variant
  design/brand/1808-Unlock-Identity_Unlock-LogoMark-Circle.svg
  design/brand/1808-Unlock-Identity_Unlock-LogoMark-Square.svg
  design/brand/1808-Unlock-Identity_Unlock-LogoMark.svg
  design/brand/1808-Unlock-Identity_Unlock-WordMark.svg
  design/brand/No Color/Unlock-Identity-WorkMark.svg
  design/brand/No Color/Unlock-LogoMark-Circle.svg
  design/brand/No Color/Unlock-LogoMark-CirclePadding.svg
  design/brand/No Color/Unlock-LogoMark.svg
  design/brand/No Color/unlock-word-mark.svg
  design/brand/No Color/unlock.svg
  design/brand/PNG/Julien.png
  design/brand/PNG/Unlock-LogoMark-BLACK.png
  design/brand/PNG/Unlock-LogoMark-Circle-Border.png
  design/brand/PNG/Unlock-LogoMark-Circle-TRANSPARENT.png
  design/brand/PNG/Unlock-LogoMark-Circle.png
  design/brand/PNG/Unlock-LogoMark-CircleWHITE-TRANSPARENT.png
  design/brand/PNG/Unlock-LogoMark-Square-TRANSPARENT.png
  design/brand/PNG/Unlock-LogoMark-Square.png
  design/brand/PNG/Unlock-LogoMark.png
  design/brand/PNG/Unlock-WordMark.png
  design/brand/Unlock-Identity-BrandColor.pdf
  design/brand/Unlock-LogoMark-Circle-Transparent.svg
  design/brand/Unlock-LogoMark-Circle.svg
  design/brand/Unlock-LogoMark-Square.svg
  design/brand/Unlock-LogoMark.svg
  design/brand/Unlock-WorkMark.svg
  design/illustration/Digital_Cash.jpg
  design/illustration/KeyCircle.png
  design/illustration/Keychain.png
  design/illustration/Unlock-Background-Cover.jpg
  design/logo/Unlock-LogoMark-Circle.svg
  design/logo/Unlock-LogoMark-Circle@2x.png
  design/logo/Unlock-LogoMark-Square.svg
  design/logo/Unlock-LogoMark-Square@2x.png
  design/logo/unlock-outline-animation.gif
  design/logo/unlock-outline-animation.svg
  design/logo/Ʉnlock Symbol-white.svg
  design/logo/Ʉnlock Symbol-white@2x.png
  design/logo/Ʉnlock Symbol.svg
  design/logo/Ʉnlock Symbol@2x.png
  design/logo/Ʉnlock-full-logo.svg
  design/logo/Ʉnlock-full-logo@2x.png
Labels: design

#8971 fix(unlock-app): Use window.history.back instead of window.close in checkout close function
  unlock-app/src/components/interface/checkout/Checkout.tsx
Labels: cla-signed

#8972 refactor(unlock-app): Rename paywallConfig utils
  unlock-app/src/__tests__/utils/getConfigFromSearch.test.ts
  unlock-app/src/components/content/CheckoutContent.tsx
  unlock-app/src/utils/paywallConfig.ts
Labels: cla-signed

#8946 chore(smart-contracts): refactor copying contract files in helper
  smart-contracts/helpers/deployments.js
  smart-contracts/test/Lock/upgrades/v10.js
  smart-contracts/test/Lock/upgrades/v11.js
  smart-contracts/test/LockSerializer/serialize.js
  smart-contracts/test/Unlock/addLockTemplate.js
  smart-contracts/test/Unlock/createLockAtVersion.js
  smart-contracts/test/Unlock/migrateLockData/v10.js
  smart-contracts/test/Unlock/upgradeLock.js
  smart-contracts/test/Unlock/upgrades.js
  smart-contracts/test/helpers/versions.js
  smart-contracts/test/truffle-fixture.js
Labels: cla-signed

#8974 wedlock(feature): adding dappcon confirmation email
  wedlocks/src/templates/locks/keyMined-0x2217D4fF7B9978ba123019Bf1F4DC0A2Bd46F9D6.js
  wedlocks/static/attachments/dappcon.png
Labels: cla-signed

#8980 feat(unlock-app): Add quantity screen to new checkout
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Lock.tsx
  unlock-app/src/components/interface/checkout/alpha/useCheckoutState.tsx
Labels: cla-signed

#8981 feat(smart-contracts): `purchase` and `grantKeys` return token ids
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: cla-signed, PublicLock v11

#8948 chore(smart-contracts): bump oz libs to latest 4.6.0
  smart-contracts/contracts/UnlockProtocolGovernor.sol
  smart-contracts/package.json
  smart-contracts/test/Lock/initializers.js
  yarn.lock
Labels: cla-signed

#8985 feat(smart-contracts): use `transfer` in erc20 gas refund
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: cla-signed, PublicLock v11

#8969 feat(locksmith) - add lock manager support in verifiers endpoint
  locksmith/src/controllers/v2/verifierController.ts
  locksmith/src/routes/v2/verifier.ts
  unlock-app/src/components/interface/verifiers/VerifiersList.tsx
Labels: cla-signed

#8973 chore(network): Adding a deployment for Mumbai (polygons test net!)
  packages/networks/src/networks/index.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/tsconfig.json
  smart-contracts/.openzeppelin/unknown-80001.json
  smart-contracts/hardhat.config.js
  smart-contracts/scripts/deployments/index.js
  smart-contracts/scripts/deployments/template.js
  smart-contracts/tasks/deploy.js
  subgraph/bin/subgraphOperation.js
  subgraph/bin/subgraph_generator.js
Labels: cla-signed

#8989 feat(unlock-app) - downgrade react 17
  packages/ui/package.json
  packages/unlock-assets/package.json
  paywall-app/package.json
  unlock-app/package.json
  unlock-protocol-com/package.json
  yarn.lock
Labels: cla-signed

#8992 Ccarfi may22 product blog
  unlock-protocol-com/blog/may-22-update.md
  unlock-protocol-com/public/images/blog/may-22-update/may-22-banner.png
Labels: cla-signed

#8997 feat(unlock-app): Add confirmation screen to new checkout
  packages/contracts/src/index.ts
  packages/unlock-js/src/walletService.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/useCheckoutState.tsx
  unlock-app/src/utils/withWalletService.tsx
Labels: cla-signed

#8993 feat(smart-contracts): `onKeyTransfer` hook
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/interfaces/hooks/ILockKeyTransferHook.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/contracts/test-artifacts/TestEventHooks.sol
  smart-contracts/test/Lock/hooks/erc1155BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc20BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc721BalanceOfHook.js
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeyPurchaseHook.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/onTokenURIHook.js
  smart-contracts/test/Lock/onValidKeyHook.js
  smart-contracts/test/Lock/purchaseWithoutUnlock.js
  smart-contracts/test/Lock/renewMembershipFor.js
Labels: cla-signed, PublicLock v11

#8996 fear(unlock-app) - fix styling multiple recipients
  unlock-app/src/components/interface/checkout/MultipleRecipients.tsx
Labels: cla-signed

#8995 docs(contracts): update docs path in contract doc generation pr script
  scripts/docs-contracts-pr.sh
Labels: cla-signed

#8999 fix(smart-contracts): `balanceOf` counts only valid keys
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/totalKeys.js
Labels: cla-signed, PublicLock v11

#8983 feat(smart-contracts): allow `extend` to update stored keyPrice
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/extendRenewable.js
Labels: cla-signed, PublicLock v11

#9007 feature(locksmith): Grant keys api
  locksmith/__tests__/controllers/v2/grantKeysController.test.ts
  locksmith/__tests__/fulfillment/dispatcher.test.ts
  locksmith/__tests__/test-helpers/utils.ts
  locksmith/src/controllers/v2/authController.ts
  locksmith/src/controllers/v2/grantKeysController.ts
  locksmith/src/fulfillment/dispatcher.ts
  locksmith/src/payment/paymentProcessor.ts
  locksmith/src/routes/index.ts
  locksmith/src/routes/v2/application.ts
  locksmith/src/routes/v2/auth.ts
  locksmith/src/routes/v2/grantKeys.ts
  locksmith/src/routes/v2/metadata.ts
  locksmith/src/routes/v2/verifier.ts
  locksmith/src/utils/keyPricer.ts
  locksmith/src/utils/middlewares/auth.ts
  locksmith/src/utils/middlewares/lockManager.ts
  locksmith/src/utils/middlewares/lockManagerOrKeyGranter.ts
Labels: cla-signed

#9009 feat(unlock-app): Add minting screen to the new checkout
  unlock-app/package.json
  unlock-app/scripts/getPaywallConfigURL.ts
  unlock-app/src/animations/minted.json
  unlock-app/src/animations/minting.json
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Container.tsx
  yarn.lock
Labels: cla-signed

#9002 feat(locksmith) - fix verifier endpoint middleware and tests
  locksmith/__tests__/controllers/v2/verifierController.test.ts
  locksmith/src/controllers/v2/verifierController.ts
  locksmith/src/routes/v2/verifier.ts
  locksmith/src/utils/middlewares/lockManager.ts
Labels: cla-signed

#9014 feature(locksmith): adding a controller to sign tokens so we can generate QR codes on the baclend
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/fulfillment/dispatcher.ts
  locksmith/src/routes/index.ts
  locksmith/src/routes/v2/ticket.ts
  locksmith/src/utils/middlewares/keyOwnerMiddleware.ts
Labels: cla-signed

#9018 fix(unlock-app): Reverse dynamic route because of next export limitations
  unlock-app/src/pages/verifiers.js
Labels: cla-signed

#9020 feat(locksmith) - add isVerifier function reusable
  locksmith/src/controllers/v2/verifierController.ts
Labels: cla-signed

#9015 feat(unlock-app): Add card screen to new checkout
  unlock-app/src/components/interface/checkout/alpha/Card.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/CardPayment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/MessageToSign.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/useCheckoutState.tsx
  unlock-app/src/hooks/useCards.ts
  unlock-app/src/index.css
Labels: cla-signed

#9011 feat(smart-contracts): prevent `transferFrom` from being used when a key manager is set
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/onKeyTransferHook.js
Labels: cla-signed, PublicLock v11

#9027 feat(unlock-app): Use xstate for managing checkout state
  unlock-app/.eslintignore
  unlock-app/package.json
  unlock-app/src/components/interface/checkout/alpha/Checkout/CardPayment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/MessageToSign.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Lock.tsx
  unlock-app/src/components/interface/checkout/alpha/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/checkoutMachine.typegen.ts
  unlock-app/src/components/interface/checkout/alpha/useCheckoutHeadContent.ts
  unlock-app/src/components/interface/checkout/alpha/useCheckoutState.tsx
  yarn.lock
Labels: cla-signed

#9026 refactor(locksmith): adding verifier operation
  locksmith/__tests__/controllers/v2/verifierController.test.ts
  locksmith/src/controllers/v2/verifierController.ts
  locksmith/src/operations/verifierOperations.ts
Labels: cla-signed

#9003 fix(smart-contracts): reset original price when a key is cancelled
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
Labels: cla-signed, PublicLock v11

#9028 fix(smart-contracts): add `_recordKeyPurchase` to `extend`
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/UnlockDiscountToken/mintingTokens.js
Labels: cla-signed, PublicLock v11

#9017 feat(smart-contracts): add support for custom referrer fee
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/setReferrerFee.js
Labels: cla-signed, PublicLock v11

#9033 chore(smart-contracts): remove all `.call` patterns from tests
  smart-contracts/test/Lock/Lock.js
  smart-contracts/test/Lock/behaviors/lockBehaviors.js
  smart-contracts/test/Lock/burn.js
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/disableTransfers.js
  smart-contracts/test/Lock/erc165.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/approveForAll.js
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/erc721/compliance.js
  smart-contracts/test/Lock/erc721/getApproved.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/tokenName.js
  smart-contracts/test/Lock/erc721/tokenSymbol.js
  smart-contracts/test/Lock/erc721/tokenURI.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/expireAndRefundFor.js
  smart-contracts/test/Lock/extend.js
  smart-contracts/test/Lock/freeTrial.js
  smart-contracts/test/Lock/getHasValidKey.js
  smart-contracts/test/Lock/grantKeyExtension.js
  smart-contracts/test/Lock/grantKeys.js
  smart-contracts/test/Lock/isValidKey.js
  smart-contracts/test/Lock/mergeKeys.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/permissions/beneficiary.js
  smart-contracts/test/Lock/permissions/isKeyManager.js
  smart-contracts/test/Lock/permissions/keyGranter.js
  smart-contracts/test/Lock/permissions/keyManager.js
  smart-contracts/test/Lock/permissions/setKeyManager.js
  smart-contracts/test/Lock/purchaseFor.js
  smart-contracts/test/Lock/purchaseMultiple.js
  smart-contracts/test/Lock/renewMembershipFor.js
  smart-contracts/test/Lock/shareKey.js
  smart-contracts/test/Lock/timeMachine.js
  smart-contracts/test/Lock/transferFee.js
  smart-contracts/test/Lock/updateKeyPricing.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/Unlock/behaviors/createLock.js
  smart-contracts/test/Unlock/lockTotalSales.js
  smart-contracts/test/unlockUtils.js
Labels: smart contract, cla-signed

#9025 feat(locksmith) - add mark as checkin for verifiers and lock manager endpoint
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/operations/metadataOperations.ts
  locksmith/src/routes/v2/ticket.ts
  locksmith/src/utils/middlewares/isVerifierMiddleware.ts
Labels: cla-signed

#9035 feat(unlock-app): Add unlock account sign in and up flow to new checkout
  unlock-app/src/components/interface/checkout/alpha/Bottom.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/CardPayment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/MessageToSign.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/UnlockAccountSignIn.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.typegen.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/UnlockAccountSignIn.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/connectMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Connect/connectMachine.typegen.ts
  unlock-app/src/components/interface/checkout/alpha/Connect/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Connected.tsx
  unlock-app/src/components/interface/checkout/alpha/Lock.tsx
  unlock-app/src/components/interface/checkout/alpha/Shell.tsx
  unlock-app/src/components/interface/checkout/alpha/SignInOrUp.tsx
  unlock-app/src/components/interface/checkout/alpha/UnlockAccount/EnterEmail.tsx
  unlock-app/src/components/interface/checkout/alpha/UnlockAccount/SignIn.tsx
  unlock-app/src/components/interface/checkout/alpha/UnlockAccount/SignUp.tsx
  unlock-app/src/components/interface/checkout/alpha/UnlockAccount/index.tsx
  unlock-app/src/components/interface/checkout/alpha/UnlockAccount/unlockAccountMachine.ts
  unlock-app/src/components/interface/checkout/alpha/UnlockAccount/unlockAccountMachine.typegen.ts
  unlock-app/src/components/interface/checkout/alpha/useCheckoutHeadContent.ts
  unlock-app/src/utils/withWalletService.tsx
Labels: cla-signed

#9039 feat(unlock-app) - Mark ticket as check in storage service
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9041 feat(unlock-app) - Add get verifier status storage service
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9038 feat(locksmith) - Add check verifier status endpoint
  locksmith/src/routes/v2/verifier.ts
Labels: cla-signed

#9044 feat(unlock-app): Add support for paying using credit card in the final confirmation screen of new checkout
  unlock-app/jest.config.js
  unlock-app/src/__tests__/components/interface/VerificationStatus.test.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/CardPayment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
Labels: cla-signed

#9042 feat(unlock-app) - SIWE integration & verifier on verification page
  unlock-app/src/components/interface/verification/Key.tsx
  unlock-app/src/hooks/useLock.ts
Labels: cla-signed

#9048 feat(unlock-app) - improve authentication siwe
  locksmith/src/controllers/v2/ticketsController.ts
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9051 feat(unlock-app) - Ticket verification locksmith, add keyGranter check
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/utils/signatures.ts
Labels: cla-signed

#9043 chore(smart-contracts): Remove some statements that were not rendered correctly in docs
  packages/contracts/deprec/V4/IPublicLockV4.sol
  packages/contracts/deprec/V5/IPublicLockV5.sol
  packages/contracts/deprec/V5/IUnlockV5.sol
  packages/contracts/deprec/V6/IPublicLockV6.sol
  packages/contracts/deprec/V6/IUnlockV6.sol
  packages/contracts/deprec/V7/IPublicLockV7.sol
  packages/contracts/deprec/V7/IPublicLockV7Sol6.sol
  packages/contracts/deprec/V7/IUnlockV7.sol
  packages/contracts/deprec/V8/IPublicLockV8.sol
  packages/contracts/deprec/V8/IPublicLockV8Sol6.sol
  packages/contracts/deprec/V8/IUnlockV8.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV10.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV4.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV5.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV6.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV7.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV7Sol6.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV8.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV8Sol6.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV8sol8.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV9.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV0.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV1.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV10.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV3.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV4.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV6.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV7.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV8.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV9.sol
  packages/contracts/src/contracts/Unlock/IUnlockV10.sol
  packages/contracts/src/contracts/Unlock/IUnlockV11.sol
  packages/contracts/src/contracts/Unlock/IUnlockV5.sol
  packages/contracts/src/contracts/Unlock/IUnlockV6.sol
  packages/contracts/src/contracts/Unlock/IUnlockV7.sol
  packages/contracts/src/contracts/Unlock/IUnlockV8.sol
  packages/contracts/src/contracts/Unlock/IUnlockV9.sol
  packages/contracts/src/contracts/Unlock/UnlockV0.sol
  packages/contracts/src/contracts/Unlock/UnlockV1.sol
  packages/contracts/src/contracts/Unlock/UnlockV10.sol
  packages/contracts/src/contracts/Unlock/UnlockV11.sol
  packages/contracts/src/contracts/Unlock/UnlockV3.sol
  packages/contracts/src/contracts/Unlock/UnlockV4.sol
  packages/contracts/src/contracts/Unlock/UnlockV6.sol
  packages/contracts/src/contracts/Unlock/UnlockV7.sol
  packages/contracts/src/contracts/Unlock/UnlockV8.sol
  packages/contracts/src/contracts/Unlock/UnlockV9.sol
  packages/contracts/src/index.ts
  packages/eslint-config/src/base.js
  packages/unlock-js/src/types.ts
  packages/unlock-js/src/walletService.ts
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/scripts/deployments/template.js
  smart-contracts/test/Lock/grantKeyExtension.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/soldOut.js
  smart-contracts/test/Lock/totalKeys.js
Labels: cla-signed

#9049 feat(unlock-app): Add captcha screen to new checkout
  unlock-app/src/components/interface/checkout/alpha/Checkout/Captcha.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Connected.tsx
  unlock-app/src/components/interface/checkout/alpha/Lock.tsx
Labels: cla-signed

#9050 feat(unlock-app): Add close button and emit transaction info in new checkout
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/index.tsx
Labels: cla-signed

#9032 chore(smart-contracts): remove `hardlydifficult` from test suite
  smart-contracts/scripts/deployments/oracle.js
  smart-contracts/scripts/deployments/weth.js
  smart-contracts/test/Lock/approveBeneficiary.js
  smart-contracts/test/Lock/behaviors/lockBehaviors.js
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/extend.js
  smart-contracts/test/Lock/extendRenewable.js
  smart-contracts/test/Lock/gasRefund.js
  smart-contracts/test/Lock/purchaseMultiple.js
  smart-contracts/test/Lock/purchaseTip.js
  smart-contracts/test/Lock/renewMembershipFor.js
  smart-contracts/test/Lock/updateKeyPricing.js
  smart-contracts/test/Lock/withdrawByAddress.js
  smart-contracts/test/Unlock/behaviors/UnlockProxy.js
  smart-contracts/test/Unlock/createLockLegacy.js
  smart-contracts/test/Unlock/uniswapValue.js
  smart-contracts/test/UnlockDiscountToken/mintingTokens.js
  smart-contracts/test/UnlockDiscountToken/transferingTokens.js
  smart-contracts/test/UnlockDiscountToken/upgrades.js
  smart-contracts/test/helpers/ABIs/UniswapOracle.json
  smart-contracts/test/helpers/ABIs/weth.json
  smart-contracts/test/helpers/constants.js
  smart-contracts/test/helpers/index.js
  smart-contracts/test/helpers/tokens.js
  smart-contracts/test/helpers/uniswap.js
  smart-contracts/test/test-artifacts/Uniswap.js
Labels: smart contract, cla-signed

#9054 feat(locksmith) - generate QRcode and send it by email
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/package.json
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/operations/wedlocksOperations.ts
  locksmith/src/routes/v2/ticket.ts
  locksmith/src/utils/qrcode.ts
  locksmith/src/websub/jobs/keys.ts
  yarn.lock
Labels: cla-signed

#9061 feat(unlock-app) - fix ticketing check-in
  unlock-app/src/components/interface/verification/Key.tsx
  unlock-app/src/hooks/useLock.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9040 fix(smart-contracts): `purchaseKeys` test helper
  smart-contracts/test/Lock/approveBeneficiary.js
  smart-contracts/test/Lock/burn.js
  smart-contracts/test/Lock/cancelAndRefund.js
  smart-contracts/test/Lock/disableTransfers.js
  smart-contracts/test/Lock/erc20.js
  smart-contracts/test/Lock/erc721/approve.js
  smart-contracts/test/Lock/erc721/approveForAll.js
  smart-contracts/test/Lock/erc721/balanceOf.js
  smart-contracts/test/Lock/erc721/enumerable.js
  smart-contracts/test/Lock/erc721/ownerOf.js
  smart-contracts/test/Lock/erc721/safeTransferFrom.js
  smart-contracts/test/Lock/erc721/tokenURI.js
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/erc721/uniqueTokenIds.js
  smart-contracts/test/Lock/expireAndRefundFor.js
  smart-contracts/test/Lock/extend.js
  smart-contracts/test/Lock/extendRenewable.js
  smart-contracts/test/Lock/freeTrial.js
  smart-contracts/test/Lock/getHasValidKey.js
  smart-contracts/test/Lock/hooks/erc1155BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc20BalanceOfHook.js
  smart-contracts/test/Lock/hooks/erc721BalanceOfHook.js
  smart-contracts/test/Lock/isValidKey.js
  smart-contracts/test/Lock/maxKeysPerAddress.js
  smart-contracts/test/Lock/mergeKeys.js
  smart-contracts/test/Lock/nonExpiring.js
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/onTokenURIHook.js
  smart-contracts/test/Lock/onValidKeyHook.js
  smart-contracts/test/Lock/owners.js
  smart-contracts/test/Lock/permissions/keyManager.js
  smart-contracts/test/Lock/renewMembershipFor.js
  smart-contracts/test/Lock/setExpirationDuration.js
  smart-contracts/test/Lock/setMaxNumberOfKeys.js
  smart-contracts/test/Lock/setReferrerFee.js
  smart-contracts/test/Lock/shareKey.js
  smart-contracts/test/Lock/soldOut.js
  smart-contracts/test/Lock/timeMachine.js
  smart-contracts/test/Lock/transfer.js
  smart-contracts/test/Lock/transferFee.js
  smart-contracts/test/Lock/withdraw.js
  smart-contracts/test/Unlock/lockTotalSales.js
  smart-contracts/test/Unlock/resetTrackedValue.js
  smart-contracts/test/helpers/ABIs/IUniswapOracle.json
  smart-contracts/test/helpers/index.js
  smart-contracts/test/helpers/lock.js
Labels: cla-signed

#9072 fix(ci): stop smart contracts coverage from running on all PRs
  .github/workflows/pull-request.yml
Labels: cla-signed

#9059 chore(smart-contracts): remove custom hardhat error messages
  smart-contracts/test/Lock/grantKeys.js
  smart-contracts/test/Lock/initializers.js
  smart-contracts/test/Unlock/initializers.js
  smart-contracts/test/UnlockDiscountToken/UnlockDiscountToken.js
  smart-contracts/test/UnlockDiscountToken/governor.js
  smart-contracts/test/UnlockDiscountToken/upgrades.mainnet.js
  smart-contracts/test/helpers/constants.js
  smart-contracts/test/helpers/errors.js
  smart-contracts/test/mainnet/udt.js
Labels: smart contract, cla-signed

#9037 fix(smart-contracts): allow to share key with self
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/shareKey.js
  smart-contracts/test/Lock/transfer.js
Labels: smart contract, cla-signed

#9075 feat(unlokc-app) - expire and refund should always be visible but disabled if key expired
  unlock-app/src/components/interface/MetadataTable.tsx
Labels: cla-signed

#9074 feat(unlock-app) - handle text overflow in toast helper
  unlock-app/src/components/helpers/toast.helper.ts
Labels: cla-signed

#9077 feat(unlock-app) - refresh members page ui
  unlock-app/src/__tests__/components/interface/MetadataTable.test.tsx
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/utils/strings.ts
Labels: cla-signed

#9066 replace eth-sig-utils and ethereumjs-utils with ethers in locksmith
  locksmith/__tests__/controllers/lockController.test.js
  locksmith/__tests__/controllers/metadataController/readAddressHolderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/requestingKeyholderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/requestingTokenMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/tokenData.test.ts
  locksmith/__tests__/controllers/metadataController/updateAddressHolderMetadata.test.ts
  locksmith/__tests__/controllers/metadataController/updateDefaults.test.ts
  locksmith/__tests__/controllers/metadataController/updateKeyMetadata.test.ts
  locksmith/__tests__/controllers/purchaseController.test.ts
  locksmith/__tests__/controllers/transactionController.test.js
  locksmith/__tests__/controllers/userController/cards.test.ts
  locksmith/__tests__/controllers/userController/ejection.test.ts
  locksmith/__tests__/controllers/userController/emailUpdate.test.ts
  locksmith/__tests__/controllers/userController/passwordEncryptedPrivateKey.test.ts
  locksmith/__tests__/controllers/userController/paymentDetails.test.ts
  locksmith/__tests__/controllers/userController/privateKey.test.ts
  locksmith/__tests__/controllers/userController/recoveryPhrase.test.ts
  locksmith/__tests__/controllers/userController/userCreation.test.ts
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/__tests__/data/lockOwnership.test.ts
  locksmith/__tests__/operations/lockOperations.test.js
  locksmith/__tests__/operations/transactionOperations.test.js
  locksmith/__tests__/operations/userMetadataOperations.test.ts
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/__tests__/signatureValidation/signPersonal.test.ts
  locksmith/__tests__/signatureValidation/typedData.test.ts
  locksmith/__tests__/test-helpers/typeDataGenerators.ts
  locksmith/__tests__/utils/keyPricer.test.ts
  locksmith/config/config.js
  locksmith/package.json
  locksmith/scripts/connectedPurchase.ts
  locksmith/scripts/metadataUpload/metadata_upload.ts
  locksmith/scripts/metadataUpload/user_metadata_upload.ts
  locksmith/src/controllers/lockController.js
  locksmith/src/middlewares/signatureValidationMiddleware.ts
  locksmith/src/operations/lockOperations.ts
  locksmith/src/operations/transactionOperations.ts
  locksmith/src/utils/normalizer.ts
  locksmith/src/utils/signature.ts
  yarn.lock
Labels: cla-signed

#9079 feat(unlock-app) - verifiers should see metadata when scanning qr code
  locksmith/src/controllers/v2/metadataController.ts
  locksmith/src/operations/metadataOperations.ts
  locksmith/src/operations/verifierOperations.ts
  locksmith/src/utils/middlewares/isVerifierMiddleware.ts
  unlock-app/src/components/interface/verification/Key.tsx
  unlock-app/src/hooks/useLock.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9084 feat(locksmith) - only keyManager should call send-email API
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/src/routes/v2/ticket.ts
Labels: cla-signed

#9085 feat(unlock-app): Add progress indicator on the checkout head
  packages/unlock-assets/build/svg-component/RocketLaunch.js
  packages/unlock-assets/build/svg-component/index.js
  packages/unlock-assets/dist/index.js
  packages/unlock-assets/dist/index.js.map
  packages/unlock-assets/dist/index.modern.js
  packages/unlock-assets/dist/index.modern.js.map
  packages/unlock-assets/images/svg/rocketLaunch.svg
  packages/unlock-assets/src/SvgComponents.js
  unlock-app/src/components/interface/checkout/alpha/Checkout/Captcha.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/CardPayment.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/MessageToSign.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Metadata.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/UnlockAccountSignIn.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/Confirm.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/UnlockAccountSignIn.tsx
  unlock-app/src/components/interface/checkout/alpha/Connect/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Progress.tsx
  unlock-app/src/components/interface/checkout/alpha/Shell.tsx
  unlock-app/src/components/interface/checkout/alpha/useCheckoutHeadContent.ts
Labels: cla-signed

#9087 feat: remove eth-sig-util and ethereumjs-util from unlock-app
  unlock-app/package.json
  unlock-app/src/__tests__/hooks/useCards.test.ts
  unlock-app/src/__tests__/hooks/useMembers.test.js
  unlock-app/src/__tests__/services/unlockProvider.test.js
  unlock-app/src/__tests__/structured_data/keyMetadataTypedData.test.ts
  unlock-app/src/__tests__/utils/signatures.test.js
  unlock-app/src/components/content/RecoverContent.tsx
  unlock-app/src/hooks/useAccount.ts
  unlock-app/src/hooks/useCards.ts
  unlock-app/src/hooks/useMembers.js
  unlock-app/src/services/unlockProvider.ts
  unlock-app/src/structured_data/ejectionRequest.js
  unlock-app/src/structured_data/keyHolderMetadata.js
  unlock-app/src/structured_data/keyMetadata.js
  unlock-app/src/structured_data/keyMetadataTypedData.ts
  unlock-app/src/structured_data/unlockLock.js
  unlock-app/src/structured_data/unlockPaymentDetails.js
  unlock-app/src/structured_data/unlockPurchaseRequest.js
  unlock-app/src/structured_data/unlockUser.js
  unlock-app/src/utils/signatures.ts
Labels: cla-signed

#9091 feat(locksmith) - get lock address metadata by lock address
  locksmith/__tests__/controllers/v2/metadataController.test.ts
  locksmith/src/controllers/v2/metadataController.ts
  locksmith/src/routes/v2/metadata.ts
Labels: cla-signed

#9090 fix(smart-contracts): use OZ to show implementation address in cli
  smart-contracts/hardhat.config.js
  smart-contracts/scripts/deployments/unlock.js
  smart-contracts/tasks/impl.js
  smart-contracts/tasks/utils.js
Labels: smart contract

#9093 fix(unlock-protocol-com): more links fixed
  unlock-protocol-com/blog/bring-your-own-nft.md
  unlock-protocol-com/src/components/interface/Footer/index.tsx
  unlock-protocol-com/src/components/interface/Navigation/index.tsx
  unlock-protocol-com/src/components/pages/Home/sections/Recipes.tsx
Labels: cla-signed

#9097 ci(tests): add PR manual command to run all tests
  .github/workflows/commands.yml
Labels: cla-signed

#9104 feat(unlock-app): Add return user screen to new checkout
  unlock-app/scripts/getPaywallConfigURL.ts
  unlock-app/src/animations/unlocked.json
  unlock-app/src/components/interface/checkout/alpha/Checkout/Minting.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Quantity.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Returning.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
  unlock-app/src/components/interface/checkout/alpha/Lock.tsx
  unlock-app/src/components/interface/checkout/alpha/Progress.tsx
  unlock-app/src/components/interface/checkout/alpha/useCheckoutHeadContent.ts
Labels: cla-signed

#9102 feat(locksmith ) - refactor bulk metadata with merged fields
  locksmith/__tests__/controllers/v2/metadataController.test.ts
  locksmith/src/controllers/v2/metadataController.ts
  locksmith/src/operations/lockOperations.ts
  locksmith/src/routes/v2/metadata.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9099 feat(unlock-app) - add checkin time in members page
  unlock-app/src/__tests__/hooks/useMembers.test.js
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/hooks/useMembers.js
Labels: cla-signed

#9013 feat(smart-contracts): add `lendKey`
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/erc721/transferFrom.js
  smart-contracts/test/Lock/lendKey.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/permissions/setKeyManager.js
Labels: smart contract, cla-signed, PublicLock v11

#9107 feat(unlock-app) - refactor use members in ts
  unlock-app/src/hooks/useMembers.ts
Labels: cla-signed

#9110 feat(unlock-app) - hotfix account undefined
  unlock-app/src/components/content/MembersContent.tsx
Labels: cla-signed
