Repository unlock-protocol/unlock, pull requests merged in 2022-07, with the labels that each got.

#9092 feat(smart-contracts): task to verify a public lock template at version
  smart-contracts/scripts/verify-proxy.js
  smart-contracts/tasks/verify.js
Labels: smart contract

#9112 feat(unlock-app) - show metadata only if check in time exists
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
Labels: cla-signed

#9111 Ccarfi nyc22 wrapup
  unlock-protocol-com/blog/nftnyc-wrapup-2022.md
  unlock-protocol-com/public/images/blog/nyc22/DAONYC-min.png
  unlock-protocol-com/public/images/blog/nyc22/ethnewyork.png
  unlock-protocol-com/public/images/blog/nyc22/gard3n.png
  unlock-protocol-com/public/images/blog/nyc22/granted.png
  unlock-protocol-com/public/images/blog/nyc22/nfticket-min.gif
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet1.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet2.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet3.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet4.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet5.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet6.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet7.jpg
  unlock-protocol-com/public/images/blog/nyc22/nftnyc-tweet8.jpg
  unlock-protocol-com/public/images/blog/nyc22/nyc-cover-image-2022.jpeg
  unlock-protocol-com/public/images/blog/nyc22/vibesIRL-min.png
Labels: cla-signed

#9036 feat(smart-contracts): introduces `unlendKey`
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinTransfer.sol
  smart-contracts/test/Lock/unlendKey.js
Labels: smart contract, cla-signed, PublicLock v11

#9108 feature(unlock-app) : Generate qr
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/config/config.js
  locksmith/package.json
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/routes/v2/ticket.ts
  locksmith/src/utils/middlewares/auth.ts
  locksmith/src/utils/middlewares/keyOwnerMiddleware.ts
  locksmith/src/utils/qrcode.ts
Labels: cla-signed

#9113 feat(unlock-app) - members page actions position & style update
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
Labels: cla-signed

#9156 Revert "chore(deps): update paywall-app (#9147)"
  paywall-app/package.json
  yarn.lock
Labels: cla-signed

#9154 feat(unlock-app) - mark ticket as checked in from members page
  unlock-app/src/__tests__/hooks/useMembers.test.js
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/hooks/useMembers.ts
Labels: cla-signed

#9159 fix(unlock-app): Arrayify data before signing with signMessage in personal_sign method in unlock provider
  unlock-app/src/__tests__/services/unlockProvider.test.js
  unlock-app/src/services/unlockProvider.ts
Labels: cla-signed

#9170 feat(smart-contracts): contract time helper
  smart-contracts/test/helpers/index.js
  smart-contracts/test/helpers/time.js
Labels: smart contract, cla-signed

#9173 feat(unlock-app) - fix query column name with correct one
  locksmith/__tests__/controllers/v2/metadataController.test.ts
  locksmith/src/controllers/v2/metadataController.ts
  locksmith/src/operations/metadataOperations.ts
  locksmith/src/utils/keyData.ts
Labels: cla-signed

#9174 feat(unlock-app) - Optimize members page checkin
  locksmith/src/controllers/v2/metadataController.ts
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/hooks/useMembers.ts
Labels: cla-signed

#9177 feat(unlock-app) - show checked in status without login
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/Key.tsx
Labels: cla-signed

#9096 doc(smart-contracts): docs to deploy the protocol on a new network
  smart-contracts/README.md
Labels: smart contract, cla-signed

#9185 feat(locksmith) - bulk metadata refactor to include all metadata
  locksmith/src/controllers/v2/metadataController.ts
  locksmith/src/operations/lockOperations.ts
Labels: cla-signed

#9186 feat(unlock-app) - show metadata toggle button only for lockManager
  unlock-app/src/__tests__/utils/duration.test.js
  unlock-app/src/components/interface/members/MemberCard.tsx
Labels: cla-signed

#9191 feat(contracts): add hooks interfaces in the contracts package
  packages/contracts/src/contracts/Hooks/ILockKeyCancelHook.sol
  packages/contracts/src/contracts/Hooks/ILockKeyPurchaseHook.sol
  packages/contracts/src/contracts/Hooks/ILockKeyTransferHook.sol
  packages/contracts/src/contracts/Hooks/ILockTokenURIHook.sol
  packages/contracts/src/contracts/Hooks/ILockValidKeyHook.sol
  packages/contracts/src/contracts/PublicLock/ILockKeyCanacelHookV7.sol
  packages/contracts/src/contracts/PublicLock/ILockKeyPurchaseHookV7.sol
Labels: cla-signed

#9184 feat(unlock-protocol-com): Add blog post for redesigned checkout
  unlock-protocol-com/blog/redesigning-our-checkout.md
  unlock-protocol-com/public/images/blog/new-checkout-add-card.png
  unlock-protocol-com/public/images/blog/new-checkout-confirmation.png
  unlock-protocol-com/public/images/blog/new-checkout-finished.png
  unlock-protocol-com/public/images/blog/new-checkout-metadata.png
  unlock-protocol-com/public/images/blog/new-checkout-minting.png
  unlock-protocol-com/public/images/blog/new-checkout-quantity.jpg
  unlock-protocol-com/public/images/blog/new-checkout-unlock-account.png
  unlock-protocol-com/public/images/blog/new-checkout.jpg
  unlock-protocol-com/public/images/blog/redesigned-checkout/checkout-experience.mp4
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-add-card.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-confirmation.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-finished.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-metadata.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-minting.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-quantity.jpg
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-unlock-account.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/sign-in-with-ethereum.mp4
Labels: cla-signed

#9202 fix(smart-contract-extensions): correct hooks path from contracts packages
  smart-contract-extensions/contracts/hooks/CodeRequiredHook.sol
  smart-contract-extensions/contracts/hooks/DiscountCodeHook.sol
Labels: cla-signed

#9192 feat(unlock-app): Stop asking user to sign in repeatedly
  unlock-app/src/hooks/useProvider.ts
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9207 fix(unlock-app): Silently fail if there are any errors in logging out
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9205 feat(unlock-app) - Send QR-code to email metadata
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/operations/wedlocksOperations.ts
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/services/storageService.ts
  unlock-app/src/utils/signatures.ts
Labels: cla-signed

#9189 fix(contracts): reorganize generated docs
  packages/contracts/.gitignore
  packages/contracts/bin/build_docs.sh
  packages/contracts/package.json
  scripts/docs-contracts-pr.sh
Labels: Documentation, smart contract, cla-signed

#9214 feat(unlock-app)- keys grouped by network
  unlock-app/src/components/interface/keychain/KeyDetails.tsx
Labels: cla-signed

#9209 feat(wedlocks) - nft email confirmation template
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/src/operations/wedlocksOperations.ts
  packages/networks/src/networks/bsc.ts
  packages/networks/src/networks/goerli.ts
  packages/networks/src/networks/index.ts
  packages/networks/src/networks/localhost.ts
  packages/networks/src/networks/mainnet.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/src/networks/optimism.ts
  packages/networks/src/networks/optimisticKovan.ts
  packages/networks/src/networks/polygon.ts
  packages/networks/src/networks/rinkeby.ts
  packages/networks/src/networks/xdai.ts
  packages/types/src/types/unlockTypes.ts
  wedlocks/src/__tests__/templates/keyMined.test.js
  wedlocks/src/templates/keyMined.js
Labels: cla-signed

#9216 Production Deploy
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/operations/wedlocksOperations.ts
  packages/contracts/.gitignore
  packages/contracts/bin/build_docs.sh
  packages/contracts/package.json
  packages/contracts/src/contracts/Hooks/ILockKeyCancelHook.sol
  packages/contracts/src/contracts/Hooks/ILockKeyPurchaseHook.sol
  packages/contracts/src/contracts/Hooks/ILockKeyTransferHook.sol
  packages/contracts/src/contracts/Hooks/ILockTokenURIHook.sol
  packages/contracts/src/contracts/Hooks/ILockValidKeyHook.sol
  packages/contracts/src/contracts/PublicLock/ILockKeyCanacelHookV7.sol
  packages/contracts/src/contracts/PublicLock/ILockKeyPurchaseHookV7.sol
  packages/networks/src/networks/bsc.ts
  packages/networks/src/networks/goerli.ts
  packages/networks/src/networks/index.ts
  packages/networks/src/networks/localhost.ts
  packages/networks/src/networks/mainnet.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/src/networks/optimism.ts
  packages/networks/src/networks/optimisticKovan.ts
  packages/networks/src/networks/polygon.ts
  packages/networks/src/networks/rinkeby.ts
  packages/networks/src/networks/xdai.ts
  packages/types/src/types/unlockTypes.ts
  scripts/docs-contracts-pr.sh
  scripts/manual-production-pr.sh
  smart-contract-extensions/contracts/hooks/CodeRequiredHook.sol
  smart-contract-extensions/contracts/hooks/DiscountCodeHook.sol
  smart-contracts/.openzeppelin/goerli.json
  unlock-app/src/__tests__/utils/duration.test.js
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/keychain/KeyDetails.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/hooks/useProvider.ts
  unlock-app/src/services/storageService.ts
  unlock-app/src/utils/signatures.ts
  unlock-protocol-com/blog/redesigning-our-checkout.md
  unlock-protocol-com/public/images/blog/new-checkout-add-card.png
  unlock-protocol-com/public/images/blog/new-checkout-confirmation.png
  unlock-protocol-com/public/images/blog/new-checkout-finished.png
  unlock-protocol-com/public/images/blog/new-checkout-metadata.png
  unlock-protocol-com/public/images/blog/new-checkout-minting.png
  unlock-protocol-com/public/images/blog/new-checkout-quantity.jpg
  unlock-protocol-com/public/images/blog/new-checkout-unlock-account.png
  unlock-protocol-com/public/images/blog/new-checkout.jpg
  unlock-protocol-com/public/images/blog/redesigned-checkout/checkout-experience.mp4
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-add-card.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-confirmation.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-finished.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-metadata.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-minting.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-quantity.jpg
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout-unlock-account.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/new-checkout.png
  unlock-protocol-com/public/images/blog/redesigned-checkout/sign-in-with-ethereum.mp4
  wedlocks/src/__tests__/templates/keyMined.test.js
  wedlocks/src/templates/keyMined.js
Labels: cla-signed

#9073 feat(smart-contracts): script to automate gnosis setup
  smart-contracts/README.md
  smart-contracts/package.json
  smart-contracts/scripts/multisig/_helpers.js
  smart-contracts/scripts/multisig/create.js
  smart-contracts/scripts/multisig/existing.js
  smart-contracts/scripts/multisig/index.js
  smart-contracts/scripts/multisig/owners.js
  smart-contracts/scripts/multisig/submitTx.js
  smart-contracts/scripts/multisig/transferOwnership.js
  smart-contracts/scripts/upgrade/propose.js
  smart-contracts/tasks/gnosis.js
  smart-contracts/test/helpers/deployLocks.js
  smart-contracts/test/helpers/index.js
  smart-contracts/test/helpers/multisig.js
  smart-contracts/test/mainnet/udt.js
  smart-contracts/test/scripts/gnosis.mainnet.js
  yarn.lock
Labels: smart contract, cla-signed

#9220 feat(smart-contracts): add custom duration to `grantKeyExtension`
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/grantKeyExtension.js
Labels: cla-signed

#9218 feat(unlock-app): Redesign ticket membership card for verification page
  unlock-app/jest.config.js
  unlock-app/package.json
  unlock-app/src/__tests__/components/content/VerificationContent.test.tsx
  unlock-app/src/__tests__/components/interface/VerificationStatus.test.tsx
  unlock-app/src/components/content/LoginContent.tsx
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/components/interface/Account.tsx
  unlock-app/src/components/interface/Header.js
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  unlock-app/src/components/interface/verification/invalidMembership.ts
  unlock-app/src/utils/verification.ts
  yarn.lock
Labels: cla-signed

#9217 feat(unlock-app): Add qr scanner for tickets
  unlock-app/package.json
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/components/interface/Account.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
  unlock-app/src/components/interface/verification/invalidMembership.ts
  unlock-app/src/services/storageService.ts
  unlock-app/src/utils/verification.ts
  yarn.lock
Labels: cla-signed

#9228 fix(contracts): release interface when packaging contracts
  smart-contracts/tasks/release.js
Labels: smart contract, cla-signed

#9232 fix(unlock-app): Avoid double adding the base in the URL for check in method
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9230 feat(unlock-app) - redirect after login
  unlock-app/src/components/content/LoginContent.tsx
Labels: cla-signed

#9225 fix(locksmith): Return correct key expiration date from KeyData
  locksmith/src/utils/keyData.ts
Labels: cla-signed

#9183 feat(unlock): Add network description to network package and use those in checkout
  packages/networks/src/networks/bsc.ts
  packages/networks/src/networks/localhost.ts
  packages/networks/src/networks/mainnet.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/src/networks/optimism.ts
  packages/networks/src/networks/optimisticKovan.ts
  packages/networks/src/networks/polygon.ts
  packages/networks/src/networks/rinkeby.ts
  packages/networks/src/networks/xdai.ts
  packages/types/src/types/unlockTypes.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/Select.tsx
Labels: cla-signed

#9233 fix(unlock-app): Remove check in function from getEndpoint wrapper
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9227 feature(unlock-app): adding ethpass for ethcc locks
  unlock-app/src/__tests__/components/interface/keychain/QRModal.test.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/QRModal.tsx
Labels: cla-signed

#9237 feature(wedlocks) Ethcc ticket email
  wedlocks/src/templates/ethccTicket.js
Labels: cla-signed

#9236 feat(unlock-app) - change card color when ticket is checked in
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
Labels: cla-signed

#9240 feat(unlock-app) - fix filter members
  unlock-app/src/hooks/useMembers.ts
Labels: cla-signed

#9238 feat(unlock-app): Use different qr scanner library for verification page
  unlock-app/package.json
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
  unlock-app/src/components/interface/verification/invalidMembership.ts
  unlock-app/src/utils/verification.ts
  yarn.lock
Labels: cla-signed

#9242 feat(unlock-app) - members page doesnt display address with multiple keys
  unlock-app/src/__tests__/hooks/useMembers.test.js
  unlock-app/src/hooks/useMembers.ts
Labels: cla-signed

#9239 feat(unlock-app) - add ability to copy key holder address
  unlock-app/src/components/interface/members/MemberCard.tsx
Labels: cla-signed

#9253 feat(unlock-app): Increase text size on the membership card title
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
Labels: cla-signed

#9252 Update index.tsx
  unlock-protocol-com/src/components/interface/Navigation/index.tsx
Labels: cla-signed

#9255 Ccarfi june product blog
  unlock-protocol-com/blog/jun-22-update.md
  unlock-protocol-com/public/images/blog/june-22-update/june-22-banner.png
Labels: cla-signed

#9254 feat(unlock-app): Add temporary badge component for ethCC
  unlock-app/src/components/interface/verification/MembershipCard.tsx
Labels: cla-signed

#9249 feat(unlock-app) - add explicit button to scan next ticket
  unlock-app/src/components/content/VerificationContent.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
Labels: cla-signed

#9251 breaking(locksmith): Return http error if ticket already checked in when checking in again
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/src/controllers/v2/ticketsController.ts
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/members/MemberCard.tsx
Labels: cla-signed

#9263 feat(unlock-app) - fix query search by owner if uppercase
  unlock-app/src/services/graphService.ts
Labels: cla-signed

#9261 feat(unlock-app) - promt error on unexpected errors
  unlock-app/src/hooks/useMembers.ts
Labels: cla-signed

#9262 fix(unlock-app): Show scan-another button always + add close button to membership card on verification page
  unlock-app/src/components/interface/Account.tsx
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
Labels: cla-signed

#9267 fix(unlock-app): Compare lower case address only for adding badge
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
Labels: cla-signed

#9265 feat(unlock-app) - move active filter to dropdown
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/hooks/useMembers.ts
  unlock-app/src/queries/keyholdersByKeyId.js
  unlock-app/src/queries/keyholdersByLock.js
  unlock-app/src/services/graphService.ts
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#9269 Production Deploy
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
Labels: cla-signed

#9285 feat(unlock-protocol-com) - show card title on mobile
  unlock-protocol-com/src/components/pages/Home/sections/Connect.tsx
Labels: cla-signed

#9080 refactor(all): standardize use of single fetch package
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/package.json
  locksmith/src/controllers/hookController.ts
  locksmith/src/operations/wedlocksOperations.ts
  locksmith/src/utils/lockManagers.ts
  locksmith/src/websub/helpers/notify.ts
  package.json
  packages/paywall/package.json
  smart-contracts/package.json
  smart-contracts/scripts/lock/listManagers.js
  unlock-app/package.json
  unlock-app/src/__tests__/hooks/useMetadata.test.js
  unlock-app/src/__tests__/services/wedlockService.test.js
  unlock-app/src/hooks/useAccount.ts
  unlock-app/src/hooks/useMetadata.js
  unlock-app/src/services/storageService.ts
  unlock-app/src/services/wedlockService.ts
  yarn.lock
Labels: cla-signed

#9286 Ccarfi blog ethcc tickets
  unlock-protocol-com/blog/ethcc5-2022-ticketing.md
  unlock-protocol-com/public/images/blog/ethcc5/checkin1-min.png
  unlock-protocol-com/public/images/blog/ethcc5/checkin2-min.png
  unlock-protocol-com/public/images/blog/ethcc5/checkin3-min.png
  unlock-protocol-com/public/images/blog/ethcc5/checkin4-min.png
  unlock-protocol-com/public/images/blog/ethcc5/checkin5-min.png
  unlock-protocol-com/public/images/blog/ethcc5/checkin6-min.png
  unlock-protocol-com/public/images/blog/ethcc5/ethcc-stage.png
  unlock-protocol-com/public/images/blog/ethcc5/ethcc-stairway.png
  unlock-protocol-com/public/images/blog/ethcc5/maison-de-la-mutau.jpg
  unlock-protocol-com/public/images/blog/ethcc5/ticket-qr-code.png
  unlock-protocol-com/public/images/blog/ethcc5/two-phones-min.png
Labels: cla-signed

#9275 feat(unlock-app)- query for all keys (expired + active)
  unlock-app/src/__tests__/components/interface/MetadataTable.test.tsx
  unlock-app/src/__tests__/hooks/useMembers.test.js
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/hooks/useMembers.ts
  unlock-app/src/queries/keyListByLock.ts
  unlock-app/src/queries/keyholdersByLock.ts
  unlock-app/src/services/graphService.ts
  unlock-app/src/unlockTypes.ts
Labels: cla-signed

#9292 feat(paywall): Add support for loading alpha flagged checkout
  packages/paywall/src/Paywall.ts
  packages/paywall/src/urls.ts
  unlock-app/src/pages/alpha/checkout.tsx
Labels: cla-signed

#9291 feat(unlock-app ) - show members count on the members page
  unlock-app/src/components/content/MembersContent.tsx
  unlock-app/src/components/interface/MetadataTable.tsx
  unlock-app/src/hooks/useMembers.ts
  unlock-app/src/queries/keysCount.ts
  unlock-app/src/queries/locksByManager.js
  unlock-app/src/services/graphService.ts
Labels: cla-signed

#9301 fix(unlock-app): Do not show please sign the message on unlock account on connect flow
  unlock-app/src/components/interface/checkout/alpha/Connect/Confirm.tsx
Labels: cla-signed

#9303 fix(unlock-app): React to config changes passed via paywall events
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/checkoutMachine.typegen.ts
  unlock-app/src/components/interface/checkout/alpha/Checkout/index.tsx
Labels: cla-signed

#9287 feat(locksmith) - make lock name required to included it in email
  locksmith/__tests__/controllers/v2/ticketsController.test.ts
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/src/controllers/v2/ticketsController.ts
  locksmith/src/operations/wedlocksOperations.ts
Labels: cla-signed

#9276 fix(unlock-app): Handle an edge case where QR code urls have double encoded the data and missing tokenId
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/components/interface/verification/invalidMembership.ts
  unlock-app/src/utils/verification.ts
  yarn.lock
Labels: cla-signed

#9300 feat(smart-contracts): deploy new lock template and submit txs
  smart-contracts/scripts/deployments/template.js
  smart-contracts/scripts/multisig/submitTx.js
  smart-contracts/scripts/upgrade/submitLockVersion.js
  smart-contracts/tasks/upgrade.js
  smart-contracts/test/helpers/multisig.js
Labels: cla-signed

#9298 chore(ci): using github action to run automated deploys
  .github/workflows/weekly-prod-pr.yml
  scripts/automated-production-pr.sh
Labels: cla-signed

#9310 feat(unlock-protocol-com) - missingbroken links on homepage
  unlock-app/package.json
  unlock-protocol-com/package.json
  unlock-protocol-com/src/components/pages/Home/sections/Connect.tsx
  yarn.lock
Labels: cla-signed

#9299 feat(unlock-app) - add email from aidrop page
  packages/ui/public/unlock-tailwind-preset.js
  unlock-app/src/components/creator/members/GrantKeysDrawer.tsx
  unlock-app/src/components/interface/Drawer.tsx
Labels: cla-signed

#9315 feat(unlock-protocol-com) - slider homepage improvements
  unlock-protocol-com/src/components/pages/Home/sections/Connect.tsx
Labels: cla-signed

#9302 feat(unlock-app)- add or update email from members page
  unlock-app/jest.config.js
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9318 feat(unlock-app) - fix stripe storageService stripe connect function
  unlock-app/src/services/storageService.ts
Labels: cla-signed

#9320 feat(unlock-app) - add email description for airdrop
  unlock-app/src/components/creator/members/GrantKeysDrawer.tsx
Labels: cla-signed

#9316 feat(unlock-app) - show metadata in keychain page
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/KeyMetadataModal.tsx
Labels: cla-signed

#9327 feat(unlock-app) - fix pagination and update style
  unlock-app/src/components/content/MembersContent.tsx
Labels: cla-signed

#9333 docs: adding param details for approveBeneficiary
  packages/contracts/deprec/V8/IPublicLockV8.sol
  packages/contracts/deprec/V8/IPublicLockV8Sol6.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV11.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV8.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV8sol8.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV9.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV10.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV11.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV8.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV9.sol
  packages/contracts/src/contracts/Unlock/UnlockV10.sol
  packages/contracts/src/contracts/Unlock/UnlockV11.sol
  packages/contracts/src/contracts/Unlock/UnlockV8.sol
  packages/contracts/src/contracts/Unlock/UnlockV9.sol
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinLockCore.sol
Labels: cla-signed

#9329 fix(networks): update Celo multisig address
  packages/networks/src/networks/celo.ts
Labels: cla-signed

#9328 feat(smart-contracts): update urls for gnosis multisig web service
  smart-contracts/scripts/all_networks.sh
  smart-contracts/scripts/multisig/submitTx.js
Labels: cla-signed

#9337 Ccarfi superfluid blog
  unlock-protocol-com/blog/superfluid-unlock.md
  unlock-protocol-com/public/images/blog/superfluid/superfluid-unlock-min.png
Labels: cla-signed

#9341 feat(unlock-app) - make email optional airdrop
  unlock-app/src/components/creator/members/GrantKeysDrawer.tsx
Labels: cla-signed

#9323 feat(unlock-protocol-com)blog post about Goerli launch
  unlock-protocol-com/blog/goerli.md
  unlock-protocol-com/public/images/blog/goerli/goerli-logo.png
Labels: cla-signed

#9339 chore(contracts): updated docs
  packages/contracts/bin/build_docs.sh
  packages/contracts/package.json
  packages/contracts/src/contracts/PublicLock/IPublicLockV10.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV11.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV8sol8.sol
  packages/contracts/src/contracts/PublicLock/IPublicLockV9.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV10.sol
  packages/contracts/src/contracts/PublicLock/PublicLockV9.sol
  packages/contracts/src/contracts/Unlock/UnlockV10.sol
  packages/contracts/src/contracts/Unlock/UnlockV11.sol
  scripts/docs-contracts-pr.sh
  smart-contracts/contracts/interfaces/IPublicLock.sol
Labels: cla-signed

#9344 feat(unlock-app): adding warning about Rinkeby going away
  unlock-app/src/components/content/DashboardContent.js
Labels: cla-signed

#9332 feat(unlock-protocol-com) - add upcoming events page
  unlock-protocol-com/package.json
  unlock-protocol-com/src/components/icons/Util.tsx
  unlock-protocol-com/src/components/interface/Navigation/index.tsx
  unlock-protocol-com/src/components/pages/UpcomingEvents/UpcomingEventBox.tsx
  unlock-protocol-com/src/components/pages/UpcomingEvents/index.tsx
  unlock-protocol-com/src/config/routes.tsx
  unlock-protocol-com/src/pages/upcoming-events.tsx
  unlock-protocol-com/src/utils/calendar.ts
  yarn.lock
Labels: cla-signed

#9325 feat(unlock-app) - get totals members from contract
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/package.json
  packages/unlock-js/src/web3Service.ts
  unlock-app/src/components/interface/members/MemberCard.tsx
  unlock-app/src/hooks/useMembers.ts
  unlock-app/src/queries/keysCount.ts
Labels: cla-signed

#9347 Update goerli.md
  unlock-protocol-com/blog/goerli.md
Labels: cla-signed

#9346 feat(unlock-protocol-com) - fix encode string and render description as html
  unlock-protocol-com/src/components/pages/UpcomingEvents/UpcomingEventBox.tsx
  unlock-protocol-com/src/utils/calendar.ts
Labels: cla-signed

#9348 chore(unlock-app, locksmith, wedlocks): cleanup ethcc
  locksmith/src/utils/keyPricer.ts
  unlock-app/src/components/interface/keychain/QRModal.tsx
  unlock-app/src/components/interface/verification/MembershipCard.tsx
  wedlocks/src/templates/index.js
  wedlocks/src/templates/locks/keyMined-0x072149617e12170696481684598a696e9a4d46Ff.js
  wedlocks/src/templates/locks/keyMined-0x89e975EA43E0Cfe338205e016BFFaeFeFdbc3511.js
  wedlocks/src/templates/locks/keyMined-0x926FBA2B47916Fcf58d165d44D6d9714d31Ee397.js
  wedlocks/src/templates/locks/keyMined-0x9AB351cB5DAe55abD135dD256726851aae8EFeB5.js
  wedlocks/src/templates/locks/keyMined-0xBB19b9E39cB06402bf17886708506dba0B8Eb2f2.js
  wedlocks/src/templates/locks/keyMined-0xD4e591519425C0180f38B0064d362679c432196e.js
  wedlocks/src/templates/locks/keyMined-0xb7958434e812C9D1a76560d43b2CfAAfe093eC08.js
  wedlocks/src/templates/locks/keyMined-0xd0A031d9f9486B1D914124D0C1FCAC2e9e6504FE.js
Labels: cla-signed

#9349 press kit set
  design/logo/Unlock-LogoMark-Circle.svg
  design/logo/Unlock-LogoMark-Circle@2x.png
  design/logo/Unlock-LogoMark-Square.svg
  design/logo/Unlock-LogoMark-Square@2x.png
  design/logo/Unlock-Protocol-Press-Kit-2022.07.pdf
  design/logo/Ʉnlock Symbol-white.svg
  design/logo/Ʉnlock Symbol-white@2x.png
  design/logo/Ʉnlock Symbol.svg
  design/logo/Ʉnlock Symbol@2x.png
  design/logo/Ʉnlock-Logo-monogram-black.png
  design/logo/Ʉnlock-Logo-monogram-black.svg
  design/logo/Ʉnlock-Logo-monogram-white.png
  design/logo/Ʉnlock-Logo-monogram-white.svg
  design/logo/Ʉnlock-Logo-symbol-round-beige.png
  design/logo/Ʉnlock-Logo-symbol-round-beige.svg
  design/logo/Ʉnlock-Logo-symbol-round-black.png
  design/logo/Ʉnlock-Logo-symbol-round-black.svg
  design/logo/Ʉnlock-Logo-symbol-square-beige.png
  design/logo/Ʉnlock-Logo-symbol-square-beige.svg
  design/logo/Ʉnlock-Logo-symbol-square-black.png
  design/logo/Ʉnlock-Logo-symbol-square-black.svg
  design/logo/Ʉnlock-full-logo-black.png
  design/logo/Ʉnlock-full-logo-black.svg
  design/logo/Ʉnlock-full-logo-white.png
  design/logo/Ʉnlock-full-logo-white.svg
  design/logo/Ʉnlock-full-logo.svg
  design/logo/Ʉnlock-full-logo@2x.png
Labels: cla-signed
