Repository unlock-protocol/unlock, pull requests merged in 2023-02, with the labels that each got.

#10826 feat(unlock-protocol-com) - transaction receipts blogpost
  unlock-protocol-com/blog/transaction-receipts.md
  unlock-protocol-com/public/images/blog/transaction-receipts/add-purchaser-details.png
  unlock-protocol-com/public/images/blog/transaction-receipts/for-purchaser.png
  unlock-protocol-com/public/images/blog/transaction-receipts/receipt-details-1.png
  unlock-protocol-com/public/images/blog/transaction-receipts/receipt-details-2.png
  unlock-protocol-com/public/images/blog/transaction-receipts/receipt-not-allowed.png
  unlock-protocol-com/public/images/blog/transaction-receipts/receipt-section.png
  unlock-protocol-com/public/images/blog/transaction-receipts/transaction-receipts-header.png
Labels: cla-signed

#10857 feat(checkout): Add expectedAddress option to paywallConfig
  unlock-app/src/components/interface/checkout/main/Select.tsx
  unlock-app/src/unlockTypes.tsx
Labels: cla-signed

#10858 feat(checkout): Wait for 2 confirmation before updating status on mint
  unlock-app/src/components/interface/checkout/main/Minting.tsx
  unlock-app/src/components/interface/checkout/main/Renewed.tsx
Labels: cla-signed

#10938 feat(unlock-app) - fix receipts controller
  locksmith/src/controllers/v2/receiptController.ts
  unlock-app/src/components/interface/Recipts/elements/ReceiptBox.tsx
Labels: cla-signed

#10940 fix(wedlocks) Opensea unhide
  wedlocks/src/templates/helpers/links.js
  wedlocks/src/templates/keyAirdropped.js
  wedlocks/src/templates/keyMined.js
Labels: cla-signed

#10942 revert(wedlocks): Downgrade node-mail and netlify-cli
  wedlocks/package.json
  yarn.lock
Labels: cla-signed

#10941 fix(smart-contracts): keep ownership record when a key is cancelled
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/contracts/mixins/MixinRefunds.sol
  smart-contracts/test/Lock/cancelAndRefund.js
Labels: cla-signed

#10930 feat(smart-contracts): bump `PublicLock` contract to v13
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/scripts/lock/testUpgrade.js
  smart-contracts/tasks/verify.js
  smart-contracts/test/Lock/upgrades/v12.js
  smart-contracts/test/helpers/constants.js
Labels: cla-signed

#10929 (smart-contracts): fix renovate PR #10459 + remove OZ upgrades plugin in Unlock versions tests
  smart-contracts/package.json
  smart-contracts/test/Lock/upgrades/v10.js
  smart-contracts/test/Lock/upgrades/v11.js
  smart-contracts/test/Lock/upgrades/v12.js
  smart-contracts/test/Unlock/migrateLockData/v10.js
  smart-contracts/test/Unlock/upgrades.js
  smart-contracts/test/UnlockDiscountToken/upgrades.js
  smart-contracts/test/helpers/ABIs/ProxyAdmin.json
  smart-contracts/test/helpers/ABIs/TransparentUpgradeableProxy.json
  smart-contracts/test/helpers/versions.js
  yarn.lock
Labels: cla-signed

#10934 refactor(unlock-app): Remove getTokenBalance
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/hooks/useAccount.ts
Labels: cla-signed

#10945 not redirecting users after lock deployed as this created confusion
  unlock-app/src/components/interface/locks/Create/elements/CreateLockFormSummary.tsx
Labels: cla-signed

#10947 Revert "(smart-contracts): fix renovate PR #10459 + remove OZ upgrade…
  smart-contracts/package.json
  smart-contracts/test/Lock/upgrades/v10.js
  smart-contracts/test/Lock/upgrades/v11.js
  smart-contracts/test/Lock/upgrades/v12.js
  smart-contracts/test/Unlock/migrateLockData/v10.js
  smart-contracts/test/Unlock/upgrades.js
  smart-contracts/test/UnlockDiscountToken/upgrades.js
  smart-contracts/test/helpers/ABIs/ProxyAdmin.json
  smart-contracts/test/helpers/ABIs/TransparentUpgradeableProxy.json
  smart-contracts/test/helpers/versions.js
  yarn.lock
Labels: cla-signed

#10933 feat(subgraph): Set cancelled to false by default
  subgraph/src/public-lock.ts
  tests/test/subgraph.ts
Labels: cla-signed

#9418 Unlock.sol Gas Optimized Contract Now
  smart-contracts/contracts/Unlock.sol
Labels: smart contract, cla-signed

#10955 feat(wedlocks): Enable opensea message for key purchases and improve styling
  wedlocks/src/templates/base/index.js
  wedlocks/src/templates/helpers/links.js
  wedlocks/src/templates/keyMined.js
Labels: cla-signed

#10951 feat(networks): Enable claim for test networks
  packages/networks/src/networks/goerli.ts
  packages/networks/src/networks/mumbai.ts
Labels: cla-signed

#10956 feature(unlock-app): adding link to event page
  unlock-app/src/components/interface/locks/metadata/TicketForm.tsx
  unlock-app/src/config/app.tsx
  yarn.lock
Labels: cla-signed

#10958 fix(unlock-app): adding support for Timezones when setting up event metadata
  unlock-app/src/components/content/event/AddToCalendarButton.tsx
  unlock-app/src/components/content/event/EventDetails.tsx
  unlock-app/src/components/content/event/TweetItButton.tsx
  unlock-app/src/components/content/event/utils.tsx
  unlock-app/src/components/interface/keychain/KeyInfoDrawer.tsx
  unlock-app/src/components/interface/locks/metadata/TicketForm.tsx
  unlock-app/src/components/interface/locks/metadata/utils.ts
Labels: cla-signed

#10960 fix master jest issue
  packages/eslint-config/package.json
  packages/eslint-config/src/base.js
Labels: cla-signed

#10963 chore: using yarn dedupe
  yarn.lock
Labels: cla-signed

#10957 feat(locksmith) - custom email content endpoint
  locksmith/__tests__/controllers/v2/customEmailController.test.ts
  locksmith/migrations/20230203140302-custom-email-content.js
  locksmith/src/controllers/v2/customEmailController.ts
  locksmith/src/models/customEmailContent.ts
  locksmith/src/routes/index.ts
  locksmith/src/routes/v2/email.ts
  packages/unlock-js/openapi.yml
Labels: cla-signed

#10953 feat(smart-contracts): fix renovate smart contracts + version testing (again)
  smart-contracts/package.json
  smart-contracts/test/Lock/upgrades/v10.js
  smart-contracts/test/Lock/upgrades/v11.js
  smart-contracts/test/Lock/upgrades/v12.js
  smart-contracts/test/Unlock/migrateLockData/v10.js
  smart-contracts/test/Unlock/upgrades.js
  smart-contracts/test/UnlockDiscountToken/upgrades.js
  smart-contracts/test/helpers/ABIs/ProxyAdmin.json
  smart-contracts/test/helpers/ABIs/TransparentUpgradeableProxy.json
  smart-contracts/test/helpers/versions.js
  yarn.lock
Labels: cla-signed

#10969 (locksmith) - add unique index to avoid duplicates for same lockAddress + template pair
  locksmith/migrations/20230203140302-custom-email-content.js
  locksmith/src/controllers/v2/customEmailController.ts
Labels: cla-signed

#10967 fix(smart-contracts): `getBalance` test helper default to use ethersjs
  smart-contracts/test/helpers/getTokenBalance.js
  smart-contracts/test/helpers/index.js
Labels: cla-signed

#10978 feat(email-templates) - add email template in is own package
  package.json
  packages/email-templates/.gitignore
  packages/email-templates/README.md
  packages/email-templates/package.json
  packages/email-templates/src/index.ts
  packages/email-templates/src/templates/confirmEmail.ts
  packages/email-templates/src/templates/debug.ts
  packages/email-templates/src/templates/keyAirdropped.ts
  packages/email-templates/src/templates/keyMined.ts
  packages/email-templates/src/templates/keyOwnership.ts
  packages/email-templates/src/templates/locks/index.ts
  packages/email-templates/src/templates/locks/keyMined-0x01703c979220de3e7662ab90a696843225d31383.ts
  packages/email-templates/src/templates/locks/keyMined-0x0Da7C68203a9331baEB388BC7e17430F188E4061.ts
  packages/email-templates/src/templates/locks/keyMined-0x5f1c54dEDE0d96F49EEd8F57f653b24d41f4BDd6.ts
  packages/email-templates/src/templates/locks/keyMined-0x7d9904bdCE826cADE55459083252C41E23e1F7F9.ts
  packages/email-templates/src/templates/locks/keyMined-0x838327F343382526e10E14ef6E9F588E69B37230.ts
  packages/email-templates/src/templates/locks/keyMined-0xc4bcBaa594843881Fc3957C9104965D0f7cFb1FF.ts
  packages/email-templates/src/templates/transferCode.ts
  packages/email-templates/src/templates/welcome.ts
  packages/email-templates/tsconfig.json
  yarn.lock
Labels: cla-signed

#10965 feature(unlock-app): landing page for events
  packages/ui/lib/components/Form/FieldLayout.tsx
  unlock-app/next.config.js
  unlock-app/public/images/illustrations/events/dappcon.png
  unlock-app/public/images/illustrations/events/easy.svg
  unlock-app/public/images/illustrations/events/ethcc.svg
  unlock-app/public/images/illustrations/events/metacartel.png
  unlock-app/public/images/illustrations/events/outmetaverse.svg
  unlock-app/public/images/illustrations/events/party.svg
  unlock-app/public/images/illustrations/events/qr.svg
  unlock-app/public/images/illustrations/events/verifier.svg
  unlock-app/src/__tests__/hooks/useLocks.test.jsx
  unlock-app/src/components/content/EventContent.tsx
  unlock-app/src/components/content/event/EventDetails.tsx
  unlock-app/src/components/content/event/Form.tsx
  unlock-app/src/components/content/event/LandingPage.tsx
  unlock-app/src/components/content/event/LockDeploying.tsx
  unlock-app/src/components/content/event/NewEvent.tsx
  unlock-app/src/components/content/event/TweetItButton.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockFormSummary.tsx
  unlock-app/src/components/interface/locks/elements/KeyPrice.tsx
  unlock-app/src/components/interface/locks/metadata/utils.ts
  unlock-app/src/config/app.tsx
  unlock-app/src/hooks/useLocks.js
  unlock-app/src/pages/event/new.tsx
Labels: cla-signed

#10984 feat(unlock-app) - show event location only when exists
  unlock-app/src/components/content/event/EventDetails.tsx
Labels: cla-signed

#10985 fix(unlock-js) ensuring we return a contract or throw
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/package.json
  packages/unlock-js/src/unlockService.ts
  yarn.lock
Labels: cla-signed

#10986 chore: adding lockFileMaintenance to renovate
  renovate.json
Labels: cla-signed

#10987 Ccarfi events launch
  unlock-protocol-com/blog/events-launch.md
  unlock-protocol-com/public/images/blog/events-by-unlock/event-configure.png
  unlock-protocol-com/public/images/blog/events-by-unlock/event-landing.png
  unlock-protocol-com/public/images/blog/events-by-unlock/events-share.png
  unlock-protocol-com/public/images/blog/events-by-unlock/events-subbrand-share.png
Labels: cla-signed

#10976 feat(smart-contracts): settings for hardhat to use forked node properly
  smart-contracts/hardhat.config.js
  smart-contracts/test/helpers/fork.js
  smart-contracts/test/helpers/multisig.js
Labels: cla-signed

#10973 fix(smart-contracts): bump hardhat and solidity-coverage
  smart-contracts/package.json
  yarn.lock
Labels: cla-signed

#10782 feat: Use batch json rpc when using ethers
  locksmith/__tests__/utils/gasPrice.test.ts
  locksmith/__tests__/utils/gasSettings.test.ts
  locksmith/__tests__/websub/renewKey.test.ts
  locksmith/src/fulfillment/tokenTransferApproval.ts
  locksmith/src/utils/gasPrice.ts
  locksmith/src/utils/gasSettings.ts
  locksmith/src/utils/lockData.ts
  locksmith/src/utils/lockMigrate.ts
  locksmith/src/websub/helpers/renewKey.ts
  packages/unlock-express/src/hasValidKey.js
  packages/unlock-js/src/unlockService.ts
  provider/tests/networks.test.ts
  smart-contracts/scripts/multisig/_helpers.js
  unlock-app/src/__tests__/hooks/useEns.test.jsx
  unlock-app/src/components/interface/checkout/main/Minting.tsx
  unlock-app/src/components/interface/checkout/main/Renewed.tsx
  unlock-app/src/hooks/useEns.ts
  unlock-app/src/services/unlockProvider.ts
  unlock-protocol-com/src/utils/apiRequest.ts
Labels: cla-signed, run-all-tests

#10981 feat(unlock-app): Rename recipient to wallet in airdrop and add more details on email airdrops
  unlock-app/public/templates/airdrop.csv
  unlock-app/src/components/interface/members/airdrop/AirdropBulkForm.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropDrawer.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropElements.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropManualForm.tsx
Labels: cla-signed

#10975 feat(smart-contracts): use OZ native role functions to manager KeyGranters
  smart-contracts/contracts/interfaces/IPublicLock.sol
  smart-contracts/contracts/mixins/MixinGrantKeys.sol
  smart-contracts/contracts/mixins/MixinRoles.sol
  smart-contracts/test/Lock/permissions/keyGranter.js
  smart-contracts/test/helpers/index.js
  smart-contracts/test/helpers/roles.js
Labels: cla-signed

#10977 feat(smart-contracts): use local `IUniswapOracleV3` in Unlock
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUniswapOracleV3.sol
  smart-contracts/contracts/utils/UniswapOracleV3.sol
Labels: cla-signed

#10932 feat(unlock-app) - fix failing update email on members page
  locksmith/src/controllers/v2/metadataController.ts
Labels: cla-signed

#10982 feature(unlock-app): adding a dedicated settings button
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#10991 fix(locksmith) adding migration fix
  locksmith/migrations/20230208144216-fix-missing-index.js
Labels: cla-signed

#10992 feat(unlock-app) - add vitest email-templates
  packages/email-templates/.gitignore
  packages/email-templates/package.json
  packages/email-templates/vite.config.ts
  yarn.lock
Labels: cla-signed

#10993 feat(email-templates) - Refactor email templates
  packages/email-templates/package.json
  packages/email-templates/src/index.ts
  packages/email-templates/src/templates/helpers/links.ts
  packages/email-templates/src/templates/keyAirdropped.ts
  packages/email-templates/src/templates/keyMined.ts
  packages/email-templates/src/templates/locks/index.ts
  yarn.lock
Labels: cla-signed

#10997 fix(smart-contracts): bypass delegatecall check on OZ upgrades plugin
  smart-contracts/test/Unlock/addLockTemplate.js
  smart-contracts/test/Unlock/createLockAtVersion.js
  smart-contracts/test/Unlock/migrateLockData/v10.js
  smart-contracts/test/Unlock/proxyAdmin.js
  smart-contracts/test/Unlock/upgradeLock.js
  smart-contracts/test/fixtures/deploy.js
  yarn.lock
Labels: cla-signed

#10994 Ccarfi add webinar
  unlock-protocol-com/blog/events-launch.md
Labels: cla-signed

#10999 Update events-launch.md
  unlock-protocol-com/blog/events-launch.md
Labels: cla-signed

#11002 feat(ui) - refactor address input
  packages/ui/lib/components/Form/AddressInput.tsx
  packages/ui/package.json
Labels: cla-signed

#11003 feat(unlock-js) - fix resolve name
  packages/unlock-js/CHANGELOG.md
  packages/unlock-js/package.json
  packages/unlock-js/src/web3Service.ts
Labels: cla-signed

#11006 feat(ui) - prevent localForm type issue
  packages/ui/lib/components/Form/AddressInput.tsx
Labels: cla-signed

#11001 fix(locksmith): Handle showing metadata image url when it is saved for a lock
  locksmith/src/controllers/lockController.ts
Labels: cla-signed

#11012 feat(scripts): add `run-stack` scripts
  scripts/integration-tests.sh
  scripts/run-stack-dockerized.sh
  scripts/run-stack-local.sh
  tests/README.md
  tests/bin/tests.sh
  tests/package.json
Labels: cla-signed

#10944 feature(unlock-app): autoconnect and delegated providers
  packages/paywall/src/utils/index.ts
  packages/types/src/types/unlockTypes.ts
  unlock-app/src/components/interface/checkout/Connected.tsx
  unlock-app/src/components/interface/checkout/main/index.tsx
  unlock-app/src/unlockTypes.tsx
  yarn.lock
Labels: cla-signed

#11008 feat(wedlocks) - add custom template
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/package.json
  locksmith/src/operations/wedlocksOperations.ts
  packages/email-templates/src/__tests__/templates/keyMined.test.ts
  packages/email-templates/src/templates/base/index.ts
  packages/email-templates/src/templates/keyAirdropped.ts
  packages/email-templates/src/templates/keyMined.ts
  yarn.lock
Labels: cla-signed

#10937 feat(unlock-app) - customize recipients for withdrawal
  unlock-app/src/components/interface/locks/Manage/elements/TotalBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11015 fix(networks): using xDAI for the currency name on Gnosis Chain
  packages/networks/src/networks/gnosis.ts
Labels: cla-signed

#11013 fix(unlock-app): Remove timeout in autologin
  unlock-app/src/hooks/useAutoLogin.ts
Labels: cla-signed

#11016 fix(unlock-app): showing time in the event's tz
  unlock-app/src/components/content/event/EventDetails.tsx
  unlock-app/src/components/interface/keychain/KeyInfoDrawer.tsx
Labels: cla-signed

#11018 fix(locksmith): fixing pricer by introducing the coinbase ticker
  locksmith/src/utils/keyPricer.ts
  packages/networks/src/networks/gnosis.ts
  packages/types/src/types/unlockTypes.ts
Labels: cla-signed

#10990 feat(unlock-app): Add getWalletService and remove explicit network switch handling from code
  packages/unlock-js/src/walletService.ts
  unlock-app/src/__tests__/hooks/useLocks.test.jsx
  unlock-app/src/components/content/event/Form.tsx
  unlock-app/src/components/content/event/NewEvent.tsx
  unlock-app/src/components/creator/members/ExtendKeysDrawer.tsx
  unlock-app/src/components/helpers/Auth.tsx
  unlock-app/src/components/helpers/SwitchNetwork.tsx
  unlock-app/src/components/interface/Authenticate.jsx
  unlock-app/src/components/interface/ExpireAndRefundModal.tsx
  unlock-app/src/components/interface/checkout/main/Confirm.tsx
  unlock-app/src/components/interface/checkout/main/Renew.tsx
  unlock-app/src/components/interface/checkout/main/Select.tsx
  unlock-app/src/components/interface/keychain/CancelAndRefundModal.tsx
  unlock-app/src/components/interface/keychain/Extend.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/keychain/KeyInfoDrawer.tsx
  unlock-app/src/components/interface/locks/Create/CreateLock.tsx
  unlock-app/src/components/interface/locks/Create/elements/CreateLockForm.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MemberCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MetadataCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/TotalBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
  unlock-app/src/components/interface/locks/Settings/elements/SettingTerms.tsx
  unlock-app/src/components/interface/locks/Settings/forms/CancellationForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/CreditCardForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/LockManagerForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateBaseTokenURI.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateDurationForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateHooksForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateMaxKeysPerAddress.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateNameForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdatePriceForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateQuantityForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateReferralFee.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateSymbolForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateTransferFee.tsx
  unlock-app/src/components/interface/locks/Settings/forms/UpdateVersionForm.tsx
  unlock-app/src/components/interface/locks/elements/KeyPrice.tsx
  unlock-app/src/components/interface/locks/metadata/index.tsx
  unlock-app/src/components/interface/members/airdrop/AirdropDrawer.tsx
  unlock-app/src/components/interface/transfer/index.tsx
  unlock-app/src/config/app.tsx
  unlock-app/src/contexts/AuthenticationContext.tsx
  unlock-app/src/hooks/useKeyManager.ts
  unlock-app/src/hooks/useLocks.js
  unlock-app/src/hooks/usePrice.ts
  unlock-app/src/hooks/useProvider.ts
Labels: cla-signed

#11021 Update unlockTypes.tsx
  unlock-app/src/unlockTypes.tsx
Labels: cla-signed

#11020 Ccarfi homepage carousel
  unlock-protocol-com/public/images/marketing/projects/coindesk.jpg
  unlock-protocol-com/public/images/marketing/projects/forbes.png
  unlock-protocol-com/public/images/marketing/projects/socialmediaexaminer.jpg
  unlock-protocol-com/public/images/marketing/projects/techcrunch.png
  unlock-protocol-com/public/images/marketing/projects/wired.png
  unlock-protocol-com/src/components/pages/Home/sections/Projects.tsx
Labels: cla-signed

#10946 feat(unlock-app) - add email section + template customization
  unlock-app/src/components/interface/locks/Settings/elements/EmailTemplatePreview.tsx
  unlock-app/src/components/interface/locks/Settings/elements/SettingEmail.tsx
  unlock-app/src/components/interface/locks/Settings/index.tsx
  unlock-app/src/pages/locks/settings.tsx
Labels: cla-signed

#10966 feat(locksmith): Run renewal jobs weekly and monthly
  locksmith/src/graphql/datasource/keysToRenew.ts
  locksmith/src/websub/helpers/renewal.ts
  locksmith/src/websub/jobs/index.ts
  locksmith/src/websub/jobs/renewFiatKeys.ts
  locksmith/src/websub/jobs/renewKeys.ts
  locksmith/src/websub/server.ts
Labels: cla-signed

#11023 feat(unlock-app) - show template html preview + styling
  packages/email-templates/src/templates/base/index.ts
  unlock-app/src/components/interface/locks/Settings/elements/EmailTemplatePreview.tsx
Labels: cla-signed

#11026 feat(ui): Upgrade storybook version
  packages/ui/.babelrc.json
  packages/ui/.storybook/main.js
  packages/ui/package.json
  yarn.lock
Labels: cla-signed

#11028 fix(email-templates): adding margin around custom block
  packages/email-templates/src/templates/base/index.ts
Labels: cla-signed

#11025 feat(ui) - HeaderNav add custom content actions
  packages/ui/lib/components/HeaderNav/HeaderNav.tsx
Labels: cla-signed

#11031 feat(unlock-app) - AddressInput refactor
  packages/ui/lib/components/Form/AddressInput.tsx
  packages/ui/package.json
Labels: cla-signed

#11032 feat(ui): Upgrade storybook version
  packages/ui/.babelrc.json
  packages/ui/.storybook/main.js
  packages/ui/package.json
  yarn.lock
Labels: cla-signed

#11030 feat(unlock-app) - change email image
  unlock-app/public/images/illustrations/img-email.svg
  unlock-app/src/components/interface/locks/Settings/index.tsx
Labels: cla-signed

#11037 feat(unlock-app) - show email preview without custom content
  unlock-app/src/components/interface/locks/Settings/elements/EmailTemplatePreview.tsx
Labels: cla-signed

#11038 feature(unlock-app): requiring email on the demo page
  unlock-app/src/components/content/DemoContent.jsx
Labels: cla-signed

#11040 feat(unlock-app) - pass parameters email preview
  unlock-app/src/components/interface/locks/Settings/elements/EmailTemplatePreview.tsx
Labels: cla-signed

#11041 feat(unlock-app) - fix case
  packages/ui/lib/components/Disclosure/Disclosure.tsx
  unlock-app/src/components/interface/locks/Settings/elements/SettingEmail.tsx
Labels: cla-signed

#11039 feat(unlock-app) - remove check for beneficiary
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11046 feat(ui) - address input fix
  packages/ui/lib/components/Form/AddressInput.stories.tsx
  packages/ui/lib/components/Form/AddressInput.tsx
Labels: cla-signed

#11043 fix(locksmith): lock managers and key owners can generate QR code
  locksmith/src/controllers/v2/ticketsController.tsx
  locksmith/src/routes/v2/ticket.ts
  locksmith/src/utils/middlewares/lockManagerOrKeyOwner.ts
  packages/unlock-js/openapi.yml
Labels: cla-signed

#11045 feat(smart-contracts): improve scripts ro run a task for all unlock networks
  smart-contracts/scripts/all_networks
  smart-contracts/scripts/all_networks.sh
Labels: cla-signed

#10931 feat(smart-contracts): prepare Unlock migration on mainnet
  smart-contracts/.openzeppelin/mainnet.json
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/MixinKeys.sol
  smart-contracts/scripts/deployments/unlock.js
  smart-contracts/scripts/multisig/_helpers.js
  smart-contracts/test/Unlock/migration.mainnet.js
  tests/package.json
  yarn.lock
Labels: cla-signed

#11047 feat(unlock-app) - address input replace
  unlock-app/src/components/interface/locks/Settings/forms/LockManagerForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/VerifierForm.tsx
Labels: cla-signed

#11050 feat(locksmith) - Locksmith fix custom email
  locksmith/__tests__/operations/wedlocksOperations.test.ts
  locksmith/src/controllers/v2/customEmailController.ts
  locksmith/src/operations/emailOperations.ts
  locksmith/src/operations/wedlocksOperations.ts
Labels: cla-signed

#11052 feat(email-templates) - revert inline image
  packages/email-templates/src/templates/keyAirdropped.ts
  packages/email-templates/src/templates/keyMined.ts
Labels: cla-signed

#11051 feature(locksmith): Adding verification url
  locksmith/src/controllers/v2/ticketsController.tsx
  locksmith/src/routes/v2/ticket.ts
  locksmith/src/utils/qrcode.ts
  packages/unlock-js/openapi.yml
Labels: cla-signed

#11055 feat(ui) - temp remove dafault value address input
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11033 feat(smart-contracts): UnlockSwapPurchaser deployments
  packages/networks/src/networks/arbitrum.ts
  packages/networks/src/networks/celo.ts
  packages/networks/src/networks/goerli.ts
  packages/networks/src/networks/mainnet.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/src/networks/optimism.ts
  packages/networks/src/networks/polygon.ts
  packages/types/src/types/unlockTypes.ts
  smart-contracts/scripts/all_networks
  smart-contracts/scripts/deployments/swapper.js
Labels: cla-signed

#11056 feat(unlock-app): Sort networks on the lock page by preference
  unlock-app/src/components/interface/locks/List/elements/LockList.tsx
Labels: cla-signed

#11065 fix(unlock-app, wedlocks): small fixes to emails
  packages/email-templates/src/templates/base/index.ts
  packages/email-templates/src/templates/helpers/customContentStyle.ts
  packages/email-templates/src/templates/keyAirdropped.ts
  packages/email-templates/src/templates/keyMined.ts
  unlock-app/src/components/interface/locks/Settings/elements/SettingEmail.tsx
  unlock-app/src/components/interface/locks/Settings/index.tsx
Labels: cla-signed

#11063 Update events-launch.md
  unlock-protocol-com/blog/events-launch.md
Labels: cla-signed

#11066 Ccarfi treasurehunt blog post
  unlock-protocol-com/blog/treasure-hunt.md
  unlock-protocol-com/public/images/blog/treasure-hunt-share.png
Labels: cla-signed

#11062 feat(ui) - address input refactor
  packages/ui/lib/components/Form/AddressInput.stories.tsx
  packages/ui/lib/components/Form/AddressInput.tsx
  packages/ui/lib/components/Form/Input.tsx
Labels: cla-signed

#11070 refactor(locksmith): Add new endpoint for serving image and remove redirect
  locksmith/src/controllers/lockController.ts
  locksmith/src/models/index.ts
  locksmith/src/operations/lockOperations.ts
  locksmith/src/routes/lock.ts
  locksmith/src/utils/normalizer.ts
  locksmith/tsconfig.json
Labels: cla-signed

#11072 Fix(unlock-app): fixing some TS errors
  packages/ui/lib/components/Form/AddressInput.tsx
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
  unlock-app/src/components/interface/locks/Settings/forms/LockManagerForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/VerifierForm.tsx
Labels: cla-signed

#9456 feat(unlock-app): Add ethpass integration
  packages/ui/lib/index.tsx
  unlock-app/next.config.js
  unlock-app/package.json
  unlock-app/public/images/illustrations/apple-wallet.svg
  unlock-app/public/images/illustrations/google-wallet.svg
  unlock-app/public/images/unlock.png
  unlock-app/src/__tests__/hooks/useMetadata.test.jsx
  unlock-app/src/components/interface/checkout/main/Minting.tsx
  unlock-app/src/components/interface/keychain/AddToPhoneWallet.tsx
  unlock-app/src/components/interface/keychain/Key.tsx
  unlock-app/src/components/interface/verification/Scanner.tsx
  unlock-app/src/config/app.tsx
  unlock-app/src/hooks/useMetadata.js
  unlock-app/src/services/ethpass.ts
  unlock-protocol-com/public/images/unlock.png
  yarn.lock
Labels: cla-signed

#11064 feat(unlock-app) - withdraw modal refactor
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
  unlock-app/src/components/interface/locks/Settings/forms/LockManagerForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/VerifierForm.tsx
Labels: cla-signed

#11071 chore: making sure we run build on ci to identify TS issues before deployments
  locksmith/__mocks__/websub/subscriber.ts
  locksmith/package.json
  locksmith/scripts/create_access_token.ts
  locksmith/scripts/send_email.ts
  locksmith/src/routes/v2/images.ts
  locksmith/src/websub/helpers/notify.ts
  locksmith/tsconfig.json
  packages/paywall/package.json
  packages/unlock-js/package.json
  paywall-app/package.json
  unlock-app/package.json
  unlock-protocol-com/package.json
  yarn.lock
Labels: cla-signed

#11075 feat(subgraph): add nonFatalErrors for subgraph
  subgraph/src/helpers.ts
  subgraph/subgraph.yaml
Labels: cla-signed

#11024 feat(unlock-app) - use HeaderNav unlock-app
  unlock-app/src/components/interface/AppHeader.tsx
  unlock-app/src/components/interface/layouts/AppLayout.tsx
Labels: cla-signed

#11078 feat(unlock-app) - add back button to the checkout builder
  unlock-app/src/components/interface/locks/CheckoutUrl/index.tsx
Labels: cla-signed

#11077 feat(unlock-app) - withdraw validation
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11083 fix(unlock-app): Small UI tweaks
  unlock-app/src/components/interface/checkout/ViewContract.tsx
  unlock-app/src/components/interface/checkout/main/Confirm.tsx
  unlock-app/src/components/interface/checkout/main/Payment.tsx
  unlock-app/src/components/interface/checkout/main/Quantity.tsx
  unlock-app/src/components/interface/checkout/main/Renew.tsx
  unlock-app/src/components/interface/checkout/main/Select.tsx
Labels: cla-signed

#11084 feature(unlock-app): Checkout create account
  unlock-app/src/components/interface/checkout/Connected.tsx
  unlock-app/src/components/interface/checkout/UnlockAccount/EnterEmail.tsx
  yarn.lock
Labels: cla-signed

#11086 feature(unlock-app): removed superfluid for now
  package.json
  unlock-app/src/components/interface/checkout/main/Confirm.tsx
  unlock-app/src/components/interface/checkout/main/Payment.tsx
  unlock-app/src/components/interface/checkout/main/checkoutMachine.ts
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/DynamicForm.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/LocksForm.tsx
  unlock-app/src/unlockTypes.tsx
  yarn.lock
Labels: cla-signed

#11080 feat(unlock-app) - use AddressInput for airdrop
  unlock-app/src/components/interface/members/airdrop/AirdropManualForm.tsx
Labels: cla-signed

#11088 feat(unlock-app) - check benificiary when changes
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11090 fix(locksmith): getRequestURL does not work properly due to proxy
  locksmith/src/app.ts
  locksmith/src/utils/normalizer.ts
Labels: cla-signed

#11089 fix(keychain): Add one more breakpoint to grid
  unlock-app/src/components/interface/keychain/KeyDetails.tsx
Labels: cla-signed

#11076 feat(unlock-app) - improve AddressInput validation
  packages/ui/lib/components/Form/AddressInput.stories.tsx
  packages/ui/lib/components/Form/AddressInput.tsx
  packages/ui/lib/utils.ts
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
  unlock-app/src/components/interface/locks/Settings/forms/LockManagerForm.tsx
  unlock-app/src/components/interface/locks/Settings/forms/VerifierForm.tsx
Labels: cla-signed

#11096 feature(unlock-protocol-com): adding blog post for ethpass launch
  unlock-protocol-com/blog/apple-google-pass-nft.md
  unlock-protocol-com/public/images/blog/apple-pass-google-pass/apple-pass-checkout.png
  unlock-protocol-com/public/images/blog/apple-pass-google-pass/ethpass.png
  unlock-protocol-com/public/images/blog/apple-pass-google-pass/google-pass-keychain.png
Labels: cla-signed

#11099 feat(unlock-app) - use detail component
  unlock-app/src/components/interface/Receipts/elements/ReceiptBox.tsx
  unlock-app/src/components/interface/locks/List/elements/LockCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/TotalBar.tsx
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11095 feature(unlock-app): adding ethpass on the already unlocked page as well
  unlock-app/src/components/interface/checkout/main/Returning.tsx
  yarn.lock
Labels: cla-signed

#11100 feat(unlock-app) - fix logo redirect
  packages/ui/lib/components/HeaderNav/HeaderNav.tsx
  unlock-app/src/components/interface/layouts/AppLayout.tsx
Labels: cla-signed

#11101 feat(unlock-app) - add loading placeholder withdraw
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11106 Update ethpass.ts
  unlock-app/src/services/ethpass.ts
Labels: cla-signed

#11105 feat(unlock-app) - add edit metadata link with keyId
  unlock-app/src/components/interface/locks/Manage/elements/MetadataCard.tsx
Labels: cla-signed

#11109 feat(unlock-app) - fix missing docs link
  unlock-app/src/components/interface/locks/Settings/elements/SettingMisc.tsx
Labels: cla-signed

#11110 feat(ui) - detail component more flexible
  packages/ui/lib/components/Detail/Detail.tsx
Labels: cla-signed

#11108 feat(unlock-app) - add hooks in network
  packages/networks/src/networks/arbitrum.ts
  packages/networks/src/networks/bsc.ts
  packages/networks/src/networks/gnosis.ts
  packages/networks/src/networks/goerli.ts
  packages/networks/src/networks/mainnet.ts
  packages/networks/src/networks/mumbai.ts
  packages/networks/src/networks/optimism.ts
  packages/networks/src/networks/polygon.ts
  packages/types/src/types/unlockTypes.ts
Labels: cla-signed

#11113 feat(unlock-app) - fix responsive menage lock page
  unlock-app/src/components/interface/locks/Manage/elements/MemberCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MetadataCard.tsx
  unlock-app/src/components/interface/locks/Manage/index.tsx
Labels: cla-signed

#11111 feat(unlock-protocol-com): Add blog post for image upload
  unlock-protocol-com/blog/support-for-uploading-image.md
  unlock-protocol-com/public/images/blog/support-for-uploading-images/image_upload.png
Labels: cla-signed

#11121 fix(unlock-app): withdraws to beneficiary
  unlock-app/src/components/interface/locks/Manage/elements/WithdrawFundModal.tsx
Labels: cla-signed

#11122 feat(unlock): Add @unlock-protocol/core package
  package.json
  packages/core/.gitignore
  packages/core/README.md
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/schema.ts
  packages/core/tsconfig.json
  unlock-app/package.json
  unlock-app/src/components/interface/checkout/Connect/Confirm.tsx
  unlock-app/src/components/interface/checkout/Connect/index.tsx
  unlock-app/src/components/interface/checkout/UnlockAccount/unlockAccountMachine.typegen.ts
  unlock-app/src/components/interface/checkout/main/Metadata.tsx
  unlock-app/src/components/interface/checkout/main/checkoutMachine.ts
  unlock-app/src/components/interface/checkout/main/index.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/CheckoutPreview.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/LocksForm.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/index.tsx
  unlock-app/src/hooks/useCheckoutCommunication.ts
  unlock-app/src/unlockTypes.tsx
  unlock-app/src/utils/userMetadata.ts
  yarn.lock
Labels: cla-signed

#11102 feat(unlock-app) - fix missing custom option lock picker
  unlock-app/src/components/interface/Picker/index.tsx
  unlock-app/src/components/interface/locks/CheckoutUrl/elements/LocksForm.tsx
Labels: cla-signed

#11123 feat(ui) - Upgrade Storybook stories
  packages/ui/lib/components/Alert/Alert.stories.tsx
  packages/ui/lib/components/Badge/Badge.stories.tsx
  packages/ui/lib/components/Box/Box.stories.tsx
  packages/ui/lib/components/Button/Button.stories.tsx
  packages/ui/lib/components/CodeBox/CodeBox.stories.tsx
  packages/ui/lib/components/CodeBox/TabbedCodeBox.stories.tsx
  packages/ui/lib/components/Collapse/Collapse.stories.tsx
  packages/ui/lib/components/Drawer/Drawer.stories.tsx
  packages/ui/lib/components/Footer/Footer.stories.tsx
  packages/ui/lib/components/Form/AddressInput.stories.tsx
  packages/ui/lib/components/Form/Input.stories.tsx
  packages/ui/lib/components/Form/TextBox.stories.tsx
  packages/ui/lib/components/HeaderNav/HeaderNav.stories.tsx
  packages/ui/lib/components/IconButton/IconButton.stories.tsx
  packages/ui/lib/components/ImageUpload/ImageUpload.stories.tsx
  packages/ui/lib/components/Modal/Modal.stories.tsx
  packages/ui/lib/components/Placeholder/Placeholder.stories.tsx
  packages/ui/lib/components/Select/Select.stories.tsx
  packages/ui/lib/components/Ticket/Ticket.stories.tsx
  packages/ui/lib/components/Toggle/Toggle.stories.tsx
  packages/ui/lib/components/ToggleSwitch/ToggleSwitch.stories.tsx
  packages/ui/lib/components/Tooltip/Tooltip.stories.tsx
Labels: cla-signed

#11124 cleanup
  unlock-app/src/__tests__/components/helpers/Duration.test.tsx
  unlock-app/src/__tests__/components/page/opengraph.test.jsx
  unlock-app/src/__tests__/test-helpers/fixtures/signatureData.js
  unlock-app/src/__tests__/utils/types.test.js
  unlock-app/src/components/content/DashboardContent.tsx
  unlock-app/src/components/content/DemoContent.tsx
  unlock-app/src/components/content/HomeContent.tsx
  unlock-app/src/components/creator/members/ExtendKeysDrawer.tsx
  unlock-app/src/components/helpers/Duration.tsx
  unlock-app/src/components/helpers/toast.helper.ts
  unlock-app/src/components/interface/Account.tsx
  unlock-app/src/components/interface/Drawer.tsx
  unlock-app/src/components/interface/locks/Manage/elements/MemberCard.tsx
  unlock-app/src/components/interface/transfer/index.tsx
  unlock-app/src/components/interface/user-account/PaymentDetails.tsx
  unlock-app/src/components/interface/user-account/PaymentMethods.tsx
  unlock-app/src/components/page/OpenGraphTags.jsx
  unlock-app/src/components/page/OpenGraphTags.tsx
  unlock-app/src/components/page/TwitterTags.tsx
  unlock-app/src/hooks/useKeyManager.ts
  unlock-app/src/pages/index.tsx
  unlock-app/src/propTypes.tsx
  unlock-app/src/utils/types.ts
Labels: cla-signed

#11126 refactor(unlock-app): Cleanup old compatbility check from verificaiton scanner
  unlock-app/src/components/interface/VerificationStatus.tsx
Labels: cla-signed

#11125 feat(locksmith): Add checkout config endpoints
  locksmith/migrations/20230224113602-add-checkout-config.js
  locksmith/package.json
  locksmith/src/controllers/v2/checkoutController.ts
  locksmith/src/models/checkoutConfig.ts
  locksmith/src/models/index.ts
  locksmith/src/routes/index.ts
  locksmith/src/routes/v2/checkoutConfigs.ts
  packages/unlock-js/openapi.yml
  yarn.lock
Labels: cla-signed

#11127 feat(unlock-app) - simplify hooks page logic
  packages/types/src/types/unlockTypes.ts
  unlock-app/src/components/interface/locks/Settings/forms/UpdateHooksForm.tsx
Labels: cla-signed

#11134 fix(smart-contracts): lower PublicLock contract size (again)
  smart-contracts/contracts/mixins/MixinPurchase.sol
Labels: cla-signed

#11135 feat(smart-contracts): emit a `ReferrerFee` event
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Lock/setReferrerFee.js
Labels: cla-signed

#11137 feat(unlock-app) - Lock setting UI adjustment
  unlock-app/public/images/illustrations/img-email.svg
  unlock-app/public/images/illustrations/img-general.svg
  unlock-app/public/images/illustrations/img-misc.svg
  unlock-app/public/images/illustrations/img-payment.svg
  unlock-app/public/images/illustrations/img-roles.svg
  unlock-app/public/images/illustrations/img-terms.svg
  unlock-app/src/components/interface/locks/Settings/index.tsx
Labels: cla-signed

#11141 feat(provider): Add support for resolving redirect
  provider/src/handler.ts
  provider/tsconfig.json
Labels: cla-signed

#11140 feat(unlock-app) - transfer fee fix
  unlock-app/src/components/interface/locks/Settings/forms/UpdateTransferFee.tsx
Labels: cla-signed

#11146 feat(network): Increase claim limit on arbitrum to 100 cents
  packages/networks/src/networks/arbitrum.ts
Labels: cla-signed

#11143 feat(provider): Refactor provider and increase cache time
  provider/src/handler.ts
Labels: cla-signed

#11142 feat(unlock-app): Add support for resolving eth pass QR code directly
  unlock-app/package.json
  unlock-app/src/components/interface/verification/Scanner.tsx
  unlock-app/src/config/app.ts
  yarn.lock
Labels: cla-signed

#11148 fix(unlock-app): Linting fix
  unlock-app/src/components/interface/verification/invalidMembership.ts
Labels: cla-signed

#11149 change(unlock-app): Allow claim always even if user has balance on arbitrum
  unlock-app/src/components/interface/checkout/main/Payment.tsx
Labels: cla-signed

#11153 feat(smart-contracts): emit `EventHooksUpdated` event
  smart-contracts/contracts/mixins/MixinLockCore.sol
  smart-contracts/test/Lock/onKeyCancelHook.js
  smart-contracts/test/Lock/onKeyExtendHook.js
  smart-contracts/test/Lock/onKeyGrantHook.js
  smart-contracts/test/Lock/onKeyPurchaseHook.js
  smart-contracts/test/Lock/onKeyTransferHook.js
  smart-contracts/test/Lock/onTokenURIHook.js
  smart-contracts/test/Lock/onValidKeyHook.js
Labels: cla-signed

#11022 feat(smart-contracts): implement protocol fee
  smart-contracts/contracts/Unlock.sol
  smart-contracts/contracts/interfaces/IUnlock.sol
  smart-contracts/contracts/mixins/MixinPurchase.sol
  smart-contracts/test/Unlock/protocolFee.js
  smart-contracts/test/helpers/deployLocks.js
  smart-contracts/test/helpers/lock.js
Labels: cla-signed

#11157 feat(unlock-app) - fix check for children
  packages/ui/lib/components/Detail/Detail.tsx
Labels: cla-signed

#11156 fix(unlock-app): Signer addresses passed as an array instead of string
  unlock-app/src/components/interface/VerificationStatus.tsx
  unlock-app/src/utils/signatures.ts
Labels: cla-signed

#11159 refactor(unlock-app): Refactor injected provider detection into a function
  unlock-app/src/components/interface/LoginPrompt.tsx
  unlock-app/src/components/interface/checkout/Connect/connectMachine.typegen.ts
  unlock-app/src/components/interface/checkout/Connected.tsx
  unlock-app/src/utils/wallet.ts
Labels: cla-signed

#11158 fix(unlock-app): Add an explicit check for token Id on checkout when optimistic
  unlock-app/src/components/interface/checkout/Connect/connectMachine.typegen.ts
  unlock-app/src/components/interface/checkout/main/Minting.tsx
Labels: cla-signed

#11160 refactor(unlock-app): Remove old lock icon change modal
  packages/ui/lib/components/ImageUpload/ImageUpload.stories.tsx
  packages/ui/lib/components/ImageUpload/ImageUpload.tsx
  unlock-app/src/components/interface/locks/List/elements/LockCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockDetailCard.tsx
  unlock-app/src/components/interface/locks/Manage/elements/LockIcon.tsx
  unlock-app/src/components/interface/locks/metadata/index.tsx
Labels: cla-signed
